St4tely raven test map patch 1
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #122
Opened 2021-02-04 14:06 UTC by St4telyRaven

### Brief description of the changes:
---Fill in---

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2021-02-04 14:20 UTC, AwesomePatrol commented on maps/biter_battles_v2/ai.lua
> +    local tick = game.tick
Wrong tick source. Please apply: https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/commit/6fa5174bfae12ca4a2ed57d759f3ed38c96e16ad

2021-02-05 16:49 UTC, guymaor86 commented on maps/biter_battles_v2/grenades.lua
> +	return x*x
you can use the builtin function `math.pow(x,2)`

2021-02-05 21:19 UTC, guymaor86 requested changes
what is `maps/biter_battles_v2 - test.7z` new file?
we should delete it

2021-02-05 21:54 UTC, St4telyRaven commented
yes


On Fri, Feb 5, 2021 at 1:20 PM guymaor86 <notifications@github.com> wrote:

> *@guymaor86* requested changes on this pull request.
>
> what is maps/biter_battles_v2 - test.7z new file?
> we should delete it
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/pull/122#pullrequestreview-584714765>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARV62OHR3CNJE7ZT7ULT5GDS5ROIFANCNFSM4XC4NKGA>
> .
>

2021-03-12 18:55 UTC, guppyfaced commented
You'll need to merge the changes to resolve the conflicts.

To keep things simple, I would recommend opening a request for each feature (difficulty, biter swarm size, etc) separately.

2021-03-12 22:22 UTC, closed without merging