add parameters for spawn ore in tables.lua
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #175
Opened 2021-06-01 16:24 UTC by Max01000

Brief description of the changes:
parameters that can be changed.
size = 23, density = 3000, big_patches = 2, small_patches = 1

functions added:
generate_spawn_ore
premutate_table
clear_ore_in_main

deleted: generate_additional_spawn_ore

### Tested Changes:
- [ ] I've tested the changes locally or with people.

2021-06-01 17:42 UTC, 1pulse commented
nice, does this also include approx X2 iron at main?

2021-06-01 17:47 UTC, Max01000 commented
> nice, does this also include approx X2 iron at main? 

yup it has more iron. not sure if it is exactly 2x.

2021-06-04 13:58 UTC, cogito123 requested changes
I like those changes, but whole mechanism can be simplified.
Also please reuse current PR instead of opening new ones.

2021-06-04 13:58 UTC, cogito123 commented on maps/biter_battles_v2/terrain.lua
> +		{x = 69, y = -88}
There is no clear pattern to those value. To me those positions look random. If you add random to random you get random. So instead of typing them like that, you could do:

```lua
for x = -2, 2, 1 do
    for y = 0, -4, -1 do
         grid[#grid + 1] = {
             x = x * 32 + math.random(-5, 5),
             y = y * 32 + math.random(-8, 8)
         }
    end
end
```
This will also easier code for ore patches generation. Each chunks have 32 tiles in them on every axis. It's more readable if you operate on "standard" units. My snippet should yield almost the same result.

2021-06-04 13:58 UTC, cogito123 commented on maps/biter_battles_v2/terrain.lua
> +				x = grid[grid_index].x + math_random(-5, 5),
If you apply my previous suggestion to grid coordinates computing, then you can make this less complex if you do:
```lua
for ...
    local idx = math.random(1, #grid)
    local pos = grid[idx]
    table.remove(grid, idx)
    draw_...
end
```
You no longer need permutation and you don't have to keep track of grid index, since used positions will be removed from pool of candidates.

2021-06-06 08:51 UTC, cogito123 requested changes
The code looks much better, it's readable and somewhat organized. My big complaint goes towards commit series. It should be squashed and rebased properly. For example you introduce `bb: terrain: add premutate_table` and `bb: terrain: delete premutate_table` which looks chaotic at least. If your tool lacks a `rebase` functionality then it's time to change it for something better.

Another complaint goes towards commit messages. They don't explain the "why" behind your changes. I already posted link to one of the best guide about writing proper commit messages, so please kindly follow the tips from it: https://chris.beams.io/posts/git-commit/

2021-06-06 08:51 UTC, cogito123 commented on maps/biter_battles_v2/terrain.lua
> +function generate_oref(grid,count,ore,surface,size)
If you don't plan to export it, it should be 'local function'

2021-06-06 08:51 UTC, cogito123 commented on maps/biter_battles_v2/terrain.lua
> +function generate_oref(grid,count,ore,surface,size)
Please put spaces between function's parameters.

2021-06-06 08:51 UTC, cogito123 commented on maps/biter_battles_v2/terrain.lua
> +		local idx = math.random(1, #grid)
Move local variable declarations before for loop block. Variables will be allocated in each loop cycle if you don't do that.

2021-06-06 08:51 UTC, cogito123 commented on maps/biter_battles_v2/terrain.lua
> +		for x = -2, 2, 1 do
There is extra indentation, please remove it.

2021-06-06 08:51 UTC, cogito123 commented on maps/biter_battles_v2/terrain.lua
> +					f = -12
Variables such as this should have a very clear comment what they are and what they do. I assume it adjusts the positioning above spawn circle.

2021-06-06 08:51 UTC, cogito123 commented on maps/biter_battles_v2/terrain.lua
> +		generate_oref(grid,spawn_ore[ore].big_patches,ore,surface,spawn_ore[ore].size)
Please put spaces between function parameters.
`grid, spawn_ore[ore]...`

2021-06-07 21:26 UTC, closed without merging