First join gui minor tweaks
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #203
Opened 2021-10-13 18:10 UTC by TheBigZet

### Brief description of the changes:

- Deleted 2 lines printed to a player when using auto join
- Changed the dotted lines to normal ones
- Added game clock that updates with gui update

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2021-10-14 11:49 UTC, TheBigZet commented
Sorry for so many little commits :sweat_smile:

2021-10-17 09:49 UTC, Atom735 submitted a review, later dismissed

2021-10-17 10:31 UTC, developer-8 commented
Should the message "was automatically assigned to team" be printed if the number of people in the team is not equal? After all, the player knows which team he will be assigned.

2021-10-17 18:31 UTC, TheBigZet commented
Hmm players asked for indication when someone used the button, not when someone was sent on random. 
And it's still automatic even if you know the result :)

2021-11-03 10:16 UTC, TheBigZet commented
@1pulse @AwesomePatrol @mysticamber 
![1](https://user-images.githubusercontent.com/92057893/140042759-44138828-2050-4c40-81dc-d2c3d39398cf.jpg)
![2](https://user-images.githubusercontent.com/92057893/140042761-9363f66d-7c3e-48bc-8e3d-3b90e0be1a05.jpg)
![3](https://user-images.githubusercontent.com/92057893/140042763-06f9fa0c-0449-4e69-9aa6-275bbc4c3ecb.jpg)

2021-11-03 16:55 UTC, mysticamber commented on maps/biter_battles_v2/gui.lua
> +	local minutes = game.ticks_played % 216000
Rather than override minutes with line 50, just combine it. At the very least, combine all the math stuff. 
The result of `game.ticks_played % 216000` is still in ticks

2021-11-03 16:55 UTC, mysticamber requested changes
Please format the code + remove commented out lines. 
Also, description should include all changes (e.g. clock). When does the clock update?

2021-11-03 16:56 UTC, mysticamber commented on maps/biter_battles_v2/gui.lua
> +		if auto_join then message = table.concat({player.name, " was automatically assigned to team ", c, "! "}) end
Check with patrol. This might break his bot as it changes join message

2021-11-03 17:07 UTC, TheBigZet commented on maps/biter_battles_v2/gui.lua
> +		if auto_join then message = table.concat({player.name, " was automatically assigned to team ", c, "! "}) end
Right, didn't think of that. But I also didn't want to just add another message after the default one
`Player has joined team north
Player was automatically assigned to team north`
Doesn't look great, and it can  get spammy

2021-11-03 18:10 UTC, AwesomePatrol commented on maps/biter_battles_v2/gui.lua
> +		if auto_join then message = table.concat({player.name, " was automatically assigned to team ", c, "! "}) end
As both versions of the message are created here anyways, you can just post message to discord before this `if` statement.

2021-11-03 18:15 UTC, AwesomePatrol commented on maps/biter_battles_v2/gui.lua
> +		local auto_join = true
If you don't modify this variable (or plan to), then using constants (`true` in this case) would be better.

2021-11-03 19:44 UTC, TheBigZet commented on maps/biter_battles_v2/gui.lua
> +		if auto_join then message = table.concat({player.name, " was automatically assigned to team ", c, "! "}) end
The chat log won't differentiate between manual and auto join then, right?

2021-11-03 20:05 UTC, AwesomePatrol commented on maps/biter_battles_v2/gui.lua
> +		if auto_join then message = table.concat({player.name, " was automatically assigned to team ", c, "! "}) end
Exactly. Would you prefer this information to be preserved on Discord? If yes, then I will need to update my parser first.

2021-11-03 20:16 UTC, TheBigZet commented on maps/biter_battles_v2/gui.lua
> +		if auto_join then message = table.concat({player.name, " was automatically assigned to team ", c, "! "}) end
Nah, I don't care that much

2021-11-14 11:56 UTC, AwesomePatrol approved these changes

2021-11-21 00:38 UTC, mysticamber approved these changes

2021-11-21 00:38 UTC, merged