Ban improvements
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #208
Opened 2021-10-30 22:37 UTC by TheBigZet

### Brief description of the changes:
Added two commands:

- /kill <name> - for faster killing
- /punish <name> <reason> - for killing and banning, so that the offender drops the eq

### Tested Changes:
- [X] Needs testing with people.

2021-11-01 01:30 UTC, bits-orio commented on comfy_panel/admin.lua
> +    local victim = cmd.parameter
I wouldn't call this variable `victim`. Rather just call it `suspect` :)

2021-11-01 21:12 UTC, TheBigZet commented
Offender is now switched to his team before banning, so that the team can get their resources back in case of stealing etc.

2021-11-03 17:00 UTC, mysticamber requested changes

2021-11-07 05:48 UTC, mysticamber commented on comfy_panel/admin.lua
> +commands.add_command("kill", "Kill a player", function(cmd)
I'm hella picky, sorry. 

The second arg (Kill a player) is an explanation of the command. It's a bit self-explanatory, but I think it'd be good to include usage, Something like "Kill a player - /kill <player name>"

2021-11-07 05:49 UTC, mysticamber commented on comfy_panel/admin.lua
> +	if not killer.admin then
Personally, I'd use If...elseif... else. That way you don't have to do 2 "returns" + it's clear that both the clauses have to be met.

2021-11-07 06:11 UTC, mysticamber commented on comfy_panel/admin.lua
> +	if string.len(message) < 5 then
I think it's better if you put this higher, next to where message is declared(762). That way the offender code is next line 772.

2021-11-07 06:12 UTC, mysticamber commented on comfy_panel/admin.lua
> +	message = message .. " Appeal on discord. Link on biterbattles.org", {r = 1, g = 0.5, b = 0.1}
What colour is this? Maybe better to use the presets using the colour library. The less hardcoded the better.

2021-11-07 09:57 UTC, TheBigZet commented on comfy_panel/admin.lua
> +	message = message .. " Appeal on discord. Link on biterbattles.org", {r = 1, g = 0.5, b = 0.1}
I think I've just copied it from some other command definition but ok :D

2021-11-07 10:06 UTC, TheBigZet commented on comfy_panel/admin.lua
> +	if not killer.admin then
Is that what you mean?
`if killer.admin and game.players[victim] then`
`	victim = game.get_player(victim)`
`	kill(victim, killer)`
`elseif not killer.admin then`
`	killer.print("Only admins have licence for killing!")`
`elseif not game.players[victim] then`
`	killer.print("Invalid name")`
`end`

2021-11-09 06:26 UTC, mysticamber requested changes

2021-11-09 06:26 UTC, mysticamber commented on comfy_panel/admin.lua
> +	if not killer.admin then
use 3 back ticks to group the code comment together. Preserves format too
```
Like
    this
```

Back to the code.. 
Yes, but opposite, so you don't have to do the check twice. 

You just need to 
```
if killer.admin 
elseif not player or not player.valid
else 
end
```

I'd probably also just do

```
victim = game.get_player(victim)
```
then check `if not player or not player.valid`

Checking that player is valid, will limit this command to in game admins. If you think that Hedwig should eventually use it, see the existing trust command for how it was implemented.

2021-11-11 12:36 UTC, TheBigZet commented on comfy_panel/admin.lua
> +	if not killer.admin then
I'm not sure if that's what you had in mind, but I've changed it around

2021-11-14 09:37 UTC, AwesomePatrol requested changes
Otherwise lgtm

2021-11-14 09:37 UTC, AwesomePatrol commented on comfy_panel/admin.lua
> +		punisher.print("This is admin only command", Coloar.warning)
```suggestion
		punisher.print("This is admin only command", Color.warning)
```

2021-11-14 09:40 UTC, AwesomePatrol commented on comfy_panel/admin.lua
> +	if not killer.admin then
IMO this structure of `if` statements is much easier to read (you don't need to keep in mind what's the opposite of the last conditional and it avoids nesting). However, please don't change it back. This is also ok and if Amber likes it then it's for the better.

2021-11-14 10:51 UTC, TheBigZet commented on comfy_panel/admin.lua
> +		punisher.print("This is admin only command", Coloar.warning)
lol my bad

2021-11-14 11:02 UTC, AwesomePatrol approved these changes

2021-11-21 00:40 UTC, mysticamber approved these changes

2021-11-21 00:40 UTC, merged