Improved readme
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #209
Opened 2021-11-06 19:34 UTC by Tomab

### Brief description of the changes:
Make some superficial and minor changes to improve the readme.

Add in small graphics indicating when the last commit occurred and current fork count.  Removed the malfunctioning discord integration graphic.  Additionally include the scenario description from the "?" icon in-game.

Primarily, I am just learning how to contribute and learn the Biter Battle's development workflow to contribute in a more meaningful way going forward.

### Tested Changes:
- [X] I've tested the changes locally, **they have no effect on gameplay**.
- [ ] I've not tested the changes.

2021-11-07 05:24 UTC, mysticamber commented on readme.md
> +- https://github.com/mysticamber/bitercord is used for discord integration.
Pls remove line 24. Bitercord is a private project.

2021-11-07 05:34 UTC, mysticamber requested changes
Since you're already updating readme, pls remove line 24 for me, thanks! 

I suggest removing the evo/threat section and expanding on it in another PR in the readme, or elsewhere (not sure where. Maybe start a discussion at discord?)

The summary (Factorio Biter Battles section) doesn't mention Evo and Threat. 

P.S. Yes workflow is right - make code change, test, submit PR for review.

2021-11-07 05:34 UTC, mysticamber commented on readme.md
> +### EVO
There's no mention of evo or threat anywhere else on this page. 
This may be better held elsewhere, or the readme could be expanded to explain BB in more detail.

2021-11-07 19:30 UTC, Tomab commented on readme.md
> +### EVO
The summary, Evo and Threat sections were taken almost verbatim from the file at local/en/local.cfg (the "?" button in-game).  It would be trivial to add them back in at a later time if we decided to do so.  Bad link regarding Discord integration also removed.

2021-11-08 22:31 UTC, mysticamber requested changes

2021-11-08 22:31 UTC, mysticamber commented on readme.md
> +The biters have noticed that you are secretly hoarding fish in the rocket silo.  Your objective is to defend your silo, while defeating the other team.  Feed your opponent's biters with science packs
Sorry just noticed the last sentence. I guess that's where evo and threat comes in. Can you please remove the last sentence? Thx

2021-11-10 20:51 UTC, Tomab commented on readme.md
> +The biters have noticed that you are secretly hoarding fish in the rocket silo.  Your objective is to defend your silo, while defeating the other team.  Feed your opponent's biters with science packs
Removed last sentence from summary.

2021-11-10 22:51 UTC, mysticamber approved these changes

2021-11-10 22:52 UTC, merged