Change text warning to accurately reflect mechanics
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #210
Opened 2021-11-06 19:45 UTC by Tomab

### Brief description of the changes:
When the word trust is mentioned, the server indicates to the user that they should ask a trusted player or admin to trust them.  Trusted players however no longer have the ability to trust other players.  I'm assuming this is an admin-only capability.  As such I've modified the warning text to reflect this.

Primarily, I am just learning how to contribute and learn the Biter Battle's development workflow to contribute in a more meaningful way going forward.  Am I doing it right?

### Tested Changes:
- [X] I've tested the changes locally **They have no effect on gameplay**.
- [ ] I've not tested the changes.

2021-11-07 05:38 UTC, mysticamber requested changes

2021-11-07 05:38 UTC, mysticamber commented on chatbot.lua
> +        "If you're not trusted - ask an admin to trust you."
Can you add a brief note on how to find out who's admin? It should be in player list or by typing /admins

2021-11-07 19:39 UTC, Tomab commented on chatbot.lua
> +        "If you're not trusted - ask an admin to trust you."
I was not aware of the /admins command, so telling players about it will prove to be helpful.  Also added a bit about having been around for awhile before asking.  "Awhile" is intentionally vague here, but better than instructing new player to just ask to be trusted "right away".

2021-11-08 22:28 UTC, mysticamber approved these changes

2021-11-08 22:29 UTC, merged