Added special_games system
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #211
Opened 2021-11-08 20:55 UTC by TheBigZet

### Brief description of the changes:
Added admin gui panel for creating special games!
To add config for new special game:

- Add the config to valid_special_games table
- Add button logic in on_gui_click
- Add your generate() function

Added config for two games:

- Turtle - Simple moat with given width, are it's guarding and entrance width. Does NOT check if the silo will get destroyed :)
- Infinity chest - Spawns chest(s) with given filters for both teams

Known issues:

- For some reason checkbox for multiple chests doesn't work for spectators

### Tested Changes:
- [X] I've tested the changes locally.
- [ ] I've not tested the changes.

2021-11-08 22:47 UTC, mysticamber requested changes

2021-11-08 22:47 UTC, mysticamber commented on comfy_panel/special_games.lua
> +	local k = 1
What's k for?

2021-11-08 22:47 UTC, mysticamber commented on comfy_panel/special_games.lua
> +	local position_0 = {x = 0, y = -42}
Might want to test out how the `border_river_width` config affects this

2021-11-08 22:47 UTC, mysticamber commented on comfy_panel/special_games.lua
> +			game.print(i)
Are you sure you want this game.print line?

2021-11-08 22:47 UTC, mysticamber commented on comfy_panel/special_games.lua
> +
I'm picky sorry.. format please

2021-11-09 04:35 UTC, TheBigZet commented on comfy_panel/special_games.lua
> +	local k = 1
I hoped you won't spot it :P

2021-11-09 04:55 UTC, TheBigZet commented on comfy_panel/special_games.lua
> +	local position_0 = {x = 0, y = -42}
It shouldn't as it draws the moat from the middle of the river. The size_y just represents river width + plot y, instead of real dimensions of the plot.
Size_x is also with +-1 accuracy

2021-11-09 04:55 UTC, TheBigZet commented on comfy_panel/special_games.lua
> +			game.print(i)
touché

2021-11-09 04:57 UTC, TheBigZet commented on comfy_panel/special_games.lua
> +
Hmm I wanted to show the relativeness of elements, thus the formatting. How would you do it differently?

2021-11-09 06:13 UTC, bits-orio commented on comfy_panel/special_games.lua
> +			table.insert(water_positions, {name = "water", position = {x = i - (size_x / 2), y = -size_y - a}}) -- south
If you use `deepwater` in place of `water`, your moat color would nicely blend into the river.

2021-11-09 06:17 UTC, mysticamber requested changes

2021-11-09 06:17 UTC, mysticamber commented on comfy_panel/special_games.lua
> +
Why you making me work :D lols just kidding.

I think my confusion was that your example didn't map to your implementation. E.g. there's no field named "label" or that this is not entirely lua `textfield{name = "moat_width", type = "textfield"}`. To me it looked like a listing of descriptions, and so I thought that they should've been aligned. But I read it closer  and only just realized that the indentations were deliberate. So I change my comment to:

I'd separate the explanation of the frame/label elements from the elements required to declare the special mode. Reason being that most people that would edit for the special mode, won't care about the code for the frame/panel. They'll just care about the special game specific code. Also cause, frame is passed in as a parameter and label is hard coded. In theory, no one should touch them. 

For the special mode elements, I'd do something like. 

```
<mode name> = {
		name = "<display name of the mode>",
		config = {
			[1] = {name = "<label name>", type = "label", caption = "<hover help text>"},
			[2] = {name = '<text field name>', type = "textfield", text = "<Text content>", numeric = true, width = <40>}
		},
		button = {name = "<button name>", type = "button", caption = "<hover help text>"}
	},
```

Then notes about config/button, etc.

2021-11-09 06:39 UTC, TheBigZet commented on comfy_panel/special_games.lua
> +	local position_0 = {x = 0, y = -42}
Crap you're right

2021-11-09 06:55 UTC, bits-orio commented on comfy_panel/special_games.lua
> +	local surface = game.surfaces[global.bb_surface_name]
First thing before making any moat generation, you need to make sure you chart the work surface, else you will see artifacts in moat sometimes randomly.:
```suggestion
	local surface = game.surfaces[global.bb_surface_name]
	game.forces["spectator"].chart(surface, {{-size_x/2-moat_width, -size_y-moat_width}, {size_x/2+moat_width, size_y+moat_width}})
```

2021-11-09 06:55 UTC, bits-orio commented on comfy_panel/special_games.lua
> +			table.insert(water_positions, {name = "water", position = {x = i - (size_x / 2), y = -size_y - a}}) -- south
If you use deepwater in place of water, your moat color would nicely blend into the river.

```suggestion
			table.insert(water_positions, {name = "deepwater", position = {x = (size_x / 2) + a, y = i}}) -- north
			table.insert(water_positions, {name = "deepwater", position = {x = -(size_x / 2) - a, y = i}})
			table.insert(water_positions, {name = "deepwater", position = {x = (size_x / 2) + a, y = -i}}) -- south
			table.insert(water_positions, {name = "deepwater", position = {x = -(size_x / 2) - a, y = -i}})
		end
	end
	for i = 1, size_x do
		for a = 0, moat_width do
			table.insert(water_positions, {name = "deepwater", position = {x = i - (size_x / 2), y = size_y + a}}) -- north 
			table.insert(water_positions, {name = "deepwater", position = {x = i - (size_x / 2), y = -size_y - a}}) -- south
```

2021-11-09 06:55 UTC, bits-orio commented on comfy_panel/special_games.lua
> +			position_0.x = position_0.x + (i * k)
If the chests are separate, can you please separate them by atleast 5 spaces each? That way, people can tak out items from each of the 4 directions.

2021-11-09 06:55 UTC, bits-orio commented on comfy_panel/special_games.lua
> +local function generate_turtle(moat_width, entrance_width, size_x, size_y)
I tried, and currently `moat_width` feels like a bogus variable on testing. The width is same no matter what value I enter. Can you check?

2021-11-09 09:43 UTC, developer-8 commented on comfy_panel/special_games.lua
> +local function generate_turtle(moat_width, entrance_width, size_x, size_y)
The generated moat width is 1 greater than the entered value.

2021-11-09 09:44 UTC, developer-8 commented
It is possible to remove concrete and make an island

2021-11-09 09:56 UTC, developer-8 commented
The turtle is not symmetrical, its shifted 1 tile to south east and generated width and height always 1 tile less than entered

2021-11-09 10:33 UTC, TheBigZet commented on comfy_panel/special_games.lua
> +			position_0.x = position_0.x + (i * k)
I can make a toggle for that

2021-11-09 10:38 UTC, TheBigZet commented
1) Yeah I think it's beacuse I didn't place dirt before concrete. Will fix that.

2) Do we care that much? ;) It has something to do with the map isn't symmetric relatively to (0,0)

2021-11-09 10:55 UTC, developer-8 commented
2. North turtle 1 tile row less then south

2021-11-09 11:17 UTC, TheBigZet commented
Sigh, I guess I have to use terrain copy from mirror_terrain.lua

2021-11-09 12:11 UTC, TheBigZet commented on comfy_panel/special_games.lua
> +local function generate_turtle(moat_width, entrance_width, size_x, size_y)
Strange, I thought I fixed that... I'll have a look later

2021-11-09 17:48 UTC, TheBigZet commented on comfy_panel/special_games.lua
> +	local surface = game.surfaces[global.bb_surface_name]
The only artifacts I've spotted were remnants, and I didn't think we would care about them :D

2021-11-09 18:03 UTC, TheBigZet commented on comfy_panel/special_games.lua
> +local function generate_turtle(moat_width, entrance_width, size_x, size_y)
My bad, I thought that the left one was 1 tile wide :) However apart from it being too wide, moat_wide works fine for me bits-orio
![obraz](https://user-images.githubusercontent.com/92057893/140979204-b6cdedf1-2b74-4315-85ad-cc03aad2234d.png)

2021-11-09 19:20 UTC, TheBigZet commented on comfy_panel/special_games.lua
> +	local position_0 = {x = 0, y = -42}
In config it says that river width tops at 100 files, in reality it tops at 64, so that's not a problem

2021-11-10 05:08 UTC, bits-orio commented on comfy_panel/special_games.lua
> +	local surface = game.surfaces[global.bb_surface_name]
Even so, its nice to have discovery of the area that includes moat.

2021-11-12 02:45 UTC, bits-orio commented on comfy_panel/special_games.lua
> +local function generate_turtle(moat_width, entrance_width, size_x, size_y)
Actually, maybe I tested it wrong, it works.

2021-11-12 02:47 UTC, bits-orio commented
Its sometimes possible for the entrance to be lying on a water patch. Which makes it 100% unreachable turtle moat.

![Screenshot_20211111_184617](https://user-images.githubusercontent.com/90995942/141400342-1a6c9453-f22f-41b5-8253-eec6225259f9.png)

2021-11-12 02:50 UTC, bits-orio commented
I again request this somewhere: 
```
game.forces["spectator"].chart(surface, {{-size_x/2-moat_width, -size_y-moat_width}, {size_x/2+moat_width, size_y+moat_width}})
```

its a nice addition to have, to show players who are about to join, what they are about to get into.

2021-11-12 02:52 UTC, bits-orio commented
Can you make `multi` as default, and set `5` as default for `gap size`?

2021-11-12 09:06 UTC, TheBigZet commented
> Its sometimes possible for the entrance to be lying on a water patch. Which makes it 100% unreachable turtle moat.
> 
> ![Screenshot_20211111_184617](https://user-images.githubusercontent.com/90995942/141400342-1a6c9453-f22f-41b5-8253-eec6225259f9.png)

Yeah I know, but the only solution would be to make technically endless bridge from silo to biters nests

2021-11-12 09:08 UTC, TheBigZet commented
> I again request this somewhere:
> 
> ```
> game.forces["spectator"].chart(surface, {{-size_x/2-moat_width, -size_y-moat_width}, {size_x/2+moat_width, size_y+moat_width}})
> ```
> 
> its a nice addition to have, to show players who are about to join, what they are about to get into.

Idk, default game is un-charted as well...
I can always make a toggle :D

2021-11-12 16:36 UTC, bits-orio commented
> > I again request this somewhere:
> > ```
> > game.forces["spectator"].chart(surface, {{-size_x/2-moat_width, -size_y-moat_width}, {size_x/2+moat_width, size_y+moat_width}})
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > its a nice addition to have, to show players who are about to join, what they are about to get into.
> 
> Idk, default game is un-charted as well... I can always make a toggle :D

Yeah a toggle would be nice.

2021-11-13 11:17 UTC, TheBigZet commented
I think that's all I wanted to add. The biggest limitation now is that config is only one line, and I don't see a simple solution to that.
The chart button allows for checking if the bridge will end up in a lake or not, as I think that making bridge go from silo to biters area is a good idea.
That's all if I'm concerned

2021-11-26 14:50 UTC, TheBigZet commented
![obraz](https://user-images.githubusercontent.com/92057893/143597787-95520de6-18ff-4ab2-8f4f-93f5e0f86365.png)

2021-12-06 01:46 UTC, merged