Removed trust check on clear-corpses command
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #227
Opened 2021-12-06 11:51 UTC by Ragnarok000000

### Brief description of the changes:
Accepted in discord, the change is to allow non trusted players to do clear-corpses command (now everyone can do it), tested it locally.

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2021-12-07 19:08 UTC, AwesomePatrol reviewed
Vote: https://discord.com/channels/823696400797138974/823771211421974579/853063186257281035

I would prefer `radius` to be either lowered to `300` for all or just non-trusted. It's fairly easy to lag the server as `find_entities_filtered` are usually quite expensive.

2021-12-07 19:14 UTC, Ragnarok000000 commented
Please do not merge, we need an "anti" abuse system (like only once every 4min...?)

2021-12-09 18:34 UTC, AwesomePatrol commented on maps/biter_battles_v2/main.lua
> +        if not trusted[player.name] and param > 100 then
```suggestion
        if not trusted[player.name] and not player.admin and param > 100 then
```

2021-12-09 18:34 UTC, AwesomePatrol commented on maps/biter_battles_v2/main.lua
> +            player.print('[ERROR] Value is too big. Max radius is 100', Color.fail)
please keep indentation (and use `p` instead of `player.print`) to be consistent with the rest of the function

2021-12-09 19:02 UTC, Ragnarok000000 commented on maps/biter_battles_v2/main.lua
> +        if not trusted[player.name] and param > 100 then
Suggestion took into account (didn't bother merging the if at start as it was like that before, but I agree on that idea to merge the if)

2021-12-09 19:02 UTC, Ragnarok000000 commented on maps/biter_battles_v2/main.lua
> +            player.print('[ERROR] Value is too big. Max radius is 100', Color.fail)
Indentation added, for p instead of player.print, it was p before but the rest of code is player.print... Do you still wanna keep the p?

2021-12-09 19:04 UTC, Ragnarok000000 commented
I've finished the changes. So on my side it's ready (just waiting for patrol answer on the conversation, if we do p with player.print or we do only player.print)

2021-12-09 19:23 UTC, Ragnarok000000 commented on maps/biter_battles_v2/main.lua
> +				player.print('[ERROR] Value is too big. Max radius is 100', Color.fail)
Yeah I merged the suggestion from before, but it didn't remove the if not player.admin alone. Basically 2 same if. cleared it to have the if in the same line. Should be better now..? If OK, resolve conversation.

The goal of this if, is if you are NOT an admin, if you are NOT trusted and if you chose a radius > 100, message than return because you are not allowed to clear corpse with radius > 100.

Otherwise, you're fine (you're either an admin or trusted so you can do 500 max, or you are not an admin/not trusted but you did radius <=100 so it's fine)

2021-12-12 12:09 UTC, AwesomePatrol commented on maps/biter_battles_v2/main.lua
> +        local p = player.print
Is this variable ever used?

2021-12-12 12:11 UTC, AwesomePatrol commented on maps/biter_battles_v2/main.lua
> +        if not trusted[player.name] and not player.admin and param > 100 and not player.admin then
```suggestion
        if not trusted[player.name] and not player.admin and param > 100 then
```

2021-12-12 12:13 UTC, AwesomePatrol requested changes

2021-12-12 12:13 UTC, AwesomePatrol commented on maps/biter_battles_v2/main.lua
> +            end
One `end` too many

2021-12-12 12:39 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/main.lua
> +        local p = player.print
No, deleted.

2021-12-12 12:41 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/main.lua
> +            end
Oh correct, probably the side effect of the suggestion to merge the 2 if, didn't remove the end. Fixed

2021-12-12 12:45 UTC, Ragnarok77-factorio commented
I don't get why it says "changes requested" whereas the conversations/suggestions were taken into account/resolved 🤔

2021-12-12 12:46 UTC, merged