Fix messing research queue exploit in jail
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #241
Opened 2021-12-19 16:54 UTC by Ragnarok77-factorio

Fix messing research queue exploit in jail

### Brief description of the changes:
If a player has its research window opened, and if he's jailed, he can still mess research even without permission as the tab is opened. To prevent them, kill them so they loose the window.

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2021-12-20 11:41 UTC, TheBigZet commented
When in doubt, kill the offender! 😄

2022-05-14 17:43 UTC, TheBigZet commented
Actually there's non-lethal way to do this
`player.opened = none`
Killing the player would mean the corpse is left forever in jail

2022-05-14 19:25 UTC, TheBigZet requested changes

2022-05-14 19:25 UTC, TheBigZet commented on utils/datastore/jail_data.lua
> +	game.players[griefer].character.die()
Actually there's non-lethal way to do this @Ragnarok77-factorio
player.opened = none
Killing the player would mean the corpse is left forever in jail

2022-05-14 19:58 UTC, Ragnarok77-factorio commented on utils/datastore/jail_data.lua
> +	game.players[griefer].character.die()
Updated it to your request, tested it with 2 accounts (one jailing, the other one having research opened) and... it worked, research closed once jailed. I didn't know this method existed.

2022-05-14 20:25 UTC, Ragnarok77-factorio commented
Also added changelogs, seems like it has not been started for a long time

2022-05-14 20:41 UTC, TheBigZet commented on utils/datastore/jail_data.lua
> +    game.players[griefer].character.opened = none
Test it, I believe `opened` belongs to `player`, not `character`

2022-05-14 20:59 UTC, Ragnarok77-factorio commented on utils/datastore/jail_data.lua
> +    game.players[griefer].character.opened = none
Seems to work for both :  https://lua-api.factorio.com/latest/LuaControl.html#LuaControl.opened
![image](https://user-images.githubusercontent.com/95619848/168447830-91825d8c-e208-4b3d-8ef2-700e301e1fbf.png)

I tested with or without character, both OK
Anyways, shorter code I guess without character , so updated it @TheBigZet

2022-05-15 09:31 UTC, TheBigZet approved these changes
Technically not the correct syntax, but it works

2022-05-15 14:36 UTC, TheBigZet requested changes

2022-05-15 14:36 UTC, TheBigZet commented on utils/datastore/jail_data.lua
> +    game.players[griefer].opened = none
Sorry, please change it to 
`game.players[griefer].opened = defines.gui_type.none`
so it's syntax correct

2022-05-15 14:36 UTC, TheBigZet commented on utils/datastore/jail_data.lua
> +    game.players[griefer].opened = none
Sorry for nitpicking, please change it to 
`game.players[griefer].opened = defines.gui_type.none`
so it's syntax correct

2022-05-15 15:08 UTC, Ragnarok77-factorio commented on utils/datastore/jail_data.lua
> +    game.players[griefer].opened = none
No worries it's fine, and it's done  @TheBigZet

2022-05-15 15:33 UTC, TheBigZet approved these changes

2022-05-15 16:11 UTC, merged