Anti afk system
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #248
Opened 2021-12-26 12:07 UTC by Ragnarok77-factorio

### Brief description of the changes:
Any player who is afk for more than 5 minutes will be sent back to spectator island, but he will be able to come back to his position with his gear too (player not brutally kicked from the server as we want to keep even afk players in the game).

Dev comments : 
Use player_data to store the information about where the player was, so he can easily come back to his position, using afk_time as it's the best solution for now to find who is afk. Reset table at restart too. The player_data was from jail system

Vote link :  https://discord.com/channels/823696400797138974/823771211421974579/924374019220844654

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2021-12-28 21:51 UTC, AwesomePatrol requested changes

2021-12-28 21:51 UTC, AwesomePatrol commented on maps/biter_battles_v2/gui.lua
> +local player_data = {}
This is desync waiting to happen

2021-12-28 22:33 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/gui.lua
> +local player_data = {}
Ugh, kinda confused because first I really don't know desync well at all, second is that I've basically copied the code from jail_data and adapted it a bit, but it's the same way, it has a local player_data, call the get_player_data and so on... so don't really know why and if it's really the case, what to do..? 🤔  @AwesomePatrol

2021-12-28 22:40 UTC, AwesomePatrol commented on maps/biter_battles_v2/gui.lua
> +local player_data = {}
AFAIK only `global` data is preserved in saves, so when someone joins the game they won't receive it. When somebody rejoins a team, one client will put character in default position and the other in the saved one. Please test in multiplayer in heavy mode to confirm/debunk

2021-12-29 12:34 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/gui.lua
> +local player_data = {}
Confirmed, it was desynching (which seemed logical).

I updated it to global (inspired from special events to know ho to exactly), and it should  be fine now, tested it, couldn't get desync anymore, also tried heavy debug, nothing too.

2021-12-29 12:56 UTC, AwesomePatrol commented on maps/biter_battles_v2/game_over.lua
> +		Gui.reset_tables_gui()
Inconsistent indentation

2021-12-29 12:56 UTC, AwesomePatrol commented on maps/biter_battles_v2/main.lua
> +	antiAfkTimeBeforeEnabled = 60 * 60 * 5 -- in tick : 5 minutes
please consider making it file local (define at the file start)

2021-12-29 12:56 UTC, AwesomePatrol commented on maps/biter_battles_v2/main.lua
> +	if player.afk_time > antiAfkTimeBeforeEnabled then
It would be great to get a warning first. Consider having to thresholds configurable

2021-12-29 12:56 UTC, AwesomePatrol commented on maps/biter_battles_v2/gui.lua
> +function spectate(player, forced_join, positionStored)
Please stick to snake_case and adverb before noun

2021-12-29 12:56 UTC, AwesomePatrol commented on maps/biter_battles_v2/gui.lua
> +            get_player_data(player, true)
Inconsistent indentation

2021-12-29 13:13 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/game_over.lua
> +		Gui.reset_tables_gui()
Fixed it

2021-12-29 13:14 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/main.lua
> +	antiAfkTimeBeforeEnabled = 60 * 60 * 5 -- in tick : 5 minutes
I think I got it right ..? I added it at file start instead

2021-12-29 13:16 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/main.lua
> +	if player.afk_time > antiAfkTimeBeforeEnabled then
Done, I've added a warning message, at 3min40 (was worried 1 exact minute could lead to weird issues since it's called every minute, so did 1min20s so 3min40 afk for a warning), threshold at start, like the other afk variable

2021-12-29 13:16 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/gui.lua
> +function spectate(player, forced_join, positionStored)
Yes, better to have same kind of name everywhere, done

2021-12-29 13:16 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/gui.lua
> +            get_player_data(player, true)
Fixed too.

2021-12-29 13:20 UTC, AwesomePatrol approved these changes

2021-12-29 13:20 UTC, AwesomePatrol commented on maps/biter_battles_v2/init.lua
> +	global.player_data_afk = {}
Most likely not needed as you have already declared it in `gui.lua`

2021-12-29 13:25 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/init.lua
> +	global.player_data_afk = {}
To be honest I copied the special_event, and he did like it that too (at beginning of file = {} and at init.lua he also added = {} , which seems not needed I agree but...

Want me to remove it for init.lua ? (if yes I will update it and will test the PR again to be sure it doesn't introduce any desync removing this line)

2021-12-29 13:40 UTC, AwesomePatrol commented on maps/biter_battles_v2/init.lua
> +	global.player_data_afk = {}
Don't bother. Keep it as is

2022-06-25 15:17 UTC, merged