New feature : show amount of votes of diff in gui
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #300
Opened 2022-07-31 07:34 UTC by Ragnarok77-factorio

### Brief description of the changes:
Shows amount of votes of difficulties in GUI : 

Vote discord link : https://discord.com/channels/823696400797138974/823771211421974579/988455083136131132

Result in game : 
![image](https://user-images.githubusercontent.com/95619848/182015213-1dd14817-f0ec-483d-94e8-98080d68c942.png)

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2022-07-31 12:12 UTC, TheBigZet requested changes

2022-07-31 12:12 UTC, TheBigZet commented on maps/biter_battles_v2/difficulty_vote.lua
> +		local b = frame.add({type = "button", name = tostring(key), caption = difficulties[key].name .. " (" .. difficulties[key].str .. ")" .. " : " .. amount_voters_of_diff .. " " .. voter_text})
This is highly inefficient, for 40 connected players we get 7*40=280 passes. Also, string concatenation `..` is slow
```suggestion
	local vote_amounts = {0,0,0,0,0,0,0}
	for k, v in pairs(global.difficulty_player_votes) do
		vote_amounts[v] = vote_amounts[v] + 1
	end
	
	for key, difficulty in pairs(difficulties) do
		local caption = table.concat({difficulty.name, " (", difficulty.str, ")", " : ", vote_amounts[key]})
		local b = frame.add{type = "button", name = tostring(key), caption = caption}
```

This way we get 40+7=47 passes (if everyone voted), and we use faster `table.concat`
Sidenote: for `key, value in pairs()` allows for direct value addressing, so we can use better looking `difficulty.name` instead of `difficulties[key].name`
Personally, I'd get rid of the "votes" part and leave just the number, but that's up to you.

I haven't tested it, but I'm pretty sure it should work

2022-07-31 12:20 UTC, TheBigZet requested changes

2022-07-31 12:20 UTC, TheBigZet commented on maps/biter_battles_v2/difficulty_vote.lua
> +		local b = frame.add({type = "button", name = tostring(key), caption = difficulties[key].name .. " (" .. difficulties[key].str .. ")" .. " : " .. amount_voters_of_diff .. " " .. voter_text})
This is highly inefficient, for 40 connected players we get 7*40=280 passes. Also, string concatenation `..` is slow
```suggestion
	local vote_amounts = {0,0,0,0,0,0,0}
	for k, v in pairs(global.difficulty_player_votes) do
		vote_amounts[v] = vote_amounts[v] + 1
	end
	
	for key, difficulty in pairs(difficulties) do
		local caption = table.concat({difficulty.name, " (", difficulty.str, ")", " : ", vote_amounts[key]})
		local b = frame.add{type = "button", name = tostring(key), caption = caption}
```

This way we get 40+7=47 passes (if everyone voted), and we use faster `table.concat`
Sidenote: for `key, value in pairs()` allows for direct value addressing, so we can use better looking `difficulty.name` instead of `difficulties[key].name`
Personally, I'd get rid of the "votes" part and leave just the number, but that's up to you.

I haven't tested it, but I'm pretty sure it should work

I can't mark it, but it's supposed to replace the for loop in L47 too

2022-07-31 15:10 UTC, TheBigZet commented on maps/biter_battles_v2/difficulty_vote.lua
> +		local b = frame.add({type = "button", name = tostring(key), caption = difficulties[key].name .. " (" .. difficulties[key].str .. ")" .. " : " .. amount_voters_of_diff .. " " .. voter_text})
Also, looping through connected_players eould return incorrect values in case plater voted and left the game

2022-08-01 15:44 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/difficulty_vote.lua
> +		local b = frame.add({type = "button", name = tostring(key), caption = difficulties[key].name .. " (" .. difficulties[key].str .. ")" .. " : " .. amount_voters_of_diff .. " " .. voter_text})
@TheBigZet 
Sure for the optimization, I don't believe it would have a big impact as it is not much (and just happens when a player  shows diff gui) and there is no biter at start (only map generation that is eating quite a bit of perf though), but every small bit is good to take nonetheless so agreed for change.

Okay I updated it following your suggestion (there were few issues : end missing, local variable had to  be moved outside of for, the vote was always showing 7 per player, added condition to have 1 vote per player instead). I'm not sure for your if remark, is it fine now on latest code ?

I don't think it would have been an issue as there is an event on player leaving that sets up to nil this variable : global.difficulty_player_votes[player.name] = nil so his vote shouldnt count.

2022-08-05 12:54 UTC, TheBigZet requested changes
Still too many loops. Just needed to delete L48 as I said ealier

2022-08-05 12:54 UTC, TheBigZet commented on maps/biter_battles_v2/difficulty_vote.lua
>  	for key, _ in pairs(difficulties) do
```suggestion

```

2022-08-05 12:54 UTC, TheBigZet commented on maps/biter_battles_v2/difficulty_vote.lua
> +	end
```suggestion
	for k, v in pairs(global.difficulty_player_votes) do
		vote_amounts[v] = vote_amounts[v] + 1
	end
```

2022-08-05 12:54 UTC, TheBigZet commented on maps/biter_battles_v2/difficulty_vote.lua
>  		b.style.font_color = difficulties[key].color
```suggestion
		b.style.font_color = difficulty.color
```

2022-08-05 20:00 UTC, Ragnarok77-factorio commented
Oh god all the files changed due to branch target being changed (all the develop changes needs now to be removed)

2022-08-05 20:01 UTC, TheBigZet commented
lul, maybe let's just redo it

2022-08-05 20:14 UTC, Ragnarok77-factorio commented
Okay what a mess, maybe it's fine now ? I just have a doubt about this "return Public" change...?  Otherwise seems to be working.

Changing from dev to master (or maybe master to dev too?) is horrible because there are lot of changes on both of the branches.

2022-08-09 15:56 UTC, Ragnarok77-factorio commented
Okay nevermind for public return, it was just a newline after it that was in original code, added it back. So ready again then.

2022-08-16 09:04 UTC, developer-8 commented on maps/biter_battles_v2/difficulty_vote.lua
> +	local vote_amounts = {0,0,0,0,0,0,0}
The number of elements in `vote_amounts` should derive from `difficulties`. I think optimization is not worth keeping one more constant.

2022-08-21 12:21 UTC, outstanding-factorio commented on maps/biter_battles_v2/difficulty_vote.lua
> +	local vote_amounts = {0,0,0,0,0,0,0}
I do not think developers comment is a necessary change. However, I would recommend naming the variable that it is easier to read.

2022-08-21 12:21 UTC, outstanding-factorio commented
Ready to test on test server?

2022-08-21 19:59 UTC, Ragnarok77-factorio commented
> Ready to test on test server?

To be added on test server, I think it needs to be merged first (up to TBZ or another dev with github power), then test server needs to be updated and it's ready to be tested.

2022-08-30 11:35 UTC, developer-8 commented on maps/biter_battles_v2/difficulty_vote.lua
> +	local vote_amounts = {0,0,0,0,0,0,0}
In this case, if the number of difficulties increases, the future programmer needs to remember to change the code in this place as well.

2022-08-30 11:47 UTC, developer-8 commented on maps/biter_battles_v2/difficulty_vote.lua
> +	local vote_amounts = {0,0,0,0,0,0,0}
Can be solved differently
`local vote_amounts = {}`
and when used check for nil
`vote_amounts[v] = (vote_amounts[v] or 0) + 1`

2022-08-30 14:38 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/difficulty_vote.lua
> +	local vote_amounts = {0,0,0,0,0,0,0}
I'm sure we will miss that when we add another diff, so why not make it more robust to that.

2022-08-30 14:51 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/difficulty_vote.lua
> +	local vote_amounts = {0,0,0,0,0,0,0}
Code updated, thanks for the example, would have been a bit of pain otherwise, should be fine now @developer-8

2022-08-30 17:14 UTC, developer-8 commented on maps/biter_battles_v2/difficulty_vote.lua
> +		local caption = table.concat({difficulty.name, " (", difficulty.str, ")", " : ", vote_amounts[key]})
```suggestion
		local caption = table.concat({difficulty.name, " (", difficulty.str, ")", " : ", (vote_amounts[key] or 0)})
```

2022-08-31 17:01 UTC, developer-8 approved these changes

2022-11-22 21:13 UTC, merged