refactor out existing AI functions cleanly into "Strikes" and "Targets"
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #318
Opened 2022-08-30 07:04 UTC by amannm

improve precision, performance of positioning and sampling computation involved in strikes
properly release references to destroyed target entities to allow GC

### Brief description of the changes:
---Fill in---

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2022-09-02 14:00 UTC, TheBigZet reviewed
Consider assigning frequently used functions (math.atan2, sqrt, abs) to local variables

2022-09-03 07:59 UTC, amannm commented
> Consider assigning frequently used functions (math.atan2, sqrt, abs) to local variables

done

2022-09-04 03:12 UTC, amannm commented
<img width="552" alt="image" src="https://user-images.githubusercontent.com/3229134/188295384-097652af-e8b1-42ba-8ef1-ec50b5d1de95.png">
here's the distribution you see using the following test fixture:

```
local boundary_offset = 20
local source = {x = -1024, y = 200}
local target = {x = 0, y = 200}
local samples = 2000
local res = ""
for _ = 1, samples, 1 do
    local strike_position = select_strike_position(source, target, boundary_offset)
    res = res .. string.format("[%s,%s],", math.floor(strike_position.x), math.floor(strike_position.y))
end
print(res)

```
where source was varied with `{x = -1024, y = 200}` ` {x = 0, y = 1024}` ` {x = 1024, y = 200}`

2022-09-06 20:55 UTC, developer-8 commented
This was not tested for sure. Terrain generation very broken. You can move to draft if PR not finished

2022-09-07 01:28 UTC, amannm commented
> This was not tested for sure. Terrain generation very broken. You can move to draft if PR not finished

sorry about that, had tested PR against main/master... develop introduced some new additional `Functions` use and the removal of the import messed that up. fixed now

2022-09-10 17:45 UTC, amannm commented
here is the current strike behavior that this is replacing:
![image](https://user-images.githubusercontent.com/3229134/189495477-e38c099a-bb2e-4356-a3bd-3b59b65603ba.png)
if the target selected is the center of the green circle, the current code is picking a random one of those three angles, then picking a random position on the grey portion to move biters to before attacking the 32 radius green area

2022-12-26 01:11 UTC, Ragnarok77-factorio commented
This PR generates this spam in logs (ignore line number of screenshot) : 
![image](https://user-images.githubusercontent.com/95619848/209487409-327717b6-e8e6-4c0b-9f72-d8bf4ddc37c0.png)

Which is there : 
![image](https://user-images.githubusercontent.com/95619848/209487450-cbf4db82-f993-4a89-ac56-6825ecdde1c7.png)

How to reproduce issue : 
Demote yourself, untrust yourself, place a ghost bp and welcome to this error where it will attempt to track an entity ghost that was basically deleted by code before.

==
I think its' just a missing an "if valid" condition in start_tracking code

2022-12-26 01:11 UTC, Ragnarok77-factorio requested changes

2022-12-26 01:11 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/ai_targets.lua
> +    if target_entity_type[entity.type] and entity.unit_number then
Missing an if valid check at the beginning (cf comment for why it's needed)

2022-12-26 11:43 UTC, Ragnarok77-factorio commented
Since sadly I think he's gone :( I made another PR so I can fix this issue : https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/pull/340
(if he comes back I will cancel the new PR)

2022-12-26 18:48 UTC, TheBigZet commented
@Ragnarok77-factorio

2022-12-26 19:00 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/ai_targets.lua
> +    if target_entity_type[entity.type] and entity.unit_number then
done by TBZ, closed.

2022-12-26 19:00 UTC, Ragnarok77-factorio commented
Thanks TBZ !  closed PR340

2023-01-09 02:01 UTC, amannm commented
oh ok thanks for coming back to this, thanks for the fix, let me know if there's anything else that can be improved

2023-01-12 08:20 UTC, Ragnarok77-factorio approved these changes
Got a hard time to review code exactly line per line and fully understand it every small bit, but I  didn't find anything shocking at least... Feel free if someone else can deeply review it.

It was also tested on multiple games and didn't notice any issue anymore after fix, so ok for me.

2023-05-07 12:10 UTC, TheBigZet approved these changes
No issues reported during a month long testing

2023-05-07 12:25 UTC, merged