Add snow cover to map
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #337
Opened 2022-12-18 05:21 UTC by developer-8

The goal of this PR is to add "snow cover" to the map. To create a winter mood and bring variety to the game. Snow is simulated by lab-white tiles and therefore has some limitations compared to ordinary tiles, for example, snow does not have a transition with ordinary tiles, so special concrete tiles are used as transit tiles.

Features:
- Admins have the ability to enable and disable the snow cover through the config. Changes are applied only to the map of the next game.
- Several snow coverage modes, with different amounts of snow on the map + random mode
- Made better looking trees in areas with snow

![image](https://user-images.githubusercontent.com/88335092/208282231-e5611555-fd71-4370-bf26-c57a5c1b5baa.png)

Of course, snow cover will affect the performance of map generation, but this is a price that must be paid only once when generating a chunk. I did not do tests performance, but it was playable locally.

2022-12-18 10:03 UTC, TheBigZet commented on maps/biter_battles_v2/snow_cover.lua
> +	for _, entity in pairs(surface.find_entities({{left_top_x, left_top_y}, {left_top_x + 32, left_top_y + 32}})) do
Some weird indentation is happening here

2022-12-18 10:04 UTC, TheBigZet commented on maps/biter_battles_v2/snow_cover.lua
> +            if entity.name == "tree-08"
Maybe put the names in a list?

2022-12-18 22:22 UTC, developer-8 commented on maps/biter_battles_v2/snow_cover.lua
> +	for _, entity in pairs(surface.find_entities({{left_top_x, left_top_y}, {left_top_x + 32, left_top_y + 32}})) do
Fixed. When spaces and tabs are mixed, github doesn't show it the way my editor does

2022-12-18 22:23 UTC, developer-8 commented on maps/biter_battles_v2/snow_cover.lua
> +            if entity.name == "tree-08"
Сhanged using list

2022-12-18 22:24 UTC, developer-8 commented
I had to make `is_horizontal_border_river` global again, since now it is also called in another file

2022-12-30 21:48 UTC, Ragnarok77-factorio commented
Tested during captain game, lag was noticed but it was very likely due to massive map reveal that killed ups and not the snow change. 
Neuro found that : 
![image](https://user-images.githubusercontent.com/95619848/210113766-1ef752cb-42c1-428c-b8c5-b293fcf0a8d8.png)

But after discussion, it's just that there is no transition from snow to brick, so not a bug and nothing we can do about it.
I like the toggle option of the PR too.

2023-01-23 22:19 UTC, TheBigZet requested changes
I don't think it should be merged. Some players reported it being quite uncomfortable for eyes

2023-01-26 19:26 UTC, developer-8 commented
I am closing this PR as it is no longer relevant.

2023-01-26 19:26 UTC, closed without merging