Bugfix to avoid spam of error in log when decon
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #339
Opened 2022-12-26 11:22 UTC by Ragnarok77-factorio

### Brief description of the changes:
Sometimes you see the following error in log : bad argument #3 of #3 to __index (string expected, got nil) in the if, this PR should fix it (I couldn't reproduce it...) but from the line of if, only player_index which can be optional seem to be a cause of this issue.

Should fix https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/issues/308
Maybe someone has more info..

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2022-12-28 01:58 UTC, developer-8 commented on maps/biter_battles_v2/main.lua
> +	if not event.player_index == nil then return end
```suggestion
	if not event.player_index then return end
```
sorry, your fix doesn't work

2022-12-28 02:01 UTC, developer-8 commented
I found how to repeat the bug, it is enough to deconstruct the rock with a robot, then all its contents will also be marked for deconstruction, but event will be without the `player_index`

2022-12-28 08:22 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/main.lua
> +	if not event.player_index == nil then return end
Thanks a lot, you are right, oh god... That's a good example of why review are important sometimes :D

2022-12-28 08:24 UTC, Ragnarok77-factorio commented
Oh, very nice ! Good to know, I reproduced it only with coal rocks, not classic rock. And that's why "massive" spam because lot of rocks are marked for decon when it happens.

2022-12-28 21:29 UTC, developer-8 submitted a review, later dismissed
good

2022-12-30 21:46 UTC, Ragnarok77-factorio commented
No issue found during captain game of 30/12/2022, no error appeared during a 15v15

2023-01-23 22:12 UTC, TheBigZet requested changes

2023-01-23 22:12 UTC, TheBigZet commented on maps/biter_battles_v2/main.lua
>  	if (game.players[event.player_index].force == game.forces.north and event.entity.position.y > 0) or (game.players[event.player_index].force == game.forces.south and event.entity.position.y < 0) then
Could we fix this line as well when we're at it? Assign `local player` or even `'local force_name`  at the top

2023-01-26 19:20 UTC, developer-8 reviewed
The fix was so simple and you can add your commit without this PR.

2023-01-26 19:48 UTC, TheBigZet commented
I thought I'll add it here as it's the same function

2023-01-26 19:49 UTC, merged