Introduce map reroll
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #352
Opened 2023-01-19 13:40 UTC by PlayerNoon

### Brief description of the changes:
Implementing feature approved by community.
https://discord.com/channels/823696400797138974/823771211421974579/980397648756490270
Players are able to vote to generate new map only within 30 s from the start (game time / ticks_played).
It require approval from 75% of all voters to pass.
Map is generated or not at 30 s mark from the (game time / ticks_played).
Players are able to generate new map as many times as they want.

### Tested Changes:
- [ ] I've tested the changes locally.
- [ ] I've not tested the changes.

2023-01-20 09:35 UTC, developer-8 commented
Why did you hide the 30 second countdown?
How to counter trolls who will click New map at the last second and the rest of the players simply ignore the vote? or  nothing can be done about it ?

2023-01-20 11:20 UTC, PlayerNoon commented
> Why did you hide the 30 second countdown? How to counter trolls who will click New map at the last second and the rest of the players simply ignore the vote? or nothing can be done about it ?

I tried to have this code simple without unnecessary things. Also it was not mentioned / discussed on discord.
IMO I don't think it is an issue because it is just 30 s.
If it it will be a real problem then we will have to make poll about it on discord. 
But if u really want, tell how to make that timer so i can implement it.

2023-01-20 13:04 UTC, developer-8 commented on maps/biter_battles_v2/difficulty_vote.lua
> +	local result = math.floor( yes / ( yes + no ) )
`result`  is always 1 or 0

2023-01-20 14:30 UTC, developer-8 commented on maps/biter_battles_v2/difficulty_vote.lua
> +	if result > 75 then
```suggestion
	if result >= 75 then
```

2023-01-20 19:01 UTC, developer-8 commented on maps/biter_battles_v2/game_over.lua
> +    global.reroll_voting_status = false
```suggestion
```
it is not necessary

2023-01-20 19:07 UTC, developer-8 commented on maps/biter_battles_v2/game_over.lua
> +function Public.reroll_map()
`Public.reroll_map() ` consists of code from function `Public.server_restart()`, this needs to be done somehow so that the code is not duplicated

2023-01-20 19:13 UTC, developer-8 commented on maps/biter_battles_v2/game_over.lua
> +function Public.reroll_map()
It seems to me that duplication is not necessary in this place, right?

2023-01-20 19:20 UTC, PlayerNoon commented on maps/biter_battles_v2/game_over.lua
> +function Public.reroll_map()
you right.

2023-01-20 19:49 UTC, developer-8 commented on maps/biter_battles_v2/gui.lua
> +		gui_style(b_reroll_yes, {width = 150, height = 38})
can pass `font` and `font_color` into `gui_style`

2023-01-20 19:57 UTC, developer-8 commented on maps/biter_battles_v2/difficulty_vote.lua
> +		if players == 1 then
```suggestion
	for _, vote in pairs(global.reroll_map_voting) do
		if vote == 1 then 
```
`players` confusing name

2023-01-22 23:31 UTC, TheBigZet commented on maps/biter_battles_v2/gui.lua
> +		gui_style(b_reroll_yes, {width = 150, height = 38})
`gui_style` should work with every parameter from LuaStyle, it's just a for loop

2023-01-26 20:05 UTC, developer-8 commented on maps/biter_battles_v2/game_over.lua
> +function Public.reroll_map()
Now that `reroll_map` used in `server_restart`, it can be renamed to something more suitable. At your discretion

2023-01-26 20:46 UTC, PlayerNoon commented on maps/biter_battles_v2/main.lua
> +		if global.reroll_map_voting_status and game.ticks_played >= global.reroll_time_limit then
![image](https://user-images.githubusercontent.com/120744927/214946828-409e9ad5-18bf-4ae1-a39e-90ea6b33434b.png)
 yes. first match it start form 0 tick. from next match it start form tick 11.

2023-01-26 20:48 UTC, PlayerNoon commented on maps/biter_battles_v2/game_over.lua
> +function Public.reroll_map()
i couldn't find any suitable name. you choose any.

2023-01-26 21:11 UTC, developer-8 commented on maps/biter_battles_v2/game_over.lua
> +    game.print("Generated new map")
yes

2023-01-26 21:17 UTC, developer-8 commented on maps/biter_battles_v2/game_over.lua
> +function Public.reroll_map()
how about `generate_new_map`

2023-01-26 21:24 UTC, developer-8 commented on maps/biter_battles_v2/gui.lua
> +function create_reroll_button(player)
```suggestion
local function create_reroll_button(player)
```

2023-01-26 22:14 UTC, developer-8 commented
It may make sense to move the code from `difficulty_vote.lua` to `gui.lua` so that the creation of the buttons and the handling of their clicks happen in the same file.

2023-01-29 17:03 UTC, PlayerNoon commented
done.

2023-01-29 17:40 UTC, developer-8 commented on .vs/ProjectSettings.json
> +{
remove folder .vs from git

2023-01-29 17:43 UTC, developer-8 commented on .vs/ProjectSettings.json
> +{
add it to .gitignore probably easiest

2023-01-29 17:47 UTC, PlayerNoon commented on .vs/ProjectSettings.json
> +{
how

2023-01-29 17:52 UTC, developer-8 commented on .vs/ProjectSettings.json
> +{
to
https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/blob/master/.gitignore
add
.vs/

2023-01-29 17:57 UTC, PlayerNoon commented on .vs/ProjectSettings.json
> +{
is it ok?

2023-01-29 18:04 UTC, developer-8 commented on .vs/ProjectSettings.json
> +{
yes, but .vs/ already commited so need to delete it 
You can do it on github

2023-01-29 18:11 UTC, PlayerNoon commented on .vs/ProjectSettings.json
> +{
ok?

2023-01-29 18:12 UTC, developer-8 commented on .vs/ProjectSettings.json
> +{
ok

2023-01-29 18:24 UTC, developer-8 commented on maps/biter_battles_v2/gui.lua
> +	if event.element.name == "reroll_yes" then
```suggestion
	if name == "reroll_yes" then 
```

2023-01-29 18:24 UTC, developer-8 commented on maps/biter_battles_v2/gui.lua
> +	if event.element.name == "reroll_no" then
```suggestion
	if name == "reroll_no" then 
```

2023-01-29 18:24 UTC, developer-8 commented on maps/biter_battles_v2/main.lua
> +		game.print("Generated new map")
```suggestion
			Game_over.generate_new_map()	
			game.print("Generated new map")
```

2023-01-29 18:36 UTC, developer-8 commented on maps/biter_battles_v2/gui.lua
> +	game.print(result .. "% votes to reroll." .. " Need 75% to reroll map.".. " Time left " .. reroll_time_left .. "s" )
```suggestion
	game.print(result .. "% votes to reroll. Need 75% to reroll map. Time left " .. reroll_time_left .. "s" )
```

2023-01-29 18:46 UTC, developer-8 approved these changes

2023-01-29 22:55 UTC, TheBigZet commented
I'd like having a toggle in config in case the system is abused

2023-06-07 10:42 UTC, TheBigZet requested changes
I'd like to try to do it with `utils/Task.lua`
Set function checking `reroll_voting_status` to be run x seconds after map start. This way we can cut down number of checks per tick.

I haven't used that module yet tho, not sure if it works like that

2023-06-07 10:42 UTC, TheBigZet commented on maps/biter_battles_v2/init.lua
> +	global.reroll_time_limit = 1800
I think it's too short, I get loaded around 800th tick, leaving about 15s to check the map and vote

2023-06-18 08:43 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/init.lua
> +		["map_reroll_admin_disable"] = true,
Very minor but agree too, would prefer enabled too, less confusing

2023-06-30 11:47 UTC, TheBigZet commented
Button creation and removal could also be done just once, as well as ratio calculation.

2023-06-30 16:43 UTC, developer-8 commented
I got a message about [0c7c584b2d632ec0f929034729cfdfb6356b2e83](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/commit/0c7c584b2d632ec0f929034729cfdfb6356b2e83) but I don't see it in the commits list

2023-06-30 16:51 UTC, TheBigZet commented
> I got a message about [0c7c584b2d632ec0f929034729cfdfb6356b2e83](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/commit/0c7c584b2d632ec0f929034729cfdfb6356b2e83) but I don't see it in the commits list

Yeah weird... It shows up in the source branch PlayerNoon:reroll-previev

2023-07-01 09:03 UTC, developer-8 reviewed
1. Map will not reroll if this is first game and `generate_new_map()` was never called before.

2. Map will not reroll if click "Mew map"  after time out but GUI is not hidden yet.

      before Task changes:
      ![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/88335092/15a7b55e-6195-4766-a0eb-e48c6a206ecd)
      after Task map not rerolled:
      ![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/88335092/6e54c087-8975-4cbb-b0a8-2d456eddf954)

2023-07-01 10:32 UTC, Ragnarok77-factorio commented
Waiting for fix of developer comment before testing it again

2023-07-01 10:43 UTC, developer-8 commented
I'm not insist for it to be fixed. It works well enough, no complaints about the code, bugs are minor. There's just room for improvement. I leave it to the discretion of the author

2023-07-09 07:05 UTC, Ragnarok77-factorio approved these changes
Tested it, fine for me now.
But it was a solo test.

I think it would be nice to test it a bit on pub server just to be sure no edge case was forgotten or something.

2023-07-18 15:59 UTC, Ragnarok77-factorio commented
We rerolled it, but it's quite spammy too be honest, and may the timing is a bit too short too, barely any time to vote..? Dunno, just a random opinion, what do you think? 

![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/95619848/6a6682d4-b290-4711-b9bb-5bf269fc7668)

2023-07-23 08:26 UTC, Ragnarok77-factorio commented
For the trace, it was tested live on bb, no issue found it seems like.

2023-09-25 15:15 UTC, Ragnarok77-factorio approved these changes
Tested for months on bb main server , no issue, ok for the rest too.

2023-10-03 19:15 UTC, merged