Special game disable sciences from sending
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #354
Opened 2023-01-22 20:15 UTC by PlayerNoon

Brief description of the changes:

Adding feature to special games panel.
Allows to disable chosen science packs from sending. 
![image](https://user-images.githubusercontent.com/120744927/213938042-44aa395c-13be-477b-9d42-4363894cf7b8.png)

![image](https://user-images.githubusercontent.com/120744927/213938068-d32f17bc-6b4b-4eeb-825c-b54147b96747.png)

![image](https://user-images.githubusercontent.com/120744927/213938015-39c9e215-0312-477a-81e9-d0066ba4d2c3.png)

### Tested Changes:
- [ ] I've tested the changes locally
- [ ] I've not tested the changes.

2023-01-22 22:53 UTC, TheBigZet commented
How about displaying icons instead of names in setup gui?

Also, I'd prefer disabling the buttons instead of removing them (`enabled =false`), perhaps with some tooltip "disabled by special game"

2023-03-12 14:12 UTC, PlayerNoon commented
review someone :D

2023-06-05 18:57 UTC, TheBigZet commented
Ah I see what you did there. That feels overcomplicated. What I meant was to just disable the buttons in gui, like that:

2023-06-07 10:00 UTC, TheBigZet commented
I wonder if inverted tickboxes in config gui wouldn't be more intuitive. It starts with all boxes ticked (every sci enabled) and to disable you have to un-tick a box. It would allow for less conversions in code too I think

2023-06-25 06:59 UTC, Ragnarok77-factorio requested changes
Disabling science doesnt work

2023-06-25 06:59 UTC, Ragnarok77-factorio commented on comfy_panel/special_games.lua
> +	if table_size(message)>1 then
I hosted a game, one player joined a team, I enabled the event like that, yet I don't have the wrong message (should be purple disabled, not all science enabled) : 
![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/95619848/6c278e96-8410-49e9-a61d-1d25d512feed)

2023-06-25 08:06 UTC, TheBigZet commented on comfy_panel/special_games.lua
> +	if table_size(message)>1 then
Hmm it worked for me when I was testing it... Perhaps I had some uncomited changes

2023-07-23 08:30 UTC, Ragnarok77-factorio commented
I was not here when it happened so couldn't check log factorio too but the report of the event where it happened once was : 
"went well no bug/issue, on tytd one guy went spectate when he realized he can't spam green".

2023-09-25 15:05 UTC, Ragnarok77-factorio approved these changes
OK, tested for months on main bb server, no issue

2023-09-26 19:52 UTC, Ragnarok77-factorio commented
Fixed conflicts, I hope I didn't break anything, need to test just the disable sci + send to external server before merging.

2023-10-03 18:52 UTC, Ragnarok77-factorio commented
I tested it, was fine, nothing else was really added, just removed some useless empty space that were added, and fixed a merge mistake.

2023-10-03 18:57 UTC, Ragnarok77-factorio approved these changes

2023-10-03 18:57 UTC, merged