Increase the size and edit ratio of mixed patches
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #361
Opened 2023-03-24 19:43 UTC by bits-orio

This PR does 2 things:

1. Slightly increases the sizes of the Mixed ore patches.
2. Reduces (can't fix fully) the issue where sometimes Mixed ore patches were severely cropped off near Main. Now with these changes it happens only rarely.

2023-03-24 19:45 UTC, bits-orio commented
Adding some sample seeds. You can see Mixed ore patches are slightly bigger.


<img width="1316" alt="Screenshot 2023-03-24 012615" src="https://user-images.githubusercontent.com/90995942/227624507-b52f6920-51be-4986-b2b7-d690bbd49c20.png">
<img width="1317" alt="Screenshot 2023-03-24 012523" src="https://user-images.githubusercontent.com/90995942/227624511-b125ab98-7db6-409e-b0ee-671fbdf9d4a6.png">
<img width="1046" alt="Screenshot 2023-03-24 012428" src="https://user-images.githubusercontent.com/90995942/227624513-8a4ce7b4-fa56-42c5-bb07-371db610f6dd.png">
<img width="1054" alt="Screenshot 2023-03-24 012333" src="https://user-images.githubusercontent.com/90995942/227624514-ea2216fb-f45a-4dc7-8a4a-a3291d643ed0.png">
<img width="1303" alt="Screenshot 2023-03-24 012233" src="https://user-images.githubusercontent.com/90995942/227624517-138dece3-1bfc-43ff-be2c-5aa16052b060.png">
<img width="1036" alt="Screenshot 2023-03-24 012131" src="https://user-images.githubusercontent.com/90995942/227624518-0b774a97-7f2c-4c6f-b223-35b1aa84b53f.png">

2023-03-29 03:02 UTC, bits-orio commented
Screenshots after latest commit:

<img width="1683" alt="Screenshot 2023-03-28 195700" src="https://user-images.githubus
<img width="1683" alt="Screenshot 2023-03-28 195422" src="https://user-images.githubusercontent.com/90995942/228415795-74127d94-bc74-4318-a731-a87b415c8f8b.png">
<img width="1683" alt="Screenshot 2023-03-28 195916" src="https://user-images.githubusercontent.com/90995942/228415796-659acfce-85e8-445c-85d6-c6bced8eb2e9.png">
ercontent.com/90995942/228415790-977fa994-df6a-4c13-a906-afff55d36be7.png">
<img width="1681" alt="Screenshot 2023-03-28 195544" src="https://user-images.githubusercontent.com/90995942/228415793-e8344c9d-ffab-4d92-a6fa-877e5147a790.png">

2023-09-25 15:26 UTC, Ragnarok77-factorio commented
I'm confused @bits-orio  : 
Poll was : 
![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/95619848/4c6558f8-7867-4480-853b-4adff3733e0a)

But in your PR, it's 1:1:1:1 ratio, why ? Is your PR unrelated to this poll ? Am I missing something..?

2023-10-03 20:30 UTC, Ragnarok77-factorio commented
After a discussion, for the trace, the ratio are not 1 1 1 1 but he repeated the same ores multiple times , shown here in code 
`local ores = {"iron-ore",  "copper-ore", "iron-ore", "copper-ore", "iron-ore", "coal", "iron-ore", "copper-ore",  "iron-ore", "copper-ore", "stone", "coal"}
-- mixed_ore_multiplier order is based on the ores variable
local mixed_ore_multiplier = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}`
The only issue remaining is the ratio are not exactly the same as the poll, need them to match the poll.

2023-10-03 20:32 UTC, Ragnarok77-factorio requested changes
Need changes to be done first.

2023-10-03 20:32 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/terrain.lua
> +local ores = {"iron-ore",  "copper-ore", "iron-ore", "copper-ore", "iron-ore", "coal", "iron-ore", "copper-ore",  "iron-ore", "copper-ore", "stone", "coal"}
The ratio are a bit off from the poll, need to be fixed first.

2023-10-03 20:32 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/terrain.lua
> +	-- if noise < 0.42 then return end
If it's commented, we can remove it them no, as it's just useless lines...?

2023-10-25 17:26 UTC, Ragnarok77-factorio commented
Removed n+2 as the PR seems to have become forgiven, will be back in the priority once the conflicts and ratio of ores is fixed.

2023-11-01 09:23 UTC, Ragnarok77-factorio commented
you alive @bits-orio to fix the PR...?

2023-11-22 16:59 UTC, Ragnarok77-factorio commented
Ping @bits-orio ...?

2023-12-03 19:38 UTC, clifffrey commented on maps/biter_battles_v2/terrain.lua
> +					local i = math_floor(noise * 25 + math_abs(pos.x) * 0.05) % 15 + 1
Can you make a local variable for the 15 (which is probably set to mixer_ore_multiplier's length?

2023-12-03 19:38 UTC, clifffrey commented on maps/biter_battles_v2/terrain.lua
> +	if left_top_x + 16 < -150 or left_top_x + 16 > 150 or left_top_y + 16 < -150 then
can you add a comment explaining this conditional?

2023-12-03 19:44 UTC, clifffrey commented on maps/biter_battles_v2/terrain.lua
> +local ores = {"iron-ore",  "copper-ore", "iron-ore", "stone", "copper-ore", "iron-ore", "copper-ore", "iron-ore", "coal", "iron-ore", "copper-ore",  "iron-ore", "stone", "copper-ore", "coal"}
perhaps this could be clearer as something like

```
local ore_ratios = {"iron-ore"=6, "copper-ore"=5, ...}
local ores = {};
for (... ore_ratios ...) {
  for 1, count, 1 {
    table.insert(ores, ore);
  }
}
```

I don't actually know lua very well, so excuse me for the pseudocode

2023-12-03 19:45 UTC, clifffrey commented on maps/biter_battles_v2/terrain.lua
> +local mixed_ore_multiplier = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}
I'd lean towards removing this completely, because I don't think that the functionality is all that likely to be used, and if someone wants it, they can always add the functionality back in.

If we do want to keep the functionality, I'd suggest making this a map of ore-name to average-density (and renaming it to something like average_ore_base_density).  i.e. change the value from 1 to 900, and change the math_random(800, 1000) below to somehow be math_random(0.9, 1.1) or something.... but again, just removing it makes more sense to me.

2023-12-04 21:45 UTC, bits-orio commented on maps/biter_battles_v2/terrain.lua
> +local mixed_ore_multiplier = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}
I do not understand this comment. Are you suggesting to remove mixed ores completely?

2023-12-04 21:52 UTC, bits-orio commented on maps/biter_battles_v2/terrain.lua
> +	if left_top_x + 16 < -150 or left_top_x + 16 > 150 or left_top_y + 16 < -150 then
I will add a comment.

2023-12-04 22:17 UTC, clifffrey commented on maps/biter_battles_v2/terrain.lua
> +local ores = {"iron-ore",  "copper-ore", "iron-ore", "stone", "copper-ore", "iron-ore", "copper-ore", "iron-ore", "coal", "iron-ore", "copper-ore",  "iron-ore", "stone", "copper-ore", "coal"}
ahh yes, makes sense.

2023-12-04 22:18 UTC, clifffrey commented on maps/biter_battles_v2/terrain.lua
> +local mixed_ore_multiplier = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}
I was just suggesting removing this variable completely, and replacing code that accesses "mixed_ore_multiplier[x]" with the value "1".

2023-12-04 22:23 UTC, clifffrey commented on maps/biter_battles_v2/terrain.lua
> +					local i = math_floor(noise * 25 + math_abs(pos.x) * 0.05) % 15 + 1
so I was trying to suggest adding a variable like `local num_ores = TableLength(ores)`, but I see now that this is not a built-in piece of functionality in lua.  In any case, I'd still suggest adding `local num_ores = 15` right below the definition of ores, and using the value here.

2023-12-04 22:43 UTC, bits-orio commented on maps/biter_battles_v2/terrain.lua
> +					local i = math_floor(noise * 25 + math_abs(pos.x) * 0.05) % 15 + 1
Yeah good idea, it would be good for readibility, I will add variable.
It took me a while too to figure out that `4` is not just a random magic number. Figured that out only when I reverse engineered the logic and debugged a few times.

2023-12-16 06:46 UTC, Ragnarok77-factorio commented
Conflicts needs to be resolved @bits-orio

2023-12-16 18:36 UTC, developer-8 commented
often enough it discriminates coal, today I have already seen several games where coal was missing in mixed patches near main
the image is comparing after|before PR
![Screenshot from 2023-12-16 20-28-42](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/88335092/16a1bec9-09ae-40f8-9126-ffd2a8c950be)

2023-12-18 07:51 UTC, Ragnarok77-factorio commented
Yes I notice sometimes coal is missing or barely any. 

I also feel like the frequency of mixed was increased a lot, which is weird.

2023-12-29 08:32 UTC, Ragnarok77-factorio requested changes
Conflicts in maps/biter_battles_v2/terrain.lua needs to be resolved first

2024-03-09 22:38 UTC, clifffrey approved these changes

2024-03-09 22:39 UTC, merged

2024-03-09 22:39 UTC, clifffrey commented
merged as this (well, code that is very very close to this) has been running on the server since January