Start Tracking version and add info.json
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #363
Opened 2023-04-19 18:53 UTC by XVhc6A

### Brief description of the changes:
We should have an info file and keep the version updated so it's easier to track down bugs.

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2023-04-20 16:52 UTC, TheBigZet commented
Why am I listed as the author? :D

2023-06-21 19:35 UTC, XVhc6A commented
who do you think should be author @TheBigZet ? Since you're the one that manages it I think it's fair to call you 'author' since it's really just who manages the mod as it's deployed to the factorio portal, not necessarily who wrote it.

2023-07-12 16:33 UTC, TheBigZet requested changes

2023-07-12 16:33 UTC, TheBigZet commented on info.json
> +  "author": "TheBigZet",
```suggestion

```

2023-10-13 16:01 UTC, Ragnarok77-factorio commented
The discord link is dead, would probably remove it, and probably rename it to free bb instead..? asking on discord what people think

2023-10-27 07:43 UTC, merged