fix Issue with boss killscore
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #366
Opened 2023-04-21 17:23 UTC by S-T-A-L-K-R

### Brief description of the changes:
Attempt to fix issue "Boss killed doesnt count as killscore? #346". Yes, big part of them doesn't count.

### Tested Changes:
- [X] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

I've tested it locally, and despite
```
 262.357 Script @C:/Users/{User}/AppData/Roaming/Factorio/temp/currently-playing/utils/event_core.lua:51: [ERROR] Given force is not valid, it must be a valid force index, a string (name of the force) or a LuaForce. in .../Factorio/temp/currently-playing/functions/boss_unit.lua:31
```
it seems to be working.

2023-04-22 11:52 UTC, TheBigZet requested changes

2023-04-22 11:52 UTC, TheBigZet commented on functions/boss_unit.lua
> +		entity.die(event)
According to the API https://lua-api.factorio.com/latest/LuaEntity.html#LuaEntity.die `die()` can take `LuaForce` and `LuaEntity` as a cause. I doubt your PR fixes anything. Perhaps passing event.force and/or event.cause would do sth

2023-04-23 20:20 UTC, S-T-A-L-K-R commented
Factorio API wasn't as helpful as i hoped.
I randomly deleted manual invocation of "entity.die()" and it works, now even without errors in console.
I believe manual "entity.die()" call, caused "on_entity_died()" to not receive proper data.
Evidence: https://youtu.be/t4u_NaFJonY
Console final output(because i forgot to record it): 
![FactorioConsoleDump](https://user-images.githubusercontent.com/45820682/233863416-1250ed79-db37-4e9e-92cc-9fb2d99bd262.png)

2023-04-25 05:21 UTC, TheBigZet commented
Did you check that the score is in fact increasing?
`on_entity_died()` has to recive at least `cause` https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/blob/master/comfy_panel/score.lua#L388

Removing `entity.die()` will result in boss becoming normal biter after his healthbar gies to 0. Which makes then stronger and changes healthbar more into shield

2023-09-22 05:42 UTC, S-T-A-L-K-R commented
yea, passing _entity.cause_ as a force seems to be working better

2024-03-14 04:34 UTC, clifffrey commented
This has been fixed by #436

2024-03-14 04:34 UTC, closed without merging