feat: add send to server in admin gui
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #368
Opened 2023-05-21 12:50 UTC by gabrielchl

### Brief description of the changes:
Add item in admin GUI special games tab to send players to external server
so that we don't need to find the command everytime

![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/5616556/56672977-dba0-4b1f-bcfc-47f701fe7cc0)

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [x] I've not tested the changes.

2023-05-21 13:00 UTC, TheBigZet requested changes
Add automatic popup for joining players.
Use `Event.add_removable()` with `Task.set_timeout()` and `Event.remove_removable()` so that it's active for, let's say, just an hour.

2023-05-21 13:22 UTC, gabrielchl commented
> Add automatic popup for joining players. Use `Event.add_removable()` with `Task.set_timeout()` and `Event.remove_removable()` so that it's active for, let's say, just an hour.

Added the event handler. For unregistering the event handler, I opted for a command instead of a time-based approach as we rarely know how long a game lasts.
(untested btw, I'll need someone to test it / test it with)

2023-05-21 17:59 UTC, TheBigZet requested changes
Seems like `add_removable_function` requires 3 parameters : event, function and name. Then it's referred to with `name` in `remove_removable_function`.

Also, the function probably doesn't need to be in `global` table

2023-05-21 17:59 UTC, TheBigZet commented on comfy_panel/special_games.lua
> +		Event.add_removable_function(defines.events.on_player_joined_game, global.send_to_external_server_player_joined_game_handler)
```suggestion
		Event.add_removable_function(defines.events.on_player_joined_game, global.send_to_external_server_player_joined_game_handler, "server_switch_popup")
```

2023-05-21 17:59 UTC, TheBigZet commented on comfy_panel/special_games.lua
> +	Event.remove_removable_function(defines.events.on_player_joined_game, global.send_to_external_server_player_joined_game_handler)
```suggestion
	Event.remove_removable_function(defines.events.on_player_joined_game, "server_switch_popup")
```

2023-05-21 19:33 UTC, gabrielchl commented
> Seems like `add_removable_function` requires 3 parameters : event, function and name. Then it's referred to with `name` in `remove_removable_function`.
> 
> Also, the function probably doesn't need to be in `global` table. \edit Oh and I'd also prefer to have some safety mechanism, as admins like to forget about stuff, like disabling the popup :)

this is the docs in the events file
I'll add the time triggered safety mechanism

![Screenshot 2023-05-21 130958](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/5616556/7b1b8cef-47e5-4ba2-8fab-cf8448d3f95b)

2023-05-21 21:20 UTC, TheBigZet commented
Huh, then that example is wrong. Check the function definition and the comment right before it

2023-05-28 19:12 UTC, TheBigZet commented
@gabrielchl tested on test server. Popup for connected players works. Popup for newly connecting players doesn't. Desync after opening `/debug`

2023-06-13 11:11 UTC, TheBigZet commented
@XVhc6A @AwesomePatrol @gsquaredxc What do you think of that vs simple Event with one enabled/disabled condition? (In terms of performance and clarity)

2023-06-25 06:39 UTC, Ragnarok77-factorio commented
> @XVhc6A @AwesomePatrol @gsquaredxc What do you think of that vs simple Event with one enabled/disabled condition? (In terms of performance and clarity)

Performance I don't think it matters much as the event "on player joined" is rarely called, and the code being done here is very fast to execute too I think..... Did a profiler : 
![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/95619848/bf56ae7b-35df-4c2e-9681-89419915aa1d)



For clarity, don't really care which implementation is done. I've just a doubt about how robust this removable function is though, gonna test something.

2023-06-29 10:46 UTC, merged