add server restart immediately command
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #379
Opened 2023-07-26 03:15 UTC by XVhc6A

### Brief description of the changes:
---Fill in---
```
./server-restart-immediately {optional seed: int}

```

Restart the server immediately and optionally set the seed.

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2023-09-24 11:47 UTC, Ragnarok77-factorio requested changes
Waiting for what you think

2023-10-10 14:40 UTC, Ragnarok77-factorio commented on commands/misc.lua
> +    'server-restart-immediately',
I talked about it with admins, they don't like /force-map-restart-instant as it's too close to another command tab, they don't like server-restart as it's not a server restart.

They suggested for example : /instant-map-reset

2023-10-10 14:59 UTC, Ragnarok77-factorio commented
One thing I don't understand, If I set for example the seed to "d", I expected it to have the same map, but it's not the case, any explanation..? 🤔  I feel like the map seed option does nothing, not like it matters, as the most important part is the instant map reset but.. mh @XVhc6A

2023-10-10 15:04 UTC, Ragnarok77-factorio commented
Nevermind, it's because the seed is a number, so by putting a letter => nil => no seed set. Wow that's amazing possibility.

2023-10-10 15:11 UTC, Ragnarok77-factorio commented
As I'm not sure if you will still maintain it as there was no news, I updated the code.

2023-10-10 15:32 UTC, Ragnarok77-factorio approved these changes
OK, nothing else to add.

2023-10-12 18:45 UTC, developer-8 commented on control.lua
> +function math.random_seeded(...)
There are few math functions in `utils/utils.lua` may be its possible to move this function there

2023-10-12 21:05 UTC, developer-8 commented
fyi on small numbers it generates the same values
https://forums.factorio.com/viewtopic.php?f=23&t=70060

2023-10-13 15:55 UTC, Ragnarok77-factorio commented
> fyi on small numbers it generates the same values https://forums.factorio.com/viewtopic.php?f=23&t=70060

Good to know it doesn't work for low values, if author motivated, he can prevent for example seed below 341 , and only allow 341 as the seeds would be the same 🤔

2023-10-13 16:07 UTC, Ragnarok77-factorio commented on control.lua
> +function math.random_seeded(...)
Yeah, would make sense to move it there too I guess if possible 🤔

2023-10-16 17:21 UTC, developer-8 requested changes

2023-10-16 17:21 UTC, developer-8 commented on maps/biter_battles_v2/init.lua
> +		global.next_map_seed = global.random_generator(341, 2 ^ 31)
replace 2 ^ 31  with 4294967294 for consistency?

2023-10-16 17:26 UTC, Ragnarok77-factorio commented on commands/misc.lua
> +					game.print("Error: Seed must be between 341 and 4294967294 (inclusive).", Color.warning)
Yes only the admin running the command should see the error, players are gonna be very confused otherwise why it's printing that message.

2023-10-16 21:51 UTC, XVhc6A commented on maps/biter_battles_v2/difficulty_vote.lua
> +	if not global.difficulty_votes_timeout then Init.tables() end
Honestly, I'm not sure.

When I started the game in single player mode to test this, I got an error that `global.difficulty_votes_timeout` was not defined?

2023-10-17 09:00 UTC, developer-8 commented on maps/biter_battles_v2/difficulty_vote.lua
> +	if not global.difficulty_votes_timeout then Init.tables() end
Cant reproduce it. Its work fine for me without this line.

2023-10-17 09:04 UTC, developer-8 commented
Tested the speed of the new random number generator
`/measured-command for i=1,1000000 do local a = global.random_generator(0,i) end`
60-70ms
`/measured-command local random = global.random_generator for i=1,1000000 do local a = random(0,i) end`
50-60ms
`/measured-command for i=1,1000000 do local a = math.random(0,i) end`
50-60ms
`/measured-command local math_random = math.random for i=1,1000000 do local a = math_random(0,i) end`
40-50ms

2023-10-17 09:23 UTC, developer-8 commented on commands/misc.lua
> +            player.print("Restarting with autopicked map seed: " .. global.next_map_seed, Color.warning)
Successful map reset message should be visible for all and mention who initiate map reset. Also add trace message to log like in /force-map-reset command. What do you think @Ragnarok77-factorio

2023-10-17 16:35 UTC, Ragnarok77-factorio commented on commands/misc.lua
> +            player.print("Restarting with autopicked map seed: " .. global.next_map_seed, Color.warning)
Yes indeed @developer-8 , it would be nice to have this information.

2023-10-17 17:49 UTC, developer-8 approved these changes

2023-10-18 17:56 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/init.lua
> +	if global.random_generator(1,2) == 1 then global.next_attack = "south" end
Just curious, why was it changed here ?  I understand for the settings,  but why here..? A details and probably don't matter but..? Mh

2023-10-18 18:03 UTC, Ragnarok77-factorio approved these changes
OK, and tested it, fine, will need a second round before merge to master due to quite some changes on this PR, adding another week of testing

2023-10-18 18:05 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/difficulty_vote.lua
> +	if not global.difficulty_votes_timeout then Init.tables() end
Since it's not in the code anymore, resolved.

2023-10-23 06:56 UTC, Ragnarok77-factorio approved these changes
OK, not much to add..

2023-10-27 05:45 UTC, XVhc6A commented
@Ragnarok77-factorio why don't you want to be able to ./instant-map-reset before re-roll is done? I feel like that slightly ruins the point.

2023-10-27 07:49 UTC, Ragnarok77-factorio commented
You can try to have instant map while reroll is being voted, it's quite a headache to handle (add quite some annoying edge cases that are not correctly handled..) 

Removed "ready to merge" tag :
=> Conflict appeared...
=> Maybe @XVhc6A  wants to make it possible to be able to instant map reset even if there is a reroll..?

2023-11-01 06:55 UTC, Ragnarok77-factorio approved these changes
Merge was fine, tested ok, and checked the change that was done. ready for merge!

2023-11-03 15:53 UTC, merged