Jail voting
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #387
Opened 2023-10-11 22:01 UTC by TheBigZet

### Brief description of the changes:
---Fill in---

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2023-10-15 19:33 UTC, TheBigZet commented
To be checked:
`player_vote` appears not to be properly globalized (values not updating in `/debug` not `global.tokens[8]`)

2023-10-16 18:34 UTC, Ragnarok77-factorio requested changes
I hope I didn't test it too early, but since it's not a draft, should not be..? Anyways, I wanted to see how it's displayed/working.

There is also a conflict file that needs to be resolved too.

2023-10-16 18:34 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/jail.lua
> +    player.teleport(surface.find_non_colliding_position("character", data.fallback_position, 128, 1), surface)
I hosted the update, as an admin, not in jail, I did "/free Ragnarok77 because he didnt do anything wrong" 
Error is shown in log  : 
Roaming/Factorio/temp/currently-playing/utils/event_core.lua:51: [ERROR] ...io/temp/currently-playing/maps/biter_battles_v2/jail.lua:73: attempt to index local 'data' (a nil value) in ...io/temp/currently-playing/maps/biter_battles_v2/jail.lua:83

2023-10-16 18:34 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/player_vote.lua
> +			time_to_live = vote.timer * 60,
How to reproduced , I hosted as admin, then did /promote myself, then /jail myself random reason and I got that : 
`event_core.lua:51: [ERROR] .../currently-playing/maps/biter_battles_v2/player_vote.lua:42: attempt to perform arithmetic on field 'timer' (a nil value) in .../currently-playing/maps/biter_battles_v2/player_vote.lua:326`

2023-10-16 19:59 UTC, TheBigZet commented on maps/biter_battles_v2/jail.lua
> +    player.teleport(surface.find_non_colliding_position("character", data.fallback_position, 128, 1), surface)
For quick gui peak try `\vote` instead

2023-10-16 21:26 UTC, TheBigZet commented
> I hope I didn't test it too early, but since it's not a draft, should not be..? Anyways, I wanted to see how it's displayed/working.
> 
> There is also a conflict file that needs to be resolved too.

Keep in mind that the target of jail vote is frozen for its duration, so he won't be able to click on buttons

2023-10-25 18:19 UTC, Ragnarok77-factorio requested changes

2023-10-25 18:19 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/player_vote.lua
> +		if vote.timer > 0 then
On test server where it was deployed :
I did /trust Ragnarok77
then /vote jail Ragnarok77 random reason to vote,
I left the server, came back very fast, the vote progress was frozen, but once the vote was over, I got desynched.

I think it generated this error too (root cause maybe? unsure?)..? 
`Factorio/temp/currently-playing/utils/task.lua:94: .../currently-playing/maps/biter_battles_v2/player_vote.lua:229: attempt to compare number with nil`

2024-01-04 16:54 UTC, Ragnarok77-factorio commented
Conflicts on PR, no update for months, feel free to re open if you are going to work on it.

2024-01-04 16:54 UTC, closed without merging