Biter terrain tiles optimization
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #389
Opened 2023-10-14 09:53 UTC by cogito123

### Brief description of the changes:
This patchset optimizes biter terrain generation by removing resource/math intensive simplex noise computations. At present, we run 1024 noise functions per each chunk in biter area. The side effect of this change is that pattern of biter area had to be changed to other 2D seamless texture. There is no problem changing the texture as it comes at no performance impact.

Speed at which 1024 tiles were generated previously (tiles only, not structures etc):
max: 27.3ms
min: 6.9ms
mean: 10.5ms

When this solution is applied:
max: 8.8ms
min: 1.0ms
mean: 2.6ms

I took the measurements after map was fully loaded and just idling. Then I navigated towards nests and kept pushing for few seconds. I then took sample from last 10s and computed metrics based on that.

Because we're constrained to 16ms+- per each tick, new solution frees up lots of time to handle other events like threat farming, which typically triggers map generation in biter area.

![1](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/59515242/c9bbbcbd-372c-4128-b305-7e49d1f81540)
(Screenshot modifies colors, it looks less saturated in game)

### How texture is generated
First I found seamless cartoonish 2D texture, I processed it to highlight the edges, turned into grayscale, manipulated contrast and resized image to 128x128. As values on grayscale are between 0 - 127 I was able to map different shade ranges to different shades of dirt tiles.
The mapping was performed by separate program I wrote for this occasion (not sure where to upload it). Output of the mapping is complete lua script loaded as part of scenario that contains hardcoded values per each position within 128x128 2D lua array.
![texture](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/59515242/40c4e940-17a4-4612-873e-6f31ef160ab4)

### Tested Changes:
- [X] I've tested the changes locally
- [ ] I've tested the changes online

2023-10-15 07:31 UTC, Ragnarok77-factorio commented
For now I just tested it, didn't find issue or error. 
I didn't and won't try though to be honest to deeply test and compare perf on my side too, trusting his results, but if anyone else is motivated to do the check , feel free, here are the screenshots : 
Before : 
![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/95619848/f03dbebd-4b62-4dd1-9b49-65cfc5961bfc)
After : 
![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/95619848/60e696fa-5000-477f-8c2f-4b9d13c29d26)
Before : 
![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/95619848/670a0004-4cfe-4361-a892-8e3be59e18ab)
After : 
![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/95619848/b68a2183-a6e9-4397-bc6f-4011578473a6)

2023-10-18 18:19 UTC, Ragnarok77-factorio requested changes
Change to do, but depending on the explanation, might be fine otherwise, not closed minded at all, just curious as it was the first time I've seen a goto (I try to avoid using them.. maybe I'm wrong though, I don't know)

2023-10-18 18:19 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/terrain.lua
> +				goto d_b_a
Maybe I'm missing something, but why not just not negate the if instead and have the code below in this if so there is no goto anymore, think first time I'm seeing a goto in lua... Maybe i'm wrong, but would it not be better this way, what do you think ?

2023-10-18 18:20 UTC, Ragnarok77-factorio commented
I tested it locally too, no issue

2023-10-18 19:48 UTC, cogito123 commented on maps/biter_battles_v2/terrain.lua
> +				goto d_b_a
This is a poor man's "continue" statement in lua.
Wrapping large blocks of code in IF statements leads to a code growing horizontally, i.e. you start creating staircase. A good practice is to exit branch early instead of going deeper into nested IFs.

2023-10-18 19:54 UTC, cogito123 commented
I applied new 512x512 grid (previous one was 128x128) which is about 536KB in size. It's less repetitive at larger scale and looks better at closer look.
![texture2](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/59515242/8f65a13b-acee-4256-b575-bee4e0a4d934)
![minimap](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/59515242/a968eee7-3465-456e-8d0a-d0ff28f32ec0)
![img](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/59515242/7581939c-adc8-48ee-9600-9abcd650f8d2)

2023-10-19 14:51 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/terrain.lua
> +				goto d_b_a
Understood, fine for me then, unsure what other devs think about it.

2023-10-19 15:00 UTC, Ragnarok77-factorio commented
It's a lot worse visually that I thought, tested it, no issue, ok for me.

2023-10-27 07:45 UTC, Ragnarok77-factorio commented
No one complained about the visual of it. fine for me.

2023-10-27 07:45 UTC, merged