Add /spectator-chat command
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #405
Opened 2023-10-28 21:10 UTC by clifffrey

This is useful if users that are admins want to spectate games and chat with just the spectators.

### Brief description of the changes:
This came up when mysticamber was accidentally broadcasting because they are an admin

### Tested Changes:
- [x] I've tested the changes locally (as I was only one user, I was not able to verify the visibility of messages to just the correct teams, but I think that code inspection makes it pretty clear, but let me know if I should do more testing)

2023-10-28 21:11 UTC, clifffrey commented
@mysticamber FYI

2023-10-28 23:41 UTC, gsquaredxc commented
I like this, but I think I would like a shorthand version of the command as well. Additionally, not something you need to fix, but if we decide to expand this in the future for any reason the behavior that any string not equal to "north" or "south" is equivalent to "spectator" is something of note and possibly unexpected. Also note PR #402, which should not conflict but is working on the same file.

2023-10-29 02:19 UTC, clifffrey commented
Do you have a suggestion for the shorthand version? I figured that "/sp<tab>" was pretty short to type already, and I feel a bit weird about using any of "/spc" "/spec" or "/specs" (some of which would prevent the "/sp<tab>" version from working as well).

2023-10-29 13:35 UTC, TheBigZet commented
What being an admin has anything to do with this feature?

2023-10-29 16:41 UTC, clifffrey commented
@TheBigZet That is a great question. I did the work to be able to run multiple instances of Factorio locally, so that I could actually test this behavior myself. From my testing, it is the case that admin users that are spectators automatically have their chats broadcast when in "tournament mode", and non-admins do not. That caused me to look harder to discover why there was this behavioral difference, and I think that I found the logic in [these lines](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/blob/97c32c241cdb5232cf346f78c20434c57e2bd2d7/maps/biter_battles_v2/functions.lua#L354-L355)

I updated the pull-request description with a bit more context. I definitely find the current behavior very surprising: If you are on the spectator force, and want to know if your chats will be broadcast to other teams or not, you need to know if tournament mode is enabled, and you need to know if you are an admin, because both of those variables end up impacting the decision. In many ways, just requiring "/s" if you want to shout would be more predictable/understandable for new users.

2023-10-29 17:24 UTC, TheBigZet commented
In normal games messages sent by all spectators are automatically shared with north and south forces. I believe this is intentional and dates back to the beginning of time.

In tournament mode (1v1, pros vs noobs, ...?) spectator chat isn't shared with teams, most likely to prevent leaking tactical info. Again, intentional.

Admins, most likely serving the role of a referee or an organizer, are an exception from this rule. Maybe it worked better when special games (using tournament mode) or admins weren't as common as they are today. But this behavior was intentional.

2023-10-29 17:33 UTC, clifffrey commented
That all makes sense to me (that history from long ago created this intentional behavior). It is unfortunate how non-discoverable it is for new users to understand who can see their chat messages (as well as it being surprising for newly promoted admins, as was the case for @mysticamber who was very surprised that they were broadcasting as a spectator).

Anyhow, I am fine to leave this commit as-is, abandon it, or do something different. As-is, this change potentially helps in two cases: spectating admins during tournament-mode games, and spectating non-admins during non-tournament-mode games, where this command allows these users to chat exclusively with spectators if they want to.

2023-10-29 21:06 UTC, mysticamber commented
Eh why tag me :p I told you I retired lol. 
I'm only willing to take care of Hedwig and Starly :p

2023-10-29 21:25 UTC, mysticamber commented
IMO spec chat should be spec chat by default.
Admins need to be the exception, for the reasons TBZ listed out. 

That's just my opinion though.

2023-11-05 07:09 UTC, Ragnarok77-factorio commented
A bit early stil but seems like community don't want spectator chat to be default spectator only (will see if poll changes a lot, but for now it's 8 yes 9 no..).

I would like though a shortcut too, but not sure what.. what do you mean by /sp version..?

2023-11-07 18:38 UTC, clifffrey commented
> I would like though a shortcut too, but not sure what.. what do you mean by /sp version..?

Sorry, I had markdown bugs in my post above. I updated it. I meant "/sp\<tab\>". Specifically, by using tab-completion, very few keystrokes can still be used for a long command. I worry that if we created a shortcut such as "/spchat" then "/sp\<tab\>" would no longer work, and it would require more keystrokes.

Anyhow, I am fine to add a shortcut. If I am forced to choose the shortcut command, I guess I would make it "/spec", but that seems confusing to me in a few different ways.  Just let me know what shortcut to add if people want one.

2023-11-15 16:23 UTC, Ragnarok77-factorio commented
Added vote result in first message.

2023-11-15 16:29 UTC, Ragnarok77-factorio commented
Beware of https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/pull/402 , whatever PR is merged first, will need an update so ignore is not broken again, that's why i'm not approving it yet, but it will be deployed on main bb server anyways this PR.

2023-11-15 17:31 UTC, clifffrey commented
FWIW, it occurred to me that some of the "discoverability" issues could be addressed if we automatically generated a message the first time someone sends a message as a spectator (and maybe a different message the first time that they send a message as a spectator that includes a map ping) that explained who could see the messages.

I'm open to creating a PR with this logic, if the gut feeling is that it would not be too annoying (to see this message every time you connect and send your first chat), but I'm ok either way.

2023-11-16 21:21 UTC, Ragnarok77-factorio commented
You mean, when it's the first time they send a message they get an explanation ?

It could be a good idea, and will be new player friendly, but it will need some work to have this info stored in a db (requires work on bb code + also server side), for it to persist and not be lost at each reboot/update of the server..?

I wouldn't be against it but that's quite some work and not a big priority =/

Also 402 was merged, but I don't know why I said this PR should be updated, as it's using chat_with_team function, which is the function calls print_message_to_players function that got updated to fix the bug about ignore... so...

Sorry for the useless remark.

2023-11-16 21:23 UTC, Ragnarok77-factorio commented
For the short way for command name, I think it might not be required, whenever spaghetti is removed, /sp and tab will gets this command, so...

2023-11-22 17:21 UTC, Ragnarok77-factorio requested changes
A little bug to fix, worked nicely otherwise

2023-11-22 17:21 UTC, Ragnarok77-factorio commented on commands/chat_commands.lua
> +    chat_with_team(message, 'spectator')
Little bug found, if I do a ping in my /spectator-message , it's not shown, could it be fixed..?

2023-11-22 18:35 UTC, gsquaredxc commented on commands/chat_commands.lua
> +    chat_with_team(message, 'spectator')
Looks like that issue comes from line 14. Now that we have spectator only chat, do we want to exclude gps still? We probably need to determine the intended behavior before changing the code, but it’s quite trivial to change.

2023-11-23 17:15 UTC, Ragnarok77-factorio commented on commands/chat_commands.lua
> +    chat_with_team(message, 'spectator')
No idea, spectator not seeing spectator ping don't make any sense but except that I don't know 🤔

2023-11-29 16:57 UTC, Ragnarok77-factorio commented on commands/chat_commands.lua
> +    chat_with_team(message, 'spectator')
After discussion, finally we can always change it in another PR /debate over what to do.

2023-11-29 16:58 UTC, Ragnarok77-factorio approved these changes

2023-11-29 17:07 UTC, merged