Start getting rid of the more useless Event calls
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #410
Opened 2023-11-08 11:53 UTC by XVhc6A

### Brief description of the changes:
I'd like to start moving away from using the comfy Event framework.

Although it can be helpful, when it comes to FBB this often leads to spaghetti that is just too twisted to understand (see how instant-map-reset cannot be done until after reroll)

In addition to helping out with confusion during debugging, removing this code will lower the barrier to entry to the code, make our codebase more similar to other factorio mods/scenarios (https://github.com/raiguard/Krastorio2/blob/master/control.lua), and allow us to fine tune our events and scheduling to a better degree.  

This isn't ready yet, but I will split this into a few PRs so as to not overwhelm reviewers.

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2023-12-29 09:53 UTC, Ragnarok77-factorio requested changes
Needs bug to be fixed first

2023-12-29 09:53 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/functions.lua
> -	local entity = event.created_entity
...mp/currently-playing/maps/biter_battles_v2/functions.lua:268: attempt to index global 'entity' (a nil value) in ...io/temp/currently-playing/maps/biter_battles_v2/main.lua:66

When you build a turret , or use ghost then bots to make it and so on.


https://discord.com/channels/823696400797138974/1003021908796784800/1190225821873479700

2023-12-29 09:54 UTC, Ragnarok77-factorio commented
Changed milestone until the bug is fixed (check review).

2024-01-05 06:22 UTC, XVhc6A commented
testing locally doesn't yield any errors now.  also cleaned up some other functions as well.

2024-01-09 21:06 UTC, XVhc6A commented
going to close this in favor of a split version.

2024-01-09 21:06 UTC, closed without merging