Reset game speed to 1 after silo death
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #422
Opened 2023-12-03 08:10 UTC by gsquaredxc

### Brief description of the changes:

Resets game speed to 1 after the game has completed. This allows the reset game timer to complete at normal speed.

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [x] I've not tested the changes.

2023-12-03 11:05 UTC, Ragnarok77-factorio commented
Mh hard to label this one, but whatever.

2023-12-03 11:06 UTC, Ragnarok77-factorio requested changes
Very minor thing but OK otherwise

2023-12-03 11:06 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/game_over.lua
> +
Why the space ? and indent is different from the rest : 
![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/95619848/e766dc04-eef2-4b16-b491-2f81f209d3d6)

2023-12-04 21:29 UTC, Ragnarok77-factorio approved these changes
Was quite difficult to review this massive update, seems OK.

2023-12-04 21:29 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/game_over.lua
> +
Yes, indeed, not convinced it's a good idea tbh to format the whole project, if we ever want to compare later it's gonna be horrible will all the formatting difference shown + conflicts everywhere and so on... Fine now, I can check on github too, if you over the indent, you can see if it's a tab or a space, and compare 2 existing line.

2023-12-05 05:01 UTC, clifffrey commented
I worry that in some cases, perhaps some players need a lower game.speed value to not be disconnected, just when the factories are so large (i.e. not due to biter pathing, just due to the number of inserters/etc), and this might result in many players being dropped right after the game ends.

Anyhow, I'm not trying to say that this should be a blocker on this change, I just want to call out the potential risk. For related reasons, the change might be slightly safer/less-surprising if it printed something out to the console in the case where the game speed was not already 1. Relatedly, if the game speed was set to 2 or something, it is not obvious to me that it should be lowered to 1.

2023-12-15 19:41 UTC, XVhc6A approved these changes
I think this changes makes sense.  I've never run into this problem myself, but i have seen it complained about in discord before.

2023-12-20 11:23 UTC, merged