Do a cheeky optimization of one `__index` call
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #424
Opened 2023-12-10 19:07 UTC by RadiantUwU

### Brief description of the changes:
The objective of this is to move the `boss_units` from a global table index and another index (resulting in 2 indexes) to 0 indexes by simply turning it into an upvalue

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [X] I've not tested the changes.

2023-12-11 18:34 UTC, RadiantUwU commented
> Cogito tested it, it desynchs.
> 
> it's highly advised too to test the code locally first.

Thank you for telling me about this, i'll import in VSCode and verify what else needs to be modified and will test it.

2023-12-11 20:47 UTC, RadiantUwU commented on maps/biter_battles_v2/init.lua
> +	boss_unit.force_resync 'from_global'
A resync is forced on the init since for some weird reason it decides to *not* use the init functions over here.

2023-12-11 20:52 UTC, RadiantUwU commented
How do i test it out?

2023-12-11 21:28 UTC, RadiantUwU commented
I actually cannot find a way to test this out, i tried putting it in my scenarios and still fails to initialize.

2023-12-15 19:38 UTC, XVhc6A requested changes
factorio lua is not the same as standard lua.
if you read through https://wiki.factorio.com/Tutorial:Scripting you will understand the differences.

2023-12-18 18:13 UTC, RadiantUwU commented
> factorio lua is not the same as standard lua. if you read through https://wiki.factorio.com/Tutorial:Scripting you will understand the differences.

It doesn't say what you suggested to change...?

2023-12-18 19:12 UTC, RadiantUwU commented
What's blocking this from being reviewed and merged?

2023-12-30 20:18 UTC, clifffrey commented
My gut feeling is that this change is not worthwhile as-is. It would need a much more complete change description that described actual measurements of the improved performance (i.e. there needs to actually be a measurable improvement), documentation in the code as to why this extra complexity is worth it, and a clear description of how it was tested.

2023-12-30 21:45 UTC, XVhc6A commented on maps/biter_battles_v2/init.lua
> +	boss_unit.force_resync 'from_global'
This should be BossUnits?

2023-12-31 08:31 UTC, cogito123 commented on maps/biter_battles_v2/init.lua
> +	boss_unit.force_resync 'from_global'
tables() function is running only once when new surface is created. I'm not sure how it will help with desyncing between save/load. Global variables are serialized on save and deserialized on load. If you hold a reference to global variable in local variable outside a function, then during a load stage the address of global variable will become different. I think you meant to perhaps use https://lua-api.factorio.com/latest/classes/LuaBootstrap.html#on_load where it lists a use case to reinitialize local references to globals. I see that uitls/events.lua has some wrappers around those, you could experiment with that if there is a measurable difference in performance in this PR.

2024-03-13 18:16 UTC, closed without merging

2024-03-13 18:16 UTC, clifffrey commented
I'm closing this as there has been no response to my comment above. Feel free to reopen whenever it is ready.