revamp evo/threat calculation, and add /calc-feed command
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #438
Opened 2024-01-09 23:47 UTC by clifffrey

### Brief description of the changes:
This series of commits reworks how evo/threat increases are calculated to no longer iterate through the flasks one at a time. Additionally, it adds a command that allows users to see the expected evo/threat increase from a given send (defaulting to the contents of their inventories, but fully customizable).

Additionally, this adds the first (?) unit test support to the repository, allowing some functionality to be tested in a pure-lua environment (no factorio running).

I highly recommend reviewing this commit-by-commit, as most of the commits are no-ops in terms of behavioral changes.

I am very open to feedback about how the change should work, and the UI of the /calc-feed command itself.

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2024-01-11 16:03 UTC, clifffrey commented
Converting to draft because I realized I can make a major simplification to the evo calculation logic.

2024-01-11 17:46 UTC, clifffrey commented
ok, the new logic is much much much simpler (it ends up being just a few lines of code). The diff still looks large, because I moved a few functions between files, but if you review commit-by-commit, it should be straightforward to understand that the changes are actually quite small (other than the new command that I added, it is still a bunch of code)

2024-02-16 03:50 UTC, amannm commented
when the diff has lots of contiguous green, I suggest extracting the new functionality into a separate file instead of growing `functions.lua` tech debt

2024-02-26 05:01 UTC, clifffrey commented
> when the diff has lots of contiguous green, I suggest extracting the new functionality into a separate file instead of growing `functions.lua` tech debt

Many people have different opinions about how many files should be in a repository, and what the average file size should be. If others agree, I am happy to add a `feeding_util.lua` or `feeding_functions.lua` or `feeding_calculation.lua` file that contains the lines added to `functions.lua`

2024-03-06 20:03 UTC, XVhc6A approved these changes
I looked over this a bunch and overall I think this is a great addition.  I also tested this in a solo game

my only 2 big suggestions are:
1. move the test-feeding.lua to a new directory tests
2. add ci so this is tested automatically:
https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/pull/445
you can just copy/paste the workflow yml  from there no need to keep commit

2024-03-06 20:11 UTC, XVhc6A commented on maps/biter_battles_v2/functions.lua
> +		force_to_send_to = "north"
is it possible to set "force_to_send_to" to your own force is training mode is on?

2024-03-06 20:19 UTC, XVhc6A commented
and I support moving the new functions.lua block to feeding_calculation.lua

2024-03-06 22:09 UTC, XVhc6A requested changes
~~Actually, I am not so sure this is 'correct enough'~~

~~However, it is likely something I am doing wrong, just need to reevaluate my script.~~

EDIT: Ok, figured it out, no problems anymore : )

If anyone wants to plot the results of this vs the old version, it seems pretty close. Of course I might have missed something but I tested 2 sets of flasks in game in both versions and it was within 1 evo

https://colab.research.google.com/github/Factorio-Biter-Battles/Factorio-Biter-Battles/blob/47b9728d04c0896f2609ebb8c18d952c2a21939c/cliff-plot-script.ipynb#scrollTo=NJSBvi8vcdon

runtime->run all

view plots at bottom

investigate further as you wish

![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/87399868/ab28c079-4ab5-43f1-b0ef-32663b5fcde3)

2024-03-06 22:57 UTC, XVhc6A approved these changes

2024-03-07 03:14 UTC, XVhc6A commented on maps/biter_battles_v2/functions.lua
> +		local diminishing_modifier = 1 / (0.2 + (e2 * 0.016))
```suggestion
	diminishing_modifier = 1 / (0.2 + (e2 * 0.016))
```

2024-03-07 03:15 UTC, XVhc6A commented on maps/biter_battles_v2/functions.lua
> +	local print_help = false
```suggestion
```

unused

2024-03-07 03:18 UTC, XVhc6A commented on maps/biter_battles_v2/functions.lua
> +	local difficulty = global_passed_in.difficulty_vote_value * 100
different everywhere, but i don't like the global_ prefix for non-global vars. suggest renaming it. unless you prefer to keep it.

2024-03-07 03:21 UTC, XVhc6A commented on maps/biter_battles_v2/functions.lua
>  function get_ammo_modifier(ammo_category)
```suggestion
local function get_ammo_modifier(ammo_category)
```

not your code but we should local these

2024-03-07 03:27 UTC, XVhc6A commented on maps/biter_battles_v2/functions.lua
> +				end
```suggestion
```

is  this repeated from above by mistake?

2024-03-07 03:32 UTC, XVhc6A commented on maps/biter_battles_v2/functions.lua
> +	local difficulty = global_passed_in.difficulty_vote_value * 100
would also be okay with you decomposing it to just pass in the 3 global vars that are used.

2024-03-07 03:42 UTC, XVhc6A commented on maps/biter_battles_v2/functions.lua
> +				player_count = tonumber(v)
```suggestion
				player_count = math.floor(tonumber(v))
```
should be an integer.

2024-03-07 03:46 UTC, XVhc6A commented on maps/biter_battles_v2/functions.lua
> +function Public.calc_send_command(params, global_passed_in, player_count, player)
```suggestion
---@param params string
---@param global_passed_in any
---@param player_count int
---@param player LuaPlayer|nil
---@return string
function Public.calc_send_command(params, global_passed_in, player_count, player)
```

If you use a language server, these annotations can be very helpful

2024-03-07 03:46 UTC, XVhc6A commented on test-feeding.lua
> +	print("test_calc_send")
```suggestion
```

2024-03-07 05:36 UTC, clifffrey commented on maps/biter_battles_v2/functions.lua
> +		force_to_send_to = "north"
Yes! Good point. Done.

2024-03-07 05:37 UTC, clifffrey commented on maps/biter_battles_v2/functions.lua
> +		local diminishing_modifier = 1 / (0.2 + (e2 * 0.016))
I'm leaving this one because I think that it is less confusing (like, using "local" twice isn't really necessary, but given that I don't want the value of the variable to outlive its scope, "local" is a clear way of announcing that).

2024-03-07 05:37 UTC, clifffrey commented on maps/biter_battles_v2/functions.lua
> +	local print_help = false
done

2024-03-07 05:37 UTC, clifffrey commented on maps/biter_battles_v2/functions.lua
> +	local difficulty = global_passed_in.difficulty_vote_value * 100
I removed the param and replaced it with 4 params.

2024-03-07 05:38 UTC, clifffrey commented on maps/biter_battles_v2/functions.lua
> +				end
Yes, fixed.

2024-03-07 05:38 UTC, clifffrey commented on maps/biter_battles_v2/functions.lua
> +				player_count = tonumber(v)
Done.

2024-03-07 05:38 UTC, clifffrey commented on maps/biter_battles_v2/functions.lua
> +function Public.calc_send_command(params, global_passed_in, player_count, player)
Done (and added in another place or two).

I finally got a lua LSP working.

2024-03-07 05:38 UTC, clifffrey commented on test-feeding.lua
> +	print("test_calc_send")
Done

2024-03-07 05:39 UTC, clifffrey commented
Thank you so much for the very careful review. This substantially improved the code.

> 1. move the test-feeding.lua to a new directory tests

Done

> 2. add ci so this is tested automatically:
>    [add testing/ci to evo calc #445](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/pull/445)
>    you can just copy/paste the workflow yml  from there no need to keep commit

Done - and thank you! I do not yet have experience with github actions, so this is a great opportunity to learn about them.

Thank you also for doing the double-check that the numbers end up being essentially the same.


> and I support moving the new functions.lua block to feeding_calculation.lua

Done

2024-03-13 22:28 UTC, merged