Add a new tab displaying mutagen values and resource costs
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #443
Opened 2024-03-03 22:03 UTC by clifffrey

### Brief description of the changes:
Add a new tab displaying mutagen values and resource costs

I feel like this gives a lot of context for why sending higher-tier
sciences is worth more, and having this information available will
make new players learn the game faster. Note that I made some pretty
arbitrary decisions in the "cost" column. Specifically, which recipes
to assume the use of productivity modules for, and the relative cost
of each ore type and crude oil, as well as just blindly assuming that
all of the different petro/light/heavy oil are the same cost as
crude. That said, I think that this still gives a pretty accurate
picture of the costs/values of the different sciences.

Also, people have talked about potentially making a mode that slightly
randomizes the effectiveness of different sciences (or potentially
even randomizes what could be sent), and this tab would allow people
to decide what to throw in such a setting.

The function that I wrote to compute the raw resource cost of things
is slightly hacked together. Specifically, it won't be able to deal
with recipes that have multiple outputs very well. That said, I
believe that it works for the current science flask recipes fairly
well (just, if you have lots of mods enabled that add more complex
recipes, then this will not work I suspect).

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2024-03-06 23:02 UTC, XVhc6A requested changes
<img width="700" alt="image" src="https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/87399868/d617b559-6e0f-49d3-bfbb-8bf1e0a5fcf6">
<img width="696" alt="image" src="https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/87399868/44439460-f1e3-4cb6-bad1-b48ea6fbaccb">

if we're going to add this, the inner frame should be widened since it looks weird now.

2024-03-06 23:25 UTC, XVhc6A commented on maps/biter_battles_v2/feed_values_tab.lua
> +        print("No simple recipe for " .. product .. " assuming zero cost")
may want to use `log("xxx")` or `game.print("xxx")` instead of print

2024-03-06 23:25 UTC, XVhc6A commented on maps/biter_battles_v2/feed_values_tab.lua
> +    end
seems like you could condense this down?

2024-03-06 23:25 UTC, XVhc6A commented on maps/biter_battles_v2/feed_values_tab.lua
> +    end
might want to add global.bb_food_costs to the global table init function. just so it is kept track of.

Also, pass food_costs into this function as an argument, and do the global call outside to reduce the global data dependency.

2024-03-06 23:25 UTC, XVhc6A commented on maps/biter_battles_v2/sciencelogs_tab.lua
> +	local headersSummary = {"", table.unpack(global.science_logs_category_potion)}
👍

2024-03-06 23:25 UTC, XVhc6A commented on maps/biter_battles_v2/feed_values_tab.lua
> +    local raw_cost = 0
```suggestion
    raw_cost = 0
```

2024-03-06 23:25 UTC, XVhc6A commented on maps/biter_battles_v2/feed_values_tab.lua
> +local function add_feed_values(player, element)
player is unused

2024-03-06 23:25 UTC, XVhc6A commented on maps/biter_battles_v2/feed_values_tab.lua
> +function comfy_panel_get_active_frame(player)
```suggestion
local function comfy_panel_get_active_frame(player)
```

2024-03-06 23:25 UTC, XVhc6A commented on maps/biter_battles_v2/feed_values_tab.lua
> +local food_value_table_version = tables.food_value_table_version
```suggestion
local tables = require "maps.biter_battles_v2.tables"
local food_values = tables.food_values
local food_long_and_short = tables.food_long_and_short
```

lots of this is unused

2024-03-09 04:08 UTC, clifffrey commented on maps/biter_battles_v2/feed_values_tab.lua
> +        print("No simple recipe for " .. product .. " assuming zero cost")
switched to log(), thank you

2024-03-09 04:08 UTC, clifffrey commented on maps/biter_battles_v2/feed_values_tab.lua
> +    end
done

2024-03-09 04:08 UTC, clifffrey commented on maps/biter_battles_v2/feed_values_tab.lua
> +    end
hmm, it doesn't really need to be re-initialized every time that the map is reset though, so I'm not sure where to put something to make it better tracked.

I did change it to pass food_costs in to this function.

2024-03-09 04:08 UTC, clifffrey commented on maps/biter_battles_v2/feed_values_tab.lua
> +    local raw_cost = 0
Done

2024-03-09 04:09 UTC, clifffrey commented on maps/biter_battles_v2/feed_values_tab.lua
> +local function add_feed_values(player, element)
this is true.... but I think that maybe it is worthwhile to keep it because I think that the function/UI is actually created/stored per player, and this helps document that behavior.

2024-03-09 04:09 UTC, clifffrey commented on maps/biter_battles_v2/feed_values_tab.lua
> +function comfy_panel_get_active_frame(player)
Done

2024-03-09 04:09 UTC, clifffrey commented on maps/biter_battles_v2/feed_values_tab.lua
> +local food_value_table_version = tables.food_value_table_version
Done

2024-03-09 04:09 UTC, clifffrey commented
> if we're going to add this, the inner frame should be widened since it looks weird now. (see right side)

I agree that it looks slightly odd for admins... but most players are not admins, and for them it looks fine, so I'm inclined to leave as-is

2024-03-14 04:23 UTC, XVhc6A commented
okay, sounds good, I still approve then!

2024-03-14 18:10 UTC, clifffrey commented
FWIW, I added a bunch more code to this PR - There are now tooltips that give a lot more information about exactly what things cost. Also, the code tracks more than just the cost number, but actually tracks the number of intermediates, raw ores, and crafting time required.

2024-03-22 18:41 UTC, merged