add send_via_river special game
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #446
Opened 2024-03-08 20:18 UTC by XVhc6A

### Brief description of the changes:
Send your science via the inserters at the river!

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2024-03-31 08:29 UTC, gsquaredxc commented on comfy_panel/special_games/send_via_river.lua
> +-- local RUN_SPECIAL_NAME = "drbuttons-special-run"
Looks like this and line 10 to 14 are testing, and line 1 through 8 may not be needed.

2024-04-07 02:27 UTC, clifffrey requested changes

2024-04-07 02:27 UTC, clifffrey commented on comfy_panel/special_games/send_via_river.lua
> +		surface.request_to_generate_chunks(chunk_position, 5)
why 5?  why not the default of 0 (only generate this chunk)?

2024-04-07 02:27 UTC, clifffrey commented on comfy_panel/special_games/send_via_river.lua
> +	if surface.get_tile(entity.position.x, entity.position.y).collides_with("water-tile") then
reading the APIs, I wonder if you could perhaps simplify the logic by just unconditionally calling set_tile(water), set_tile(landfill).  The act of setting it to water would automatically remove colliding entities (which I guess might include the player entities), so maybe this is not a good/worthwhile idea.  I just wanted to throw it out as a brainstorm idea in case it sounded appealing to you.

2024-04-07 02:27 UTC, clifffrey commented on comfy_panel/special_games/send_via_river.lua
> +local science_packs = {
use Tables.food_names instead?

2024-04-07 02:27 UTC, clifffrey commented on comfy_panel/special_games/send_via_river.lua
> +local function get_random_player_from_force(force_name)
maybe outside the scope of this change, but it would be nice if we just changed the feeding logic to not require a player to be passed in, and then special games could just use that.  It would probably not be a hard change to make...

2024-04-07 02:27 UTC, clifffrey commented on comfy_panel/special_games/send_via_river.lua
> +				team_strings[enemy],
it would be more consistent to use the same messages, give or take, as feeding.lua does, i.e.

`" to ", Functions.team_name_with_color(enemy), "'s biters!"`

2024-04-07 02:27 UTC, clifffrey commented on comfy_panel/special_games/send_via_river.lua
> +					inventory.remove({ name = item_name, count = item_count })
can't you just directly use Feeding.lua:`Public.feed_biters` ? and delete a lot of this code?

2024-04-07 02:27 UTC, clifffrey commented on comfy_panel/special_games/send_via_river.lua
> +local function drbuttons_temporary_tick_handler(event)
perhaps rename to "send_via_river_" instead of "drbuttons_" ?

2024-04-07 02:27 UTC, clifffrey commented on comfy_panel/special_games/send_via_river.lua
> +	local disabled_food = {
again, it would be great to use Tables for this if you can

2024-04-09 18:49 UTC, XVhc6A commented on comfy_panel/special_games/send_via_river.lua
> +		surface.request_to_generate_chunks(chunk_position, 5)
I wasn't sure what to do here, I think it needs to be at least radius of 1 in case the placed entity is on the edge. But i don't know why I picked 5.  I will change it to 1.

2024-04-09 19:30 UTC, XVhc6A commented on comfy_panel/special_games/send_via_river.lua
> +	if surface.get_tile(entity.position.x, entity.position.y).collides_with("water-tile") then
I tried it out, I like it better. I can't remember what my original problem was here, but I think it had something to do with fish, so we'll just do it water->landfill every time now

2024-04-09 19:33 UTC, XVhc6A commented on comfy_panel/special_games/send_via_river.lua
> +local function get_random_player_from_force(force_name)
it definitely would be, but we can do that separately. I'll make a github issue.

2024-04-09 19:35 UTC, XVhc6A commented on comfy_panel/special_games/send_via_river.lua
> +local function get_random_player_from_force(force_name)
https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/issues/470

2025-01-20 02:07 UTC, clifffrey commented
Closing as no progress has been made in a long time

2025-01-20 02:07 UTC, closed without merging