Patch 1
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #467
Opened 2024-04-04 11:52 UTC by Moller21

### Brief description of the changes:

So a update to the previous healthbar text patch, because i've no idea how this github stuff works so i just made a new one.
I added option to hide the text, it's opt in. Changeable in the config window together with the notify on poll etc.

To answer rag's question i want to have it on on tick because the health text is more responsive when there's fewer bosses around and thats when you want it to be most responsive. It can update at maximum one healthbar per tick so i believe this is also a small  performance increase but not sure. And sorry for the space spam, not sure how to fix it.

And yeah, would probably be wise to test these changes :)

Earlier post:
Added text to the healthbar, heard worries about UPS but shouldn't be much impact, its only 1 text updated each second. 

https://cdn.discordapp.com/attachments/823771633021747210/1179497243036897380/image.png?ex=6579ff68&is=65678a68&hm=3c7ce440bfc6605fff1f85afb4fa7ab9fbd9fe4487c0d5535c4a928aa7460190&

### Tested Changes:
- [🍑] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2024-04-04 17:46 UTC, clifffrey requested changes
You need to fix the whitespace issues by using tabs instead of spaces.

I'd prefer if you reopened your old pull request #418 and made the changes there, so that the history is all in one place, but it is ok to leave here if you want.

2024-04-04 23:15 UTC, Moller21 commented
Any idea how i can fix this?

2024-04-05 02:30 UTC, clifffrey commented
> Any idea how i can fix this?

I'm not sure what you are asking about.  If it is tabs vs spaces, there are options in most editors. I am using VSCode, and it automatically did the right thing. What are you using to edit the code?

2024-04-05 18:09 UTC, Moller21 commented
> > Any idea how i can fix this?
> 
> I'm not sure what you are asking about. If it is tabs vs spaces, there are options in most editors. I am using VSCode, and it automatically did the right thing. What are you using to edit the code?

I use sublime text, and then copy the whole file into web brower. I'll try to figure it out somehow.
Can i undo a commit?

2024-04-05 20:09 UTC, clifffrey commented
> > > Any idea how i can fix this?
> > 
> > 
> > I'm not sure what you are asking about. If it is tabs vs spaces, there are options in most editors. I am using VSCode, and it automatically did the right thing. What are you using to edit the code?
> 
> I use sublime text, and then copy the whole file into web brower. I'll try to figure it out somehow. Can i undo a commit?

ok, you could try using a git client locally, but there are different ways of doing it.  Copying into a web browser should be ok too.

Yes, you can undo a commit, but it might be more straightforward to just make more commits with your fixes.

2024-04-06 16:18 UTC, Moller21 commented
Tada! Was pretty easy to figure out with the desktop app.

2024-04-07 04:12 UTC, clifffrey requested changes

2024-04-07 04:12 UTC, clifffrey commented on functions/boss_unit.lua
> +local healthbartext_playerlist
I am nervous that this needs to be stored in global.  Specifically, my read of https://wiki.factorio.com/Tutorial:Modding_tutorial/Gangsir#Multiplayer_and_desyncs implies to me that this might need to be stored in global, otherwise it might cause desyncs.  That said, I am not an expert in desyncs by any measure, so I might be wrong here.

2024-04-07 04:12 UTC, clifffrey commented on comfy_panel/config.lua
> +    ["bb_map_show_healthbar_numbers"] = function(event)
This should be using tabs to match the code around it

2024-04-07 04:12 UTC, clifffrey commented on comfy_panel/config.lua
> +        boss.healthbarnumbers_enable_for_player(player.name, event.element.switch_state == "left")
I think that you need this code to look much more like the `auto_hotbar_enabled` code.  Specifically, the fact that this is player-local state rather than global state has other consequences  (this also overlaps with my comment about `healthbar_playerlist` needing to be inside of `global` as well)

2024-04-07 12:26 UTC, Moller21 commented on functions/boss_unit.lua
> +event.add(defines.events.on_tick, on_tick)
If I use the nth tick, sure thats possible, but i believe its way to slow that way so you'd have to update, lets say, maybe 10 healthbars each tick. It's better to spread the load over more ticks than doing big chunks of them in a single tick.

2024-04-07 12:27 UTC, Moller21 commented on functions/boss_unit.lua
> +event.add(defines.events.on_tick, on_tick)
I'll see if I can do some test but no promise, its hard to test cause the other code uses on hit event.

2024-04-16 12:10 UTC, closed without merging