Add script and framework for benchmarking
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #469
Opened 2024-04-08 23:18 UTC by XVhc6A

To enable quick monitoring of changes to the core code, and mapping those changes to tangible timings, we can introduce the following code.

Workflow:
1. Modify the scenario to modify control.lua to require the benchmark code
2. Convert the scenario to a save
3. Run the benchmark on the new save

Notes:
  Consider: Disabling the profiler (comment out the line in benchmark.lua) and just looking at raw execute time.

### Brief description of the changes:

I need to look at this more to be sure it's all good, and to document it a little better.

### Tested Changes:
- [ x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2024-04-08 23:26 UTC, clifffrey requested changes

2024-04-08 23:26 UTC, clifffrey commented on benchmark.lua
> +			local bp_string =
Can you add a comment explaining what is in this blob?

2024-04-08 23:26 UTC, clifffrey commented on benchmark.sh
> +	echo "Usage: $0 <factorio data directory> <factorio executable> <scenario to benchmark directory>"
So, can we take a save from a big/slow captains game and easily run this against that save?  I guess it isn't clear to me what a "scenario to benchmark directory" is.

2024-04-09 03:44 UTC, XVhc6A commented on benchmark.sh
> +	echo "Usage: $0 <factorio data directory> <factorio executable> <scenario to benchmark directory>"
While you could technically take a real save, you cannot really modify the core code as all the global/function tables are 'pre-set', and definitely not anything with new/modified globals.  so for anything more in depth than a few line changes, you need to create the scenario save from scratch every time.

scenario to benchmark dir is just saying, create save starting from your development directory (I assume most develop outside of the factorio data directory)

2024-04-09 15:28 UTC, clifffrey requested changes
I'm very excited by this change!  I think that you will deserve a huge amount of credit for all of the performance improvements that follow. It is amazing how making something easily measurable allows people to improve that metric.

2024-04-09 15:28 UTC, clifffrey commented on server-settings.json
> +{
perhaps rename this to something like benchmark-server-settings.json?  Or move this to the benchmarking directory?

Otherwise, I worry that people could be confused by the presence of an additional server-settings.json file (and be unsure if somehow it is the setting that they would use when they load the scenario or something)

2024-04-09 15:28 UTC, clifffrey commented on benchmarking/main.lua
> +			-- local bp_string =
it would be great if these crazy bp strings could be put in their own file, and if there was at least a single line description along the lines of `-- a factorio blueprint that has lots of laser turrets/walls around the silo` or something

2024-04-09 16:16 UTC, XVhc6A commented on server-settings.json
> +{
I moved it into the benchmarking directory, but ping me again here if you think it should be renamed again.

2024-04-09 16:17 UTC, vadcx requested changes
I reviewed the Bash script. I can only recommend you to install VSCodium with Shellcheck to learn more about Shell and avoid tricky mistakes. I found it's a better teacher for Shell than most articles or books that will likely omit pitfalls.

2024-04-09 16:17 UTC, vadcx commented on benchmarking/run_benchmark.sh
> +	sed -i.bak "s|$old_text|$new_text|g" $CONTROL_FILE || exit 1
`"$CONTROL_FILE"` must be in double quotes

2024-04-09 16:17 UTC, vadcx commented on benchmarking/run_benchmark.sh
> +	new_text="require 'maps.biter_battles_v2.main'\nrequire 'benchmarking.main'"
I suggest adding it to the Lua code as a clearly visible injection point. Example

```lua
-- set to true by Shell script or manually
local BENCHMARKING_ENABLED = false
if BENCHMARKING_ENABLED then
-- require here
end
```

PS: You may have just pushed that change, I am not sure?

2024-04-09 16:17 UTC, vadcx commented on benchmarking/run_benchmark.sh
> +	SAVE_FACTORIO_DATA_PATH="${FACTORIO_DATA_DIR}"/saves/"${HARDCODED_PRIMED_SCENARIO_NAME}".zip
You can simplify this quoting: `"${FACTORIO_DATA_DIR}"/saves/"${HARDCODED_PRIMED_SCENARIO_NAME}".zip` to `"${FACTORIO_DATA_DIR}/saves/${HARDCODED_PRIMED_SCENARIO_NAME}.zip"` - just quote the entire string once. `${...}` does the job already.

Below one more line llike this.

2024-04-09 16:17 UTC, vadcx commented on benchmarking/run_benchmark.sh
> +			break
There should be a sleep after the second graceful kill before `break`, otherwise it sends a graceful kill immediately followed by `kill -9`

2024-04-09 16:17 UTC, vadcx commented on benchmarking/run_benchmark.sh
> +#!/bin/bash
`#!/usr/bin/env bash` is the recommended and well supported shebang

2024-04-09 16:19 UTC, XVhc6A commented on benchmarking/main.lua
> +			-- local bp_string =
Yea,  I thought about writing a script to make it from scratch, but this seemed way faster to do, so for now I'll at least move this into a separate file.

2024-04-09 16:21 UTC, XVhc6A commented on benchmarking/run_benchmark.sh
> +	new_text="require 'maps.biter_battles_v2.main'\nrequire 'benchmarking.main'"
That looks much better than sed : )

2024-04-09 17:36 UTC, XVhc6A commented
@clifffrey @vadcx 
Thank you for your comments.
I've updated the code and you can view the diff here:

https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/compare/b564a216ab7e69198c375dbafb62cd01f2d08c61..0fd00c1aa4701f2c4f23d894d08d5ca6e7258191

2024-04-09 21:55 UTC, clifffrey approved these changes

2024-04-09 21:55 UTC, merged