Add code support for feeding without specifying player
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #471
Opened 2024-04-09 21:33 UTC by clifffrey

This is to help special games where feeding happens without a specific player doing it.  The no-player-specified codepaths are currently unused and untested.

This is intended to fix issue #470

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2024-04-11 19:43 UTC, XVhc6A requested changes
looks good, but the set_evo_and_threat in other files needs to be updated

2024-04-11 19:43 UTC, XVhc6A commented on maps/biter_battles_v2/feeding.lua
> +function Public.do_raw_feed(flask_amount, food, biter_force_name)
this was a global and is used in `maps/biter_battles_v2/ai.lua` 

I'm not sure if that is / was intentional to avoid circular dependency or by accident

2024-04-12 16:01 UTC, clifffrey commented
ok, now I updated the benchmarking code as well, so I believe that this is ready for your approval.

2024-04-12 19:53 UTC, XVhc6A approved these changes
lgtm

2024-04-12 21:21 UTC, merged