New/faster/more-predictable revive mechanics
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #472
Opened 2024-04-10 04:39 UTC by clifffrey

Real description to be done later, look at commit descriptions for details now

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2024-04-12 07:51 UTC, RedRafe commented on functions/boss_unit.lua
>  	end
I've tested this behavior. `LuaEntity::health` [docs](https://lua-api.factorio.com/latest/classes/LuaEntity.html#health) is always clamped between [0, max_proto_health]. It would be maybe more clear & faster if we rely on the event filter:
setting `on_entity_damaged` with filter `health = 0` (instead of `<=`, since health cannot be less than 0 to clear any doubt). And then, in the handler, skipping the check for the health value (since that is already done on the C++ side of the API and thus it's valid), removing the while loop (since we already know the final health should be the max), and simply do:

```lua
[...]
if not unit then return end

entity.health = entity.prototype.max_health
unit.revive_count = unit.revive_count - 1

if unit.healthbar_id then
    ...
  -- break // no need to do 'break' since there's no while loop anymore
    ...
end
```

Here's the benchmarking result (not any statistical performance gain, but proof that the behaviour remains unchanged):

> Old behavior
```
 4.742 Checksum
13.851 Goodbye
Time = 9.109
(valid) calls to handler: 1501
``` 

> New behavior
```
 4.669 Checksum
13.718 Goodbye
Time = 9.040
(valid) calls to handler: 1501
```

2024-04-12 07:51 UTC, RedRafe commented on functions/boss_unit.lua
> +	{{filter = "type", type = "unit"}, {filter = "final-health", comparison = "<=", value = 0, mode = "and"}})
use `=` instead of `<=`

2024-04-12 15:33 UTC, RedRafe commented on functions/boss_unit.lua
> +	if global.bb_draw_revive_count_text then
It appears that `global.bb_draw_revive_count_text` is never initialized in 'init.lua` with all other globals, consider giving it a starting value to make it explicit that is by default `false`

2024-04-12 16:17 UTC, clifffrey commented on functions/boss_unit.lua
>  	end
Awesome!  Thank you for running that test.  I made all of the changes that you suggested, except I am still re-checking that the health == 0, just because in the future, perhaps the filter will be changed to handle other code cases too.  But, I agree that there is a tiny performance win potential here. And it is ok with me if someone wants to make that change later on.

2024-04-12 16:17 UTC, clifffrey commented on functions/boss_unit.lua
> +	if global.bb_draw_revive_count_text then
Done  (to the part of init.lua that only runs once, rather than on every map reset).

2024-04-12 16:17 UTC, clifffrey commented on functions/boss_unit.lua
> +	{{filter = "type", type = "unit"}, {filter = "final-health", comparison = "<=", value = 0, mode = "and"}})
Done

2024-04-12 16:31 UTC, RedRafe commented
Just one minor consideration for the whole refactor of the revive mechanic, since we're at it.
With these changes, the `revive_count` is treated as `int`, but there are no checks in place in case any floating point appears. Since we're already refactoring it, to make it more robust for future updates, we could either:

1. add some validations for the `revive_count`, at least before passing it to the `rendering` to draw the text, to make sure code is handling those floats as int in the right way

-- or --

2. add a bit of logic to support floating `revive_count` (which could become handy in the `ai.lua` part). Basically add one more step when setting the health (`entity.health = (revive_count < 1 and revive_count or 1) * max_proto_health`) and just `math.floor(`revive_count`) before passing it to the renders logic (which would still be done if sanitizing to int). That way, we could support `23.5` revive counts or, if needed in the future, reanimate entities with certain health

2024-04-12 17:43 UTC, XVhc6A requested changes
looks like you updated something but going to submit this review since i don't know what clicking refresh does

2024-04-12 17:45 UTC, XVhc6A commented
> Just one minor consideration for the whole refactor of the revive mechanic, since we're at it. With these changes, the `revive_count` is treated as `int`, 

I think adding typing is good enough here, the language server will warn us if we don't pass integers.  I don't see any utility in having half a revive.

2024-04-12 17:49 UTC, XVhc6A commented
I think that overall that this is fine, but I think in a follow up PR I should further update the benchmarking script to be a little more scientific.  Once this is merged I will work on that.  I'm imagining that we can just use lab tiles and just have a bunch of biters spawn in front of a horizontal line of tests. with 1:1 threat equivalents of each implementaiton.

2024-04-12 19:00 UTC, clifffrey commented on benchmarking/main.lua
>  			---At this point we have a save 'abcdefg' which is loaded at or
Done

2024-04-12 19:01 UTC, clifffrey commented on benchmarking/main.lua
> +			log("total threat consumed: " .. (high_threat_value - global.bb_threat["north_biters"]))
Done (although more could be done in this space...)

2024-04-12 19:01 UTC, clifffrey commented on benchmarking/run_benchmark.sh
> +	echo "done"
done

2024-04-12 19:01 UTC, clifffrey commented on benchmarking/run_benchmark.sh
> +	echo done2
Done

2024-04-12 19:01 UTC, clifffrey commented on benchmarking/run_benchmark.sh
> +	#mv "$SAVE_FACTORIO_DATA_PATH" .trash/ || exit 1
I feel like leaving the one save with the obvious name is fine.

I also feel like we should change the scenario name from randomly-generated to static (and more obvious).  Otherwise, I keep hitting ctrl-c when running, and I have all of these random scenarios that I haven't cleaned up yet.  But yeah, I think that a bunch of improvements could be made in this space... I'm leaving some of them for the future for now though.

2024-04-12 19:01 UTC, clifffrey commented on functions/biter_raffle.lua
>  local math_floor = math.floor
So, I am conflicted.

On the whole, we should really just use math.random() whenever/wherever.  For testing my one specific change, it was important that these used independent random generators because otherwise I was getting completely different attack waves, and it made the benchmark results worthless.

Replacing each random generator with global.random_generator doesn't really help in the general case, because then if you change any place that uses global.random_generator, it'll screw up the benchmark reproducibility. That is the advantage to using many different random generators.... then when you add a call to random somewhere, it only messes up other random numbers that are "nearby".

I think that for now, I'll just completely revert my change, because even though it was important/useful for testing my change, it maybe shouldn't be here long-term.

2024-04-12 19:04 UTC, clifffrey commented on functions/boss_unit.lua
> +---@param revive_count integer
I reworked a bunch of this

2024-04-12 19:04 UTC, clifffrey commented on functions/boss_unit.lua
>  local Public = {}
I did at least some of this.... the change to init.lua didn't make errors automatically show up, I had to add additional `@type` annotations to the code here as well, which I did.

2024-04-12 19:04 UTC, clifffrey commented on functions/boss_unit.lua
> +		unit.revive_count = unit.revive_count - 1
I already reworked this based on RedRafe's feedback. I incorrectly thought that health could go negative if units were overkilled.

2024-04-12 19:04 UTC, clifffrey commented on maps/biter_battles_v2/ai.lua
> +end
hmm, I'm going to leave this, as lots of places would break if `reanim_chance` was set to 100+.  Also, I want to change `reanim_chance` to `health_factor` in a future change, so hopefully this code is short-lived.

2024-04-12 19:04 UTC, clifffrey commented on maps/biter_battles_v2/ai.lua
> +Event.add(defines.events.on_entity_spawned, on_entity_spawned)
I'm inclined to leave it where it is.

2024-04-14 03:48 UTC, clifffrey commented
> 2. add a bit of logic to support floating `revive_count` (which could become handy in the `ai.lua` part). Basically add one more step when setting the health (`entity.health = (revive_count < 1 and revive_count or 1) * max_proto_health`) and just `math.floor(revive_count)` before passing it to the renders logic (which would still be done if sanitizing to int). That way, we could support `23.5` revive counts or, if needed in the future, reanimate entities with certain health

I think that this is a great idea, and I implemented it.  This just makes it a `health_factor` rather than a `revive_count`, which is much simpler I think.

2024-04-14 06:44 UTC, RedRafe commented on functions/boss_unit.lua
> +	else
I would say we simply don't add any renders with anything with life in range [0,1] since there would be units with text and units without text at same true health value.

2024-04-14 06:50 UTC, RedRafe commented
I think it's great you implemented the floating point feature. And it's not particularly relevant for the player since there's an arrogant `math.floor` which truncates the value and simply displays it as int. Simple to understand for the player, helpful to us. 

Just curious of we should even add text renders when health becomes <1 (as there may be units with renders and units without them, at same health value) which could create confusion, and simply "let the unit free" once it's healt factor becomes regular [0,1] (except bosses, obviously). Overall, highly approve these changes.

2024-04-15 21:26 UTC, XVhc6A commented on functions/boss_unit.lua
> +	end
So, if this is to be tested, an admin needs to run `/c global.bb_draw_health_factor_text=true` ?

2024-04-15 22:18 UTC, XVhc6A commented on functions/boss_unit.lua
> +	{{filter = "type", type = "unit"}, {filter = "final-health", comparison = "=", value = 0, mode = "and"}})
I'm ok with this, but I wonder if we should add a shim in utils.event to block adding any defines.events.on_entity_damaged events, since they would overwrite eachother?

2024-04-15 22:57 UTC, clifffrey commented on functions/boss_unit.lua
> +	end
yeah. I thought that it looks too ugly to have on all the time, but it is useful when debugging.

2024-04-15 22:59 UTC, clifffrey commented on maps/biter_battles_v2/ai.lua
>  		end
I think that that is a really good idea. That said, it is outside the scope of this one change.

I think that we might want to go even farther, and actually keep track of the total amount of outstanding threat/biters, and we could use that to prevent us from spawning more biters (and potentially causing threat to go negative when/if they are all killed).  But, again, none of this is in scope for this current change.

2024-04-15 23:07 UTC, clifffrey commented
> I think it's great you implemented the floating point feature. And it's not particularly relevant for the player since there's an arrogant `math.floor` which truncates the value and simply displays it as int. Simple to understand for the player, helpful to us.
> 
> Just curious of we should even add text renders when health becomes <1 (as there may be units with renders and units without them, at same health value) which could create confusion, and simply "let the unit free" once it's healt factor becomes regular [0,1] (except bosses, obviously). Overall, highly approve these changes.

The text that is rendered is just the "additional health, beyond the current health of the biter" that remains.  So any biter with no bonus health will not have a number displayed at all.  I agree that numbers < 1 are confusing.  In general, the numbers seem confusing no matter how we slice it though (and they are off by default for a reason!).  In all cases, we "let the unit free" once we are done adding any bonus health.

2024-04-15 23:10 UTC, XVhc6A commented on functions/boss_unit.lua
> +	end
Edit, I realize what I was doing wrong here now, nevermind.

2024-04-15 23:59 UTC, clifffrey commented on functions/boss_unit.lua
> +	{{filter = "type", type = "unit"}, {filter = "final-health", comparison = "=", value = 0, mode = "and"}})
Done

2024-04-16 00:19 UTC, XVhc6A approved these changes
looks good lets give it a shot!

2024-04-16 17:08 UTC, merged