no_turret_creep performance fix
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #479
Opened 2024-04-18 01:39 UTC by vadcx

### Brief description of the changes:
Fixes #478 

> Optimizes the function by limiting the search output to only 1 entity of
type spawner.
>Previously the code restricted spawners to a circular area of 64 tiles,
now it is 64 square tiles on any axis. This is a slight change in
behavior.

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

---

Idk, is there no other way to only register commands for local testing? Because I registered the test command along with other commands.

Remember when testing you must be quite far from spawn, even further than the teleport moves you to get inside the "biter area" where building too close to spawners is prohibited. And the angle really applies, so if you travel too far west/east, you must go further out to stay in the biter area.

2024-04-18 03:01 UTC, clifffrey requested changes

2024-04-18 03:01 UTC, clifffrey commented on maps/biter_battles_v2/functions.lua
> +		limit = 1,
wait, I am confused by this change, and the underlying issue.  I think that I misunderstood the original issue (I thought that it was searching through all spawners on the surface instead of all within a given square)

According to the profile you took:
```
741x "no_turret_creep" in "...mp/currently-playing/maps/biter_battles_v2/functions.lua", line 293. Total Duration: 33.750242ms
    1701x C function "__index". Total Duration: 7.754077ms
    63x "is_biter_area" in "...mp/currently-playing/maps/biter_battles_v2/functions.lua", line 279. Total Duration: 0.646451ms
        63x C function "math_abs". Total Duration: 0.178611ms
    26x C function "find_entities_filtered". Total Duration: 16.538527ms
```

I think that this means that during the minute of your profile, 741 entities were placed, 63 of them were turrets (i.e. were on `no_turret_blacklist`).

The 1701x calls to `__index` are perhaps largely for field access, i.e. `event.created_entity` might be one `__index`, and thus those calls to `__index` are even before the call to `no_turret_blacklist`.  I am not certain about any of that, but I don't really see any reason to suspect that a lot of spawners were returned (even if they were, I don't think that iterating through `pairs` would look like a call to `__index`). Thus, I don't actually think that this change will improve performance in any measurable way.

I think that it is very rare that a turret is placed and there are spawners within the square-of-70, but not within the circle-of-radius-64.

2024-04-18 13:11 UTC, vadcx commented on maps/biter_battles_v2/functions.lua
> +	-- sic! this does not affect the direct indexation values below somehow
The assignments below **do** modify the returned table and the function call works correctly with shifted coordinates.

However I tried to "reset" posEntity modifications below with literal `posEntity = entity.position` to avoid entity.position.x lookups. To my surprise, that returned the same modified table and not a new one. Well I didn't check the table pointer, but the position values were other than event.position.x/y. In short:

```lua
local posEntity = entity.position
posEntity.x = posEntity.x + 500
game.print(posEntity.x) -- +500
posEntity = entity.position -- I would expect original values
game.print(posEntity.x) -- +500
game.print(entity.position.x) -- original
```

This is from in-game testing, I didn't actually run this snippet. This is probably an optimization on Factorio's end, but it goes against the expectations of interacting with Lua tables. Although all this direct index access is elegant in some way, this gotta be the one case where it's dangerously misleading.

2024-04-18 13:19 UTC, vadcx commented on maps/biter_battles_v2/functions.lua
> +		limit = 1,
Dang, you are right. The cost of this call must not come from the amount of spawners in range, but the total entities in proximity the game has to iterate and filter internally. I was too fixated on just this call...

https://lua-api.factorio.com/latest/classes/LuaSurface.html#find_entities_filtered

Looking again at the API I wonder if the two flags would be better performance-wise if the game has any optimizations in place? Military target seems most likely to have been specifically optimized for this kind of lookups. But here I would need to come up with a complex test first involving many player entities + spawners to confirm performance benefits.

- force 	:: ForceIdentification or array[ForceIdentification]?	
- is_military_target 	:: boolean?

I forgot to upload the screenshot yesterday, the range of 70 was chosen out of caution. Because the sqrt(4096) from below still limits to only 64 tiles. Anyway, now we can go back to position+radius filter parameters for exactly the same behavior as before. I had chosen the square because of my misunderstanding where the problem lies.

![no-turret-creep4](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/129969897/5cf79bb4-95b7-4e7a-8b8c-f4b21bde3e2a)

2024-04-18 19:01 UTC, clifffrey commented on maps/biter_battles_v2/functions.lua
> +		limit = 1,
yeah, I think that you are right that this would require performance testing.  I agree that using `force` and `radius` might improve performance, but it is hard to know (and it is possible that they won't improve performance).

2024-04-27 03:16 UTC, clifffrey commented
As is, you could at least just change this to directly use position/radius instead of area+calculate-in-lua, and then it could have `limit=1` set as well.  This would at least simplify the code, even if the performance is likely not all that different.

2024-05-20 17:43 UTC, clifffrey commented
closing due to inactivity, feel free to reopen

2024-05-20 17:43 UTC, closed without merging