Speed up at_targets random target selection
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #480
Opened 2024-04-18 04:30 UTC by clifffrey

Specifically, by doing a bit more work when we start/stop tracking units, we can get constant-time-indexing support for fast random building selection.

This was reported in issue #476 as something that can slow down large captains games.

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2024-04-18 14:01 UTC, vadcx approved these changes

2024-04-18 14:01 UTC, vadcx commented on maps/biter_battles_v2/ai_targets.lua
> +        if not first_entity or not second_entity then break end
Looks good. I only noticed there exists the edge case if only one valid entity was rolled, no targets will be added. But according to comment in `simple_valid_random_sample` this should be very rare.

2024-04-20 03:27 UTC, clifffrey commented on maps/biter_battles_v2/ai_targets.lua
> +        if not first_entity or not second_entity then break end
ok, in part due to this comment, I spent time learning about the cases where the LuaEntity might not be valid, and found all sorts of surprising behavior (nothing severe, just surprising), and was inspired to redo much of my change in a way that I think really simplifies it.

I'd love it if you could take another look at the changes.

2024-04-20 05:14 UTC, vadcx requested changes
I didn't review greater logic as well as I did last time :) It's a great idea to use this other event for tracking

EDIT/PS: Code readability suffers as elsewhere, I'd have moved more code chunks to functions with understandable names.

2024-04-20 05:14 UTC, vadcx commented on maps/biter_battles_v2/ai_targets.lua
> +    end
2nd entity can be nil then it will try to access its (nil) position. If you want a fallback then... huh that can be simplified:

```lua
    local first_entity = simple_random_sample(available_list)
    if not first_entity then return nil end
    local second_entity = simple_random_sample(available_list) or first_entity

    local first = first_entity.position
    local second = second_entity.position
    if origin_distance(first) < origin_distance(second) then
        return first
    else
        return second
    end
```

2024-04-20 05:14 UTC, vadcx commented on maps/biter_battles_v2/game_over.lua
> +	AiTargets.start_tracking(entity)
same as above, I believe we should use raise_event in create_entity rather than explicit manual tracking

2024-04-21 02:51 UTC, clifffrey commented on maps/biter_battles_v2/ai_targets.lua
> +    end
in practice, I think that it is impossible for one to return nil without the other being nil as well (and it seems unlikely that it'll actually ever be nil), so I'm happy with how I have the logic already.

2024-04-21 02:54 UTC, clifffrey commented on maps/biter_battles_v2/game_over.lua
> +	AiTargets.start_tracking(entity)
hmm, the code has many calls to `create_entity`, and essentially only the rocket silo one (and the clone-of-the-rocket-silo) has any impact for `start_tracking`....

Anyhow, you might be right, but even if so, I'd rather that this be done in a separate change, and I don't think that I'm going to make it (but I'm ok if someone else wants to make the change).

2024-04-21 02:55 UTC, clifffrey commented on benchmarking/main.lua
> +			AiTargets.start_tracking(entity)
currently `raise_built` is unused, and same for `script_raised_built`.

As I mention in my other comment, I'm ok if someone else wants to make this change, and I'm not inclined to make it right now.

2024-04-21 03:07 UTC, clifffrey commented on maps/biter_battles_v2/ai_targets.lua
> +            end
Moved, thank you

2024-04-21 03:07 UTC, clifffrey commented on maps/biter_battles_v2/ai_targets.lua
> +    map[unit_number] = nil
yes!  Good catch!

2024-04-21 03:17 UTC, clifffrey commented
> EDIT/PS: Code readability suffers as elsewhere, I'd have moved more code chunks to functions with understandable names.

ok, I renamed one function to something at least slightly better as well.

I will wait for your approval before submitting.

2024-04-21 03:22 UTC, vadcx commented
> I will wait for your approval before submitting.

[do it](https://i.ytimg.com/vi/C3y6SsGAWks/sddefault.jpg)

2024-04-21 03:23 UTC, vadcx approved these changes
I forgot I have to type do it in this window.

2024-04-21 22:37 UTC, merged