Make player always 'trusted' in singleplayer
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #485
Opened 2024-04-18 19:16 UTC by vadcx

Note this does NOT affect multiplayer even if hosted yourself. In singleplayer you will now be trusted + game admin, but hosting multiplayer you are game admin but NOT trusted due to play time.

This allows to use the profiler immediately in a new singleplayer game.

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2024-04-19 16:14 UTC, clifffrey requested changes

2024-04-19 16:14 UTC, clifffrey commented on utils/datastore/session_data.lua
> +setmetatable(trusted, {__index = function()
I will say that this change makes me nervous, but maybe I am crazy for being nervous about it.

I have almost no lua experience, which is probably part of it.  For instance, when I read https://lua-api.factorio.com/latest/auxiliary/global.html and look at this code, it is not at all clear to me if the metatable will survive or not if the game is saved/loaded.  Also, it is not clear to me how often the `trusted` table is accessed, and if there are performance impacts from this change.

Thus, I wonder if a simpler option is possible? For instance, could we instead do an insert inside of an `on_player_joined_game` event?  Or even just from the init.lua code somewhere?

2024-04-20 05:17 UTC, vadcx commented on utils/datastore/session_data.lua
> +setmetatable(trusted, {__index = function()
__index only works as a fallthrough, so if a player had the value assigned explicitly it would stay there. Think of it as a _potential_ 2nd lookup. However trusted is used throughout the codebase.

My intention for not going with persistence was two-fold: don't affect multiplayer unless necessary and it doesn't (although being game admin SHOULD be giving trusted permissions if we consider hierarchy); be dead simple there.

I didn't know about metatables [register_metatable](https://lua-api.factorio.com/latest/classes/LuaBootstrap.html#register_metatable) but it's not like I would've cared much in this instance. Still it's surprising to me, but if Factorio doesn't serialize metatables maybe it'll need to load the entire file from scratch anyway to reload the functions to memory.

I will read about it and try the join/load approach. I heard that loading a save doesn't call the usual join event, because to the game you never left and it continues.

2024-04-21 03:20 UTC, clifffrey commented on utils/datastore/session_data.lua
> +setmetatable(trusted, {__index = function()
For what it is worth, I wouldn't be too afraid of changing the code, even if it potentially impacts how multiplayer works.  It is ok for us to change things, as long as we can test/etc.

2024-04-21 22:43 UTC, clifffrey commented
also, vadcx@, can you let me know who you are in discord/in-game?  Feel free to just privately message me if you do not want it to be public.

2024-04-21 22:49 UTC, vadcx commented
@clifffrey same as here, I cannot chat in Discord due to the phone verification requirement I refuse with Discord based on [their roots](https://en.wikipedia.org/wiki/OpenFeint#History).

2024-04-22 02:02 UTC, vadcx commented
Content warning: prepare a lot of tea. LOL

Thanks for "RTFMing" me with the links above :) now that I had to face and read them I decided to write down this treatise of what I understand now of Factorio's save-load system, desyncs and the decisions that led there. Maybe I will put it down as its own wiki article one day.

Recommended reading order:

- https://lua-api.factorio.com/latest/auxiliary/global.html - Factorio's `global` should've been renamed `persist`
- https://lua-api.factorio.com/latest/auxiliary/libraries.html
- Gangsir's modding & desync tutorial https://wiki.factorio.com/Tutorial:Modding_tutorial/Gangsir

That's all for now. I assume people reading understand the determinism and the lockstep networking architecture.

If you have spent a lot of time in pure Lua, you would expect all the handy-dandy properties of dynamic typing and functions being first-class values. Much like JavaScript. Ask a table about key MYFUNC and get that function in return or a table that acts like a function due to `__call` metatable :)

The foundational decision by Factorio devs was to use the standard Lua aka PUC-Rio Lua. This means admitting to its shortcomings and long-standing limitations like [load](https://www.lua.org/manual/5.2/manual.html#pdf-load) that provides no guarantees about safety when loading bytecode directly.

For security reasons, the result is that Factorio will never try to serialize functions or code of the Lua Virtual Machive (VM). Although it would have been cool if the entire Lua VM state were saved/transferred/restored exactly as it was before. This would completely eliminate desync issues on our (modders) side due to improper save handling. Yet this would allow the loophole of deserializing untrusted code... and there goes the security... *Even if there are examples of other VM implementations that allow this. Altough maybe in a non-portable way.*

---

If we are not allowed to serialize functions, it makes sense to erase metatables completely too, because they are mostly made of custom callback functions. Following to these constraints leaves us with the current Factorio architecture:

- All Lua code is plain text Lua.
- No functions/metatables will be saved to meet the constraints
- Only **data state** is saved and restored for game saves (and multiplayer that uses game saves under the hood)
- Lua's data persistence in game saves is achieved by only serializing the special `global` Factorio table
- Factorio's internal data is restored from the save game, data needed for Lua scripts is restored by recreating the `global` table as it was before the save game
- Lua code is loaded afresh from the included script files (be it mods or scenario scripts)
- Lua code makes sure to re-register metatables when its code loads, because they were erased, even for tables inside `global`

If it helps, think of Factorio's save system as OS hibernation. You have all the same code on disk, but must pay attention to load previously saved stuff from pagefile into memory so it appears seamless.

_The high level explanation of a desync in Factorio is that you forgot to sneak through data in `global` between current players and players loading from code + save data._ There are no other causes, because Factorio devs deliberately limit you in what you can do or reach from within Lua. That's why there's no *asymmetrical* I/O in Factorio where you would load a file on one player's computer or the server. It's a decision to limit the "desync surface" so to say.

And because Factorio does not go out of its way to serialize the Lua VM state, you only get the data stored in `global`, which is serialized between saves; all your local and "Lua global" and upvalue variables be damned (poof, gone)!

Read [Gangsir's desync chapter](https://wiki.factorio.com/Tutorial:Modding_tutorial/Gangsir#Multiplayer_and_desyncs) again and the previous paragraphs if needed.

---

Only now does it make sense to read the more advanced articles:

- https://lua-api.factorio.com/latest/auxiliary/data-lifecycle.html
- https://wiki.factorio.com/Desynchronization

It should make sense now why the "Heavy mode" of desync troubleshooting is there. The desyncs between players can only happen if you can't restore (current state) from (persistent save data + script files)\*. The only other culprit is Factorio itself introducing desyncs, but that's not **our** problem.

\* data-lifecycle article, "on_load()" section

---

I hope you can now understand and explain Gangsir's desync examples:

1. **Using local variables.** When a player loads (save data + script files), he starts with values from code. If you intend on using them, they must be loaded/overloaded from `global` persistence table.
    - Just consider all data coming from script files immutable and values from `global` must be overlayed on top. (Linux examples: OverlayFS, Docker, Fedora Silverblue, SteamOS.)
2. **Conditional event subscribing.** When your (save data + script file) loads, it must know if it needs to subscribe to an event from before by checking **your** saved variable in `global` persistence table. If you didn't save it in global, the newly joined player has no idea that event must have been subscribed to!
3. **Improper use of on_load.** Carefully read the data-lifecycle, the warnings and don't do anything crazy except trying to load the saved state from `global` to restore from "hibernation".
4. **Comparison by reference.** This is very tricky, because that's exactly what makes Lua so easy to use. Even if functions are now out of the way (not saved-restored), there are still Lua tables and objects that came from Factorio's API. The tutorial says:

> Be cautious of comparing tables by reference. In multiplayer syncing, tables deserialized from the server state will be new objects, not equal by reference to any table initialized by client code.
> `if a == b then` and `if a ~= b then`

... they may have different results if `a` came from loading script file code and `b` came from deserialization (save file).

> Note that [LuaObjects](https://lua-api.factorio.com/latest/builtin-types.html#LuaObject) provided by the game have their equality operator overwritten to prevent this behaviour, so code such as `LuaEntityA ~= LuaEntityB` will not desync. However, this does not apply when LuaObjects are used as keys in tables:

> `if table[LuaObject] then`

> This will desync in the same way as described for the plain tables a and b above. For entities it is recommended to use [LuaEntity.unit_number](https://lua-api.factorio.com/latest/LuaEntity.html#LuaEntity.unit_number) as the table key instead of the whole entity.

Lua's tables and game's objects are pretty much C pointers. They can't be restored between save & load. The game tries to help when it comes to the equality operator of LuaObject, but when it is used as table keys you happen to rely on the pointer address that will never be the same between save and after load.

**Remember:**

When loading from save/joining multiplayer:

`global[ FactorioGameObject ] = someValue` will not be found after loading --> desync.

The following will work after loading because the `serpent` library takes care of it across serializations (only for all _regular Lua objects_ in `global`):

```
global.savedLuaTable = {"I am a SavedLuaTable"}

-- times passes, empires fall, you join the game:
local persistedTable = global.savedLuaTable
global[ persistedTable ] = LuaValue
```

Next example will not work because when loading code, Lua is blissfully unaware and creates new tables:

```
local freshTable = require("make-me-a-table")
return global[ freshTable ] -- NOT FOUND, new object used as key here -> desync

--- in contrast, save it under a permanent string key:
return global["my-old-table"] --> always finds the saved value
```

Hopefully I understood and delivered that Lua example correctly.

----

After this short preface I can finally explain (to myself and to you) the metatable shenanigans her [...]

2024-04-22 03:57 UTC, clifffrey commented
Wow, quite the read!  Thank you.

I agree that the variant that you posted is better than what is currently in the PR. However, a solution that doesn't even use metatables still seems preferable to me, because it would not ever imply that one needed understanding of a 1700 word essay (and would reduce questions/concerns about performance/behavior/etc being different in singleplayer, like what if `/untrust` just sets something to nil?). And I look forward to whatever you come up with.

2024-05-20 17:44 UTC, clifffrey commented
closing due to inactivity, feel free to reopen

2024-05-20 17:44 UTC, closed without merging