Add a new research info window (disabled by default)
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #490
Opened 2024-04-23 05:34 UTC by clifffrey

This is meant to replace the white-flask that allows spectators to view research progress during captains games. Specifically, the current implementation bothers me because it actually moves players between forces, which I believe introduces many possible races/confusion/bugs. I also hope that this implementation might be more useful, as it shows a comparison of both teams at the same time.

I believe that bugs with the existing implementation led to the decision to only enable the white-flask during captain's games. I hope that this new implementation can be enabled in all games.

For now, it is disabled by default, but can be enabled by setting
  `global.bb_show_research_info = "always"`
or
  `global.bb_show_research_info = "spec"`
to enable it, and setting
  `global.bb_show_research_info = nil`
to disable it

I find UI code frustrating to write, because I am accutely aware of millions of ways in which the final UI is not perfect, but it takes a long time and many iterations to make changes, and at some ponit I have to decide "good enough for now".

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2024-04-23 14:49 UTC, vadcx requested changes
Once again I am more about small comments while I learn about the Factorio API and code structure.

2024-04-23 14:49 UTC, vadcx commented on maps/biter_battles_v2/functions.lua
> +	return string.format("%d:%02d:%02d", hours, minutes, seconds)
There's Factorio's own https://github.com/wube/factorio-data/blob/master/core/lualib/util.lua#L58 but it does not include hours. `util.formattime(ticks)`

2024-04-23 14:49 UTC, vadcx commented on maps/biter_battles_v2/gui.lua
>  		time_caption = string.format("Time: %02d:%02d", total_hours, minutes)
Although you didn't touch it, this is yet a third time format, here in hours:minutes

2024-04-23 14:49 UTC, vadcx commented on maps/biter_battles_v2/gui.lua
> +			(global.bb_show_research_info == "spec" and player.force.name == "spectator") then
You forgot to use `is_spec` on the if line, instead comparing to force name again

2024-04-23 14:49 UTC, vadcx commented on maps/biter_battles_v2/research_info.lua
> +            progress_info[tech.name] = progress
Force.research_progress always returns the progress% of current research. This wasn't obvious to me and I find `global.research_info.progress` ambiguous here. Suggestion: rename to `global.research_info.current_progress`

2024-04-23 14:49 UTC, vadcx commented on maps/biter_battles_v2/research_info.lua
> +    end
Shouldn't it be called "toggle_research_info" if a second call destroys the window?

2024-04-23 15:34 UTC, clifffrey commented on maps/biter_battles_v2/functions.lua
> +	return string.format("%d:%02d:%02d", hours, minutes, seconds)
Fun.  I think that hours are easier to read in this case.

2024-04-23 15:42 UTC, clifffrey commented on maps/biter_battles_v2/research_info.lua
> +    end
Perhaps?  One could argue that the primary purpose of the button is still to show the info. Also, that is what the other/similar buttons are named in the code, so there is a naming-consistency argument as well. So I'm inclined to leave this as-is.

Confusingly-to-me, if I remove the "return" here, the behavior is identical, and I don't really understand why.

2024-04-23 15:44 UTC, clifffrey commented on maps/biter_battles_v2/research_info.lua
> +            progress_info[tech.name] = progress
hmm, `LuaForce.research_progress` returns the progress of the current research.  We are storing that in a map because it is possible for the force to keep switching technologies, and have progress on many of them, and I worry that `current_progress` might make people think it is just the progress of the current research.  But really all names are terrible.  A weakness with `progress` as a name is that it sortof implies `progression`, which is inaccurate here.  I guess I'll rename to `current_progress`

2024-04-23 15:44 UTC, clifffrey commented on maps/biter_battles_v2/gui.lua
> +			(global.bb_show_research_info == "spec" and player.force.name == "spectator") then
Thanks, done.

2024-04-25 17:21 UTC, clifffrey commented
I'd love if you could review/approve this change @vadcx (and possibly the new-threat-model change as well)

2024-04-25 17:25 UTC, vadcx approved these changes
I had seen the recent commits and had nothing else to add.

2024-04-25 21:50 UTC, merged