Implement flamethrower turret overlap protection in code
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #495
Opened 2024-04-25 22:37 UTC by clifffrey

It has always slightly bothered me that the rules for what count as overlapping flamethrower turrets are not super clear/explicit, and are very annoying to enforce on new players that don't know the rules.

If there is already one flamethrower turret placed, this prevents another flamethrower turret being placed that is facing the same direction within a 48x2 box centered on the already placed turret. Thus rows of flamethrower turrets must be at least 24 tiles apart (front-to-front).  This distance was chosen because flamethrower turrets have a min range of 6 and a max range of 30.

I added a global variable that can be used to disable this behavior (mostly just in case it causes a strange performance issue or otherwise unexpected bug).

To disable this functionality, run
  /c global.bb_prevent_overlapping_flamers = nil

When testing, this is a useful command
  /c game.player.insert{name="flamethrower-turret", count=100}

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2024-04-25 23:35 UTC, vadcx requested changes

2024-04-25 23:35 UTC, vadcx commented on maps/biter_battles_v2/functions.lua
> +	local half_area_height = 24
hardcoded size 1/...

2024-04-25 23:35 UTC, vadcx commented on maps/biter_battles_v2/functions.lua
> +	local surface = event.created_entity.surface
use `entity` local var

2024-04-25 23:35 UTC, vadcx commented on maps/biter_battles_v2/functions.lua
> +	if global.bb_prevent_overlapping_flamers and event.created_entity.type == "fluid-turret" then
use `entity` local var

2024-04-27 03:10 UTC, clifffrey commented on maps/biter_battles_v2/functions.lua
>  	if not no_turret_blacklist[event.created_entity.type] then return end
Done

2024-04-27 03:10 UTC, clifffrey commented on maps/biter_battles_v2/functions.lua
> +	if global.bb_prevent_overlapping_flamers and event.created_entity.type == "fluid-turret" then
Done

2024-04-27 03:10 UTC, clifffrey commented on maps/biter_battles_v2/functions.lua
> +	local surface = event.created_entity.surface
Done

2024-04-27 03:11 UTC, clifffrey commented on maps/biter_battles_v2/functions.lua
> +		local flame_turrets = surface.find_entities_filtered({type = "fluid-turret", area = area, direction = entity.direction, limit = 2})
So, I agree that this could be done, and that maybe it would be better that way.... but it is not at all clear to me that we would want the same constraints for different turrets or not.... so I'm really unsure of what the desired effect would be on a modded game.

So, I have changed the checks from `type = 'fluid-turret'` to instead be `name = 'flamethrower_turret'`, which I think is a good idea and will help avoid surprising behavior for modded games.

2024-04-27 03:11 UTC, clifffrey commented on maps/biter_battles_v2/functions.lua
>  	})
Good idea. Done.

2024-04-27 03:17 UTC, vadcx commented on maps/biter_battles_v2/functions.lua
> +		local flame_turrets = surface.find_entities_filtered({type = "fluid-turret", area = area, direction = entity.direction, limit = 2})
I would assume the fluid turrets are gonna function the same, however if there's indeed an overlap of fluid turret types you'd want to combine them. Like vanilla flamethrower + some slowing liquid for example?

Rampant mod especially requires different attack types to penetrate armor of diverse biters. Yeah I agree.

2024-04-27 03:17 UTC, vadcx approved these changes

2024-04-27 04:37 UTC, merged