Document Event/EventCore modules
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #496
Opened 2024-04-26 03:07 UTC by vadcx

### Brief description of the changes:

event libs: fix param annotation and finish doc
EmmyLua annotations have a specific syntax. I am not sure if the author
pretended to write annotations (fooled me indeed) or actually had a
plugin that accepted these custom annotations.

The fixed syntax is that of official EmmyLua and it's picked up
correctly by sumneko's LSP too.

require rename utils.event_core: EventCoreI -- renamed the `Public` library holding exported functions to EventCore so code search is usable.

utils/event libs: add documentation

utils/token.lua: add doc

utils/global.lua: add doc

This should be a comment-only change. If the comments don't read clearly or are hard to understand, note it down, it's probably a hole in my understanding of code or explanation. 

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [x] I've not tested the changes. But luac -p syntax check didn't bite me

----

This is the first in this series of PRs. Next I will go on a renaming spree because I am getting lost in all these "inlined" upvalues that only serve the purpose of eliminating a single table lookup IN LUA SPACE, which is already very cheap. It's the Lua code<->C boundary that is expensive. The otherwise readable function names look like variables and with all this heavy "inlining" it's like going through spaghetti.

2024-04-27 02:46 UTC, clifffrey requested changes

2024-04-27 02:46 UTC, clifffrey commented on utils/token.lua
> +-- NOTE:
this is a pretty scary-sounding note to add to the code.

I somewhat feel like you should only put this in if you have an active plan to remove the function/fix this note.  Otherwise I feel like perhaps it should be written in a way that sounds less scary, or is more clearly a statement of your opinion.

2024-04-27 03:23 UTC, vadcx commented on utils/event.lua
> +-- The handler must not be a closure, as that is a desync risk (the caller must ensure the func's state is synchronized across save/load).
The Token library actually does use a **local counter**. Why is it OK? It limits `Token.register` (read it as `Token.register_local`) to only the on_init and on_load stage. This means it's restricted only to functions coming from plain source code. Therefore assuming the order is not changed, old and joining players will load up the same state (from source code functions), despite the token being tracked in an upvalue. It's required for on_init and on_load to be identical though, else on_load produces a different token order than on_init did.

So "upvalues not allowed" is a limited understanding of "as long as you only modify upvalues as part of save loading/map initialization AND in the same way for both, it's ok. I promise". Code updates to a running save could change the order, but *we don't do that around here*, that's a concern for full mods.

I don't like this design. If this explanation is still not any better, that's because I can't find the right terminology to explain the subtle [fuckery](https://www.youtube.com/embed/eW-OMR-iWOE?start=95&end=99) of Factorio's script & save loading architecture.

2024-04-27 03:30 UTC, vadcx commented on utils/event.lua
> +---This probably shouldn't be used, because there's no way to remove a filter through this API and it's unclear how Factorio handles multiple filters, probably it's an AND filter chain, i.e. ALL filt
Ah good link, I was only looking at script.set_event_filter. The answer was 2 clicks away if you knew where to click.

> How to combine this **with the previous filter**. Defaults to "or". When evaluating the filters, "and" has higher precedence than "or".

That would be very confusing to debug! If at least one filter has an AND in the chain, it'll be short-circuiting and cutting off all subsequent filters.

I will need to see how current code expects that to be used, I assume OR.

2024-04-27 03:33 UTC, vadcx commented on utils/event_core.lua
> +-- This is a cursed local function definition
```
local function countDown(x)
        if x > 0 then
                return countDown(x-1)
        end
        return x
end

print(countDown( 42 ))
```

While this style is a very good way to demonstrate how Lua understands it, I think to never have seen this before :sweat_smile: This was supposed to be a fun comment, I want to rewrite the code anyway.

2024-04-27 03:50 UTC, vadcx commented on utils/event_core.lua
> +---The game can register any amount of Nth ticks but only one function for them all.
You are right, I remembered it now without double checking the link even... How's this?

> The game can register any amount of Nth ticks, but each unique Nth tick may only have one handler to it.

or "...associated with it"

2024-04-27 03:50 UTC, vadcx commented on utils/token.lua
> +-- NOTE:
Yes to all three, but considering it's only allowed in load/init stage there's not too much risk. Do you not like the entire comment or just the "LOCALLY stores the var" because you only marked the top header. Like I said in the previous comment, the code updates for us as a pure scenario are practically impossible... unless specifically playing with a save in the dev environment.

You need to point me at the words that struck you, I am blind here. I described the function's implementation in a doc (sic) with the intent of understanding not just its contract but what it does too, to rewrite later. I will need to understand the places where it's used, which is not too few. The comment's length definitely shows my shock/surprise of what it's doing there :grin:

2024-04-28 03:27 UTC, clifffrey commented on utils/event.lua
> +-- The handler must not be a closure, as that is a desync risk (the caller must ensure the func's state is synchronized across save/load).
my claim is that there is a real problem with doing something like the following

```
local function my_func()
  local captured_var = 0
  local function this_is_a_closure()
    captured_var = captured_var + 1
  end
  Event.register(blah, this_is_a_closure())
end
```

Specifically, I believe that the above will behave very surprisingly because of the `load(tostring(func))` stuff, which will change the reference to `captured_var` to be of a global variable instead of the expected/intended local variable.

So, I guess I'm trying to say that there are really a few properties of the passed in function:
1) The passed in function needs to be very careful about any writes to global state (unless it is really in `global`), because synchronizing it can be a real desync risk.
2) The passed in function cannot capture any non-global variables by reference (some people might call this type of function a closure).

Currently, your edit implies to me that (2) is maybe acceptable/possible, if you just synchronize state properly, and I don't think that that is actually the case.

Does this make sense?

2024-04-28 03:29 UTC, clifffrey commented on utils/event.lua
> +---This probably shouldn't be used, because there's no way to remove a filter through this API and it's unclear how Factorio handles multiple filters, probably it's an AND filter chain, i.e. ALL filt
Anyhow, I think that this is potentially safe to use, but there are still some big caveats.  Specifically, if any one callsite is using it for a specific event, then all other uses of that event must also specify their filter.  i.e. if one callsite believes that not setting a filter means "give me everything", then they are in for a surprise when a second callsite is added that sets a filter.

2024-04-28 03:33 UTC, clifffrey commented on utils/event_core.lua
> +-- This is a cursed local function definition
I do not understand.  Your example is a recursive function.  As far as I can tell, `call_handlers` is not a recursive function.

Anyhow, if you want to change this comment to a TODO, that is fine with me.  I just think that "cursed" might mean many different things to different people.

2024-04-28 03:37 UTC, clifffrey commented on utils/token.lua
> +-- NOTE:
Great, please add something like
```
--TODO(vadcx): I plan on removing this function or addressing these notes below shortly
```

Phrases like "mostly useless" can mean many different things to different people.  One might argue that a datastructure like a skip-list is "mostly useless" because most of the time, it is not a good choice, even though it is occasionally very useful.  So, I would much prefer that this comment focus on what is valuable.  I see in the code that it is frequently used for UI popups (I think), and this comment doesn't give me clarity as to whether you believe that this is a good use of the function or not.

2024-05-09 02:21 UTC, clifffrey commented
Are you still interested in making this change?  I still like it and am supportive of documentation improvements.

2024-05-20 17:44 UTC, clifffrey commented
closing due to inactivity, feel free to reopen

2024-05-20 17:44 UTC, closed without merging