Captain : Add total playtime in picking up and ordered by playtime
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #505
Opened 2024-05-05 08:23 UTC by Ragnarok77-factorio

### Brief description of the changes:
Add total play time information in picking popup of captain, list is now ordered by playtime, while keeping having groups together.

Result : 
![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/95619848/4ad469f9-38ed-4596-9b74-76b9c8534888)

To test it easily : 
/c global.total_time_online_players["qqqq"] = 66666

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

Vote : 
https://discord.com/channels/823696400797138974/823771211421974579/1236564023336501268

IN PROGRESS (wait for poll result... but at worst there will be a trace of this possibility if one day people change their time)

2024-05-06 19:45 UTC, penguinencounter approved these changes

2024-05-06 19:58 UTC, clifffrey requested changes
This looks great, thank you!

2024-05-06 19:58 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +									b = finalParentGui.add({type = "label", caption = playtimePlayer})
the contents of this else clause are confusing to me.  I'm pretty sure that this else block should be completely empty (we want to do nothing at all if the inner-iteration doesn't match the group).

2024-05-06 19:58 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +					b = finalParentGui.add({type = "label", caption = playtimePlayer})
you should consider making a function that does the createButton + two calls to gui.add, so that the same function can be called here and in the inner-inner loop above (on line 284).  But, it is ok if you want to leave this as-is also.

2024-05-06 19:58 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +local function insertPlayerByPlaytime(playerName)
hmm, rather than doing an insertion sort, I probably would leave the code as it was before, but add a call to something like

```
table.sort(global.special_game_variables...listPlayers, function(a, b) { return (global.total_time_online_players[a] or 0) > (global.total_time_online_players[b] or 0) })
```

This just seems simpler/less error-prone to me.

2024-05-07 19:09 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +									b = finalParentGui.add({type = "label", caption = playtimePlayer})
I think you are right..? 🤔 I don't like editing stuff outside the PR scope but why not this time, I don't see where this else should be necessary, you are only interested in the group... But shorter code is better so I'm doing it, captain code is way too big, which means harder time debugging/improving it.

2024-05-07 19:10 UTC, Ragnarok77-factorio commented
PR switched to draft until all remarks are taken into account and after I tested it again.

2024-05-07 19:37 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +					b = finalParentGui.add({type = "label", caption = playtimePlayer})
Indeed, that's a good idea, it made the code much more compact, easier to read and debug, and it's always a bad practice to have the code duplicated multiple times (more error prone and so on..). Fixed

2024-05-07 19:40 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +local function insertPlayerByPlaytime(playerName)
At the start I did what you said, but then I realized I didn't like it anymore, because every time you show the list of players, you basically re order it, at every picking, which seems strange logically. 

I think it's better to have the list ordered once and for all, so you don't do the same thing every time you wanna display the player list until all the players were picked.

But if you really think it's better to reorder at every display, I can always revert it and re order the list every time instead like you suggested @clifffrey .

2024-05-07 19:40 UTC, Ragnarok77-factorio commented
Okay, tested it and took all the remarks into account, it seemed to work fine. 
There is just one topic remaining to see what solution we go.

2024-05-07 22:06 UTC, clifffrey approved these changes
Thank you. LGTM

2024-05-07 22:06 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +local function addGuiShowPlayerInfo(_finalParentGui,_button1Name,_button1Text,_pl,_groupName,_playtimePlayer)
it is strange to me to have "_" in front of function arguments.

Also strange that this function body is double-indented.

But, neither one is all that important.

2024-05-07 22:06 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +local function insertPlayerByPlaytime(playerName)
I'm fine with it either way. So no need to change it if you prefer it this way.  I personally get more anxious about implementing-my-own sort algorithms compared to re-sorting unnecessarily, but really, either way is fine.

2024-05-07 22:06 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +									b = finalParentGui.add({type = "label", caption = playtimePlayer})
FWIW, this else clause was not outside of PR scope (I think that you had accidentally added it).

In any case, I agree with you that this is fixed/better now.

2024-05-08 05:02 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +									b = finalParentGui.add({type = "label", caption = playtimePlayer})
Ahh, my bad then !

2024-05-08 05:07 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +local function addGuiShowPlayerInfo(_finalParentGui,_button1Name,_button1Text,_pl,_groupName,_playtimePlayer)
Ah my bad for the double indent, I should really use a real IDE one day for bb... Or we probably even need some formatting "rules" together.

I fixed the double indent and empty space at end of line "Removed double indent in function and empty space at end of line", for the function. Commit "Removed double indent in function and empty space at end of line"

I just wanted name similar to the code where it's called, so just added _ . But if you really want me to edit names I can if needed. I don't really mind either way.

2024-05-08 15:07 UTC, merged