Initial/experimental support for @ping in chat
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #518
Opened 2024-05-17 23:41 UTC by clifffrey

Right now, if any chat message you can see contains "@username" or "@ username", then the following effects happen:
1) if you are at 100% health, you take 1 damage
2) an explosion is drawn at your location (like a grenade going off) 3) for 1 second, a popup saying "PING" appears at the top of the screen

I made these on things that were hopefully not too annoying, but also hard to miss.

Right now, this needs to be manually enabled under Fish -> Config for each user that wants to see the ping effects.

I'm hoping to eventually enable something like this by default (although people could still disable it), but I need feedback about what the right effect is first (and if we need rate limiting or something first).

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2024-05-18 00:38 UTC, sciqu approved these changes
If a player enables then disables the slider, they still get pings. Suspect it's because they remain in "want_pings" table (as false) and it just checks if a player is in that table at all?

big-explosion is too big imo. Tried uranium-cannon-explosion (too inconsistent) and orange-circle-with-arrow (a permanent entity unlike explosions). land-mine-explosion seems good. The GUI popup is annoying because it shifts every other GUI including the massive GUI in top left, for a second.

2024-05-18 00:46 UTC, sciqu commented
A sound effect will be cool

2024-05-18 00:55 UTC, clifffrey commented
The problem with not doing the GUI change is that if a player is in map mode (like most spectators are likely to be, for instance), they will not see anything.  Thus I think that some form of popup is a good idea.  We could use player.gui.screen instead to just put it at an absolute position.... I am very much open to suggestions.

I essentially always play on mute, so I don't end up thinking about sound effects....

2024-05-18 01:03 UTC, penguinencounter commented
Definitely go with `player.gui.screen`. Easiest positioning option is centered (`auto_center` etc) but absolute positioning based on resolution and scale is doable.

2024-05-18 01:23 UTC, clifffrey commented
I'd love if someone would propose what the actual Frame should look like... It feels strange to me just having a label saying PING... but I guess this is just the first version...

2024-05-18 01:27 UTC, ness056 commented
Maybe instead of a visual thing it would be better to play a sound, something like the discord ping sound.

2024-05-18 01:35 UTC, penguinencounter commented
@clifffrey who sent the message, contents of the message

mockup:
![cliff_build says @penguinencounter please stop dropping deconstruction planners on the iron belt; 30 seconds ago - click to dismiss](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/49845522/c15769da-934a-4bea-860d-9ef6d930356d)

2024-05-18 05:19 UTC, clifffrey commented
> If a player enables then disables the slider, they still get pings. Suspect it's because they remain in "want_pings" table (as false) and it just checks if a player is in that table at all?

Indeed, thank you. Fixed.

2024-05-19 05:57 UTC, clifffrey commented
Interesting... When looking for code that could play a sound, I found `utils.alert`, which does a very similar thing, including playing a sound, and has a little progress bar for when it auto-disappears.
![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/273840/66c39ab9-2429-450f-a6b8-8010fe711f49)

I appreciate the mock-up of what the popup should possibly look like.  It is actually hard for me to implement that, because right now, I just get the whole message, i.e. "(north) cliff_build [to south]: my message" and I would need to either search for ":" and remove whatever is before that, or do more code refactoring, and I decided to just leave the text of the message unaltered for now.

So, now it looks like this, at the top of the screen:
![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/273840/edb8107c-563f-4a95-87a0-053c0458277f)

I will add sound support if someone tells me what sound to play and what volume to use (i.e. what lua snippet for sound playing I should use)

2024-05-19 19:45 UTC, penguinencounter requested changes
* there is no maximum size of the window. The alignment code seems to assume a 400-unit wide dialog, so perhaps setting `width = 400` would work
![long message. notification window is overflowing off the screen](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/49845522/fa35d079-b149-4cda-8da7-fdb685344764)

2024-05-19 19:45 UTC, penguinencounter commented on maps/biter_battles_v2/main.lua
> +local function do_ping(to_player, from_player_name, message)
This function is called inconsistently:
* in `Public.print_message_to_players`: `ping_fn(playerOfForce, playerNameSendingMessage, msgToPrint)`
* in `on_console_chat`: `ping_fn_map[pinged_name](player, event.message)`

Calls from `on_console_chat` miss `from_player_name` and provide the message instead, leaving `message` nil and a blank space in the ping UI.

Also, `on_console_chat` invocations don't include the sending player username in the message.

2024-05-20 03:51 UTC, clifffrey commented on maps/biter_battles_v2/main.lua
> +local function do_ping(to_player, from_player_name, message)
Fixed.

2024-05-21 16:29 UTC, developer-8 commented
- just message to some team triggers ping 
 ![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/88335092/948a98b6-fcf5-449e-8ea8-54875da1ec2c)
- /whisper, /reply, /r - not ping
- additional message sound to standard message sound  and damage are excessive with popup

2024-05-21 19:43 UTC, developer-8 approved these changes

2024-05-21 19:46 UTC, developer-8 commented
might need `/ignore-ping username` command to block pings from trolls, but it can be done in another PR

2024-05-21 22:28 UTC, merged