UI improvement
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #535
Opened 2024-06-03 18:10 UTC by ness056

### Brief description of the changes:
- Disable simple tags, according to this [discord poll](https://discord.com/channels/823696400797138974/823771211421974579/1241772236268896276).
- Unify the comfy panel, the team manager, the difficulty poll, the research tab, the captains GUIs and other minor things into vanilla-like frames: in screen element, draggable and can either be closed with a white cross or with the esc or E keys. To do it I added a new file in utils/ui to create new frames of that type easily in the future.
- Some minor changes to the comfy panel style to make it look more like the other GUIs. This will avoid [this type of crappiness](https://ibb.co/NpzMFQP) when the comfy panel is opened at the same time as the map info frame.
- The only two exceptions are the map info frame and the poll frame which are still in the top left corner and cannot be moved.

### Tested Changes:
- [x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2024-06-03 23:44 UTC, penguinencounter requested changes

2024-06-03 23:44 UTC, penguinencounter commented on utils/ui/closable_frame.lua
> +    closable_frame.close_all(game.get_player(event.player_index))
```suggestion
    closable_frame.close_all(game.get_player(event.player_index) --[[@as LuaPlayer]])
```

2024-06-03 23:44 UTC, penguinencounter commented on maps/biter_battles_v2/team_manager.lua
> +			local force_name = string.sub(player.gui.screen["custom_team_name_gui"].children[2].name, 10)
Reference the child by name if possible

2024-06-03 23:44 UTC, penguinencounter commented on utils/ui/closable_frame.lua
> +        global.closable_frame.closable_frames[player.index].main
the object could be invalid (for example, if the frame is `destroy()`ed without notifying closable_frame)

2024-06-03 23:44 UTC, penguinencounter commented on comfy_panel/admin.lua
> -        player.gui.center['mini_camera'].destroy()
This (and new line 543) don't communicate to `closable_frame` so the frame stays in its `global` table

2024-06-03 23:44 UTC, penguinencounter commented on comfy_panel/main.lua
> +    return player.gui.screen.comfy_panel.comfy_panel_inside.tabbed_pane.tabs[player.gui.screen.comfy_panel.comfy_panel_inside.tabbed_pane.selected_tab_index].content
Probably should assign `player.gui.screen.comfy_panel.confy_panel_inside.tabbed_pane` to a variable here.

2024-06-03 23:44 UTC, penguinencounter commented on comfy_panel/main.lua
> +    local tabbed_pane = player.gui.screen.comfy_panel.tabbed_pane
missing `comfy_panel_inside`, errors when indexed with `tabs` one line later

2024-06-03 23:44 UTC, penguinencounter commented on comfy_panel/main.lua
> +            player.gui.screen.comfy_panel.destroy()
No signal to `closable_frame`, so it still thinks it's open (?)

2024-06-03 23:44 UTC, penguinencounter commented on utils/ui/closable_frame.lua
> +	local flow = frame.add({ type = "flow", direction = "horizontal" })
This `flow`'s `horizontal_spacing` needs to be `8` for Factorio parity.

2024-06-03 23:44 UTC, penguinencounter commented on comfy_panel/poll.lua
>          Tabs.comfy_panel_restore_left_gui(event.player)
`comfy_panel_restore_left_gui` doesn't exist anymore.
```suggestion
```

2024-06-03 23:44 UTC, penguinencounter commented on maps/biter_battles_v2/functions.lua
> +	if player.gui.screen["map_intro_frame"] then player.gui.screen["map_intro_frame"].destroy() end
As a side effect of moving to `screen`, the frame **doesn't scroll anymore** when the info text is too large for the screen (the scrollbar was part of the `center` slot)

2024-06-03 23:44 UTC, penguinencounter commented on maps/biter_battles_v2/difficulty_vote.lua
> +		math.floor((global.difficulty_votes_timeout - tick) / 3600) .. " minutes left.",
I don't think the *close button tooltip* is the right place for this information. Just give it its own label or something?

2024-06-04 05:08 UTC, clifffrey reviewed
Awesome change!

2024-06-04 05:08 UTC, clifffrey commented on utils/ui/closable_frame.lua
> +local function create_draggable_frame(player, name, caption, close_tooltip, no_dragger)
I feel like the callsites would be slightly clearer if close_tooltip and no_dragger were part of an options table that could be passed in.  Specifically so that the argument names would appear at the callsite, as it is not obvious what the random string and boolean are otherwise.

Feel free to ignore this comment though, it is not critical that everything be easy to see at the callsite, and with good enough editor support to show the \@param documentation, it doesn't really matter

2024-06-04 13:17 UTC, ness056 commented on comfy_panel/admin.lua
> -        player.gui.center['mini_camera'].destroy()
When you destroy it, the on_gui_closed will be called and it will delete the element from the global table.

2024-06-04 13:18 UTC, ness056 commented on comfy_panel/main.lua
> +            player.gui.screen.comfy_panel.destroy()
same as https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/pull/535#discussion_r1625154843

2024-06-04 13:21 UTC, ness056 commented on utils/ui/closable_frame.lua
> +	if global.closable_frame.closable_frames and
I have no idea what happened here, in my vscode everything is normal and the tabulation is normal

2024-06-04 13:34 UTC, ness056 commented on utils/ui/closable_frame.lua
> +local function create_draggable_frame(player, name, caption, close_tooltip, no_dragger)
Done in next commit

2024-06-04 13:37 UTC, ness056 commented on utils/ui/closable_frame.lua
> +        global.closable_frame.closable_frames[player.index].main
fixed in next commit

2024-06-04 13:41 UTC, ness056 commented on maps/biter_battles_v2/functions.lua
> +	if player.gui.screen["map_intro_frame"] then player.gui.screen["map_intro_frame"].destroy() end
Fixed in next commit

2024-06-04 13:52 UTC, ness056 commented on maps/biter_battles_v2/difficulty_vote.lua
> +		math.floor((global.difficulty_votes_timeout - tick) / 3600) .. " minutes left.",
I have put it here because it was in the close button before, but yeah it's kinda dumb. It has it's own label in next commit.

2024-06-04 14:00 UTC, ness056 commented on comfy_panel/main.lua
> +    local tabbed_pane = player.gui.screen.comfy_panel.tabbed_pane
this function only use was in modules/map_info.lua which is not used since the map_info was moved from the comfy panel to its own thing (the question mark button) a few years ago. The function and the file are deleted in the next commit

2024-06-04 15:31 UTC, clifffrey approved these changes

2024-06-04 15:31 UTC, clifffrey commented on utils/ui/closable_frame.lua
> +	if global.closable_frame.closable_frames and
you must have your tab-width set to 4, such that 4 spaces looks identical to a tab.  You can still see the difference in vscode if you try and click one or two spaces in from the front of the line.  You can also see the difference in the github code review interface, i.e. 
![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/273840/8d154a99-beea-4f0a-bc81-3f1bd72911f0) which is from https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/pull/535/files#diff-044df456a0924561e8372ec4460a1f6c271efd847fbe140c55c2ef79aa3dce3b

In vscode, you can do something like select all, command palette -> "untabify" to replace all tabs with 4 spaces  (or tabify to replace all 4-spaces with tabs).

In general, our files are not consistent (different people use different editors with different defaults), so this isn't a big deal.  However, if you are adding a new file, it is nice if the file is consistent about its use of tabs vs spaces.

2024-06-04 16:01 UTC, ness056 commented on utils/ui/closable_frame.lua
> +	if global.closable_frame.closable_frames and
Should be good now

2024-06-04 17:02 UTC, developer-8 commented
```
4460.933 Script /temp/currently-playing/utils/event_core.lua:30: Error caught: LuaGuiElement API call when LuaGuiElement was invalid.
4460.933 Script /temp/currently-playing/utils/event_core.lua:32: stack traceback:
	..../temp/currently-playing/utils/event_core.lua:32: in function <..../temp/currently-playing/utils/event_core.lua:29>
	[C]: in function '__index'
	./temp/currently-playing/comfy_panel/player_list.lua:611: in function <.../temp/currently-playing/comfy_panel/player_list.lua:534>
	[C]: in function 'xpcall'
	....temp/currently-playing/utils/event_core.lua:49: in function 'call_handlers'
	..../temp/currently-playing/utils/event_core.lua:61: in function <..../temp/currently-playing/utils/event_core.lua:56>
```
Found a bug that I could not reproduce on the current server, so I believe it belongs in this PR. Steps to reproduce:
1. Join team 
2. In fish menu->player list click your name to open "where camera"
3. Click spectate

Also saw a similar error but can't reproduce and don't know if it's related to this PR
```
utils/event_core.lua:30: Error caught: LuaGuiElement API call when LuaGuiElement was invalid.
/utils/event_core.lua:32: stack traceback:
	..../utils/event_core.lua:32: in function <..../utils/event_core.lua:29>
	[C]: in function '__index'
	.../comfy_panel/special_games.lua:117: in function <.../comfy_panel/special_games.lua:92>
	[C]: in function 'xpcall'
	..../utils/event_core.lua:49: in function 'call_handlers'
	..../utils/event_core.lua:61: in function <..../utils/event_core.lua:56>
```

2024-06-06 22:00 UTC, merged