implement burners balance.
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #546
Opened 2024-06-25 17:01 UTC by PlayerNoon

### Brief description of the changes:
implementing game-vote.
https://discord.com/channels/823696400797138974/823771211421974579/1248907791087960068

how it is done.
on join or rejoin team function checks if u haven't got burners then check if in enemy team is connected player that also didn't get burners. if yes then insert 10 burners to both of you

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2024-06-25 17:23 UTC, clifffrey reviewed
A few comments:

1) It seems important to me that at least some effort is made to preserve join-order (i.e. players who join the team first should get burners first).  So I would suggest using something like `table.insert(global.waiting_for_burners[force], player)` and you could use a version of `removeStringFromTable` to remove players when you give them burners.

2) Maybe not all that important, but right now, you potentially give players burners when they stop spectating, and when they first join a team, but not when they connect to the game.  So it is possible for both teams to have a player that has never been given burner miners at the same time.  Theoretically, you could/should check for this in the `on_player_joined_game` event as well.

3) perhaps training mode should disable this functionality?

4) I'd like there to be some way of turning this functionality on/off. Probably via the Fish -> Config tab would be best

2024-06-27 22:20 UTC, clifffrey reviewed
My main comment in this review is really still about point (1) in my first review.

I'd love if you could respond to my point (2) in the first message I sent, even if it is just to say "I agree that this could happen, but fixing it seems too complicated/not-worthwhile".

I want to add a few more potential point as well:

5) Do we perhaps need/want some communication to users about why they sometimes have burner miners and sometimes do not. I'd rather not have to just keep checking my inventory to see if burner miners showed up. This could perhaps be done by calling `do_ping()`, or perhaps better to just create floating text above the player, or perhaps better to do `player.print()`, or perhaps some combination of the above. Similarly when people join and do not get any burners, it might be good to give them a message about why.

6) what happens if a user's inventory is full when we try and give them burner miners?

2024-06-27 22:20 UTC, clifffrey commented on maps/biter_battles_v2/gui.lua
>  	local force = "north"
perhaps rename `force` to `enemy_force`?

2024-06-27 22:20 UTC, clifffrey commented on maps/biter_battles_v2/gui.lua
> +	for enemy_player_name, _ in pairs(global.got_burners) do
so, this block of code will still make it be effectively random which member of the enemy_force actually gets burners when a new player joins. And I think that we'd rather that whoever has been on enemy_force the longest.

I'd suggest doing this by doing something like `global.waiting_for_burners[force][player_name] = game.tick` and then this loop could iterate over `for player_name, waiting_since = pairs(global.waiting_for_burners[enemy_force])` and choose the `player_name` with the lowest value of `waiting_since`.

A different idea (which is what I suggested in my earlier comment) would be to have waiting_for_burners be a list/table/array/queue that was in order.

Does this make sense?

2024-06-28 06:30 UTC, PlayerNoon commented on maps/biter_battles_v2/gui.lua
> +	for enemy_player_name, _ in pairs(global.got_burners) do
quote from. https://lua-api.factorio.com/latest/auxiliary/libraries.html#%E2%80%A2-pairs()-/-next()
"In standard Lua, the order of iteration when using pairs() is arbitrary. Because Factorio has to be deterministic, this was changed in Factorio's version of Lua. Factorio's iteration order when using next() (which pairs() uses for iteration) depends on the insertion order: Keys inserted first are iterated first."

so in the code i wrote the order is determined by first join to the team. is that ok for you?

2024-06-28 18:46 UTC, PlayerNoon commented
> I'd love if you could respond to my point (2) in the first message I sent, even if it is just to say "I agree that this could happen, but fixing it seems too complicated/not-worthwhile".
@clifffrey 
what is wrong with point 2? i added call in on_player_joined_game.

2024-06-28 21:34 UTC, clifffrey commented
> > I'd love if you could respond to my point (2) in the first message I sent, even if it is just to say "I agree that this could happen, but fixing it seems too complicated/not-worthwhile".
> 
> @clifffrey what is wrong with point 2? i added call in on_player_joined_game.

ahh, yes you did. I just missed it. Thanks.

2024-07-02 00:56 UTC, clifffrey requested changes
This is looking great. I think that it'll be good to go after this round.

Thank you for responding to the review comments!

I also just wanted to check that you explicitly decided to do nothing in response to my comment of "Similarly when people join and do not get any burners, it might be good to give them a message about why."  I'm ok with either decision here, I just want to make sure that you didn't miss the comment/idea.

2024-07-02 00:56 UTC, clifffrey commented on maps/biter_battles_v2/gui.lua
> +	player.print("You have recived 10 burners, check inventory",{ r = 1, g = 1, b = 0 })
"received"

I'll point out that you could use something like `[item=burner-mining-drill]` if you want to include the icon, and show the name in whatever language the user is using.  But, this is up to you if you want to do it.

2024-07-02 00:56 UTC, clifffrey commented on maps/biter_battles_v2/gui.lua
> +	global.got_burners[player2.name] = true
I'd consider making a function that covers lines 415-422, and calling it once per player

2024-07-02 00:56 UTC, clifffrey commented on maps/biter_battles_v2/gui.lua
>  	player2.insert { name = "burner-mining-drill", count = 10 }
I'm a bit surprised that this isn't written as
```
local num_inserted = player.insert { ..., count = 10 }
if num_inserted < 10 then
  ....spill_item_stack(...)
end
```

or, if you want to keep the `get_insertable_count` call, perhaps use its value in the `.insert( count = can_insert )` call?

2024-07-02 10:34 UTC, PlayerNoon commented on maps/biter_battles_v2/gui.lua
>  	player2.insert { name = "burner-mining-drill", count = 10 }
i have tried to return earlier but it didn't work for some reason.
now i tried it again after your comment and found why it didn't.
in spill_item_stack "Item stack count has to be a positive integer", if it is 0 then it fails the code, 
when it fails the code it also fails the return value from player.insert. i always received 10... 
i didn't understand why because the spill_item_stack is called after the player.insert so it should not affect the return value...

2024-07-02 10:35 UTC, PlayerNoon commented on maps/biter_battles_v2/gui.lua
> +	global.got_burners[player2.name] = true
ok

2024-07-02 10:35 UTC, PlayerNoon commented on maps/biter_battles_v2/gui.lua
> +	player.print("You have recived 10 burners, check inventory",{ r = 1, g = 1, b = 0 })
ok

2024-07-02 10:38 UTC, PlayerNoon commented
`I also just wanted to check that you explicitly decided to do nothing in response to my comment of "Similarly when people join and do not get any burners, it might be good to give them a message about why." I'm ok with either decision here, I just want to make sure that you didn't miss the comment/idea.`

i was thinking about it. imo message " u didn't get burner" every time u join feels annoying, also i think it would make code too complicated.

2024-07-02 17:55 UTC, clifffrey commented on maps/biter_battles_v2/gui.lua
> +	for i = 1 , 0, -1 do
I would have done this either by creating a new function, and just calling the function twice, or as
`for _, player_to_insert in ipairs({player, player2}) do`
because I find either of those ways to be a bit clearer.  But if you want to keep this as you have it, that is ok too.

2024-07-02 17:55 UTC, clifffrey commented on maps/biter_battles_v2/gui.lua
> +	local inserted
you should move this variable to be inside of the loop, because we don't actually want to remember changes to it from one iteration to the next

2024-07-02 17:55 UTC, clifffrey commented on maps/biter_battles_v2/gui.lua
>  	player2.insert { name = "burner-mining-drill", count = 10 }
it should not be possible for a failure to impact earlier lines of code. I'm not sure what was happening, but I'm glad that things are working now!

2024-07-02 18:04 UTC, PlayerNoon commented on maps/biter_battles_v2/gui.lua
> +	for i = 1 , 0, -1 do
i would like to leave it.

2024-07-02 18:10 UTC, PlayerNoon commented on maps/biter_battles_v2/gui.lua
> +	local inserted
ok

2024-07-02 18:10 UTC, PlayerNoon commented on maps/biter_battles_v2/gui.lua
> +		inserted = game.players[player.name].insert { name = "burner-mining-drill", count = burners_to_insert }
yup

2024-07-02 18:33 UTC, clifffrey approved these changes

2024-07-03 07:15 UTC, merged