Special games, add ore type in mixed ore
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #552
Opened 2024-07-03 15:33 UTC by PlayerNoon

### Brief description of the changes:
Add another funny ore type in special panel > mixed ore

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2024-07-04 07:11 UTC, clifffrey approved these changes

2024-07-04 07:11 UTC, clifffrey commented on maps/biter_battles_v2/mixed_ore_map.lua
> +					ore = ores[2]
you could be evil and make there be no pattern... i.e.
`ore = ores[(pos.x * largeprime1 + pos.y * largeprime2) % 4 + 1]`
or somesuch, and you could change `space*2` to just `space` above... but probably that is too evil.

2024-07-08 07:36 UTC, clifffrey requested changes
I'd love if you responded to the comments, even if it is just to say "thanks, but I'm not making that change"

2024-07-08 08:59 UTC, PlayerNoon commented on maps/biter_battles_v2/mixed_ore_map.lua
> +					if math.random(1,1000) > 998 then
nice idea. but i try to follow how the code is already written, everyone uses integers so why change it.

2024-07-08 09:01 UTC, PlayerNoon commented on maps/biter_battles_v2/mixed_ore_map.lua
> +					ore = ores[2]
i don't understand your code, i don't know how to apply it so can't test it.

2024-07-08 09:05 UTC, PlayerNoon commented
why my responses for your comments are important? i don't have experience so don't understand. can't merge it without? do i have to resolve all conversations? or just to have a nice conversation? :D

2024-07-08 17:49 UTC, clifffrey commented
> why my responses for your comments are important? i don't have experience so don't understand. can't merge it without? do i have to resolve all conversations? or just to have a nice conversation? :D

Great question!

If you don't respond, then I don't know if you have read the comment or not, and I don't know if we communicated successfully or not.

In the end, it really is important that the code does more than "just work" - because this is not the last change that we will make. Other people will also make changes to the code in the future, so anything we can do to make it more understandable/better/more-consistent is worthwhile, even if it means that making one change takes a bit longer.

2024-07-08 17:49 UTC, clifffrey approved these changes

2024-07-08 17:49 UTC, merged