burners-balance. now player drop burners when left game
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #556
Opened 2024-07-09 08:55 UTC by PlayerNoon

### Brief description of the changes:
Player will spill all his burners on surface on_player_left_game

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2024-07-10 05:45 UTC, clifffrey requested changes
I don't understand why we do it when the player leaves, but not if they just click the "spectate" button. Should this happen on spectate as well?

I'm also not really sure if this change is actually worthwhile... the behavior seems confusing/surprising to me.  I'd really prefer that we just check for the case where the player has exactly 10 burners, and remove the burners (and remove the player from `global.got_burners` as well).

2024-07-10 07:59 UTC, PlayerNoon commented
> I don't understand why we do it when the player leaves, but not if they just click the "spectate" button. Should this happen on spectate as well?
> 
> I'm also not really sure if this change is actually worthwhile... the behavior seems confusing/surprising to me. I'd really prefer that we just check for the case where the player has exactly 10 burners, and remove the burners (and remove the player from `global.got_burners` as well).

1. Totally forgot about spectate, i will add this.
2. if i am adding burners always for 2 players then if i want remove then i have to do this for both players also. i can't do that in case when 1 of them have already placed them. we end in situation where team with 2 players have 20 burners and team with 1 player have 10 burners. 
In case of dropping them on the surface the team with 1 player will have 20 burners and team with 2 players also 20 burners.

2024-07-13 06:28 UTC, clifffrey requested changes
This is just about ready. Thank you.

It would be great if the change consistently used ", " rather than just "," when separating arguments to functions, which is what most of the existing code does.

2024-07-13 06:28 UTC, clifffrey commented on maps/biter_battles_v2/gui.lua
> +	if not (inventory == 0) then
you should write this as `if inventory ~= 0 then` or `if inventory > 0 then`

2024-07-13 06:28 UTC, clifffrey commented on maps/biter_battles_v2/gui.lua
> +	local inventory = player.get_item_count("burner-mining-drill")
rename `inventory` to `num_burners` or something. Otherwise I'd assume that this is `player.get_inventory()`

2024-07-13 07:56 UTC, PlayerNoon commented on maps/biter_battles_v2/gui.lua
> +	if not (inventory == 0) then
yup

2024-07-13 07:56 UTC, PlayerNoon commented on maps/biter_battles_v2/gui.lua
> +	local inventory = player.get_item_count("burner-mining-drill")
right

2024-07-13 08:03 UTC, clifffrey approved these changes

2024-07-13 08:05 UTC, merged