Implement task system for captain game
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #561
Opened 2024-07-11 17:53 UTC by Ragnarok77-factorio

### Brief description of the changes:
Create tasks list in captain event.
The first player joining the task group can edit the name, other players can't.
The captain can edit all task group name and bypass this security above.

Example of view : 
Button added on top : 
![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/95619848/3c5122a2-132a-47c7-a520-b830051fabae)
If you join a task  : 
![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/95619848/bbf37a86-d444-45a6-a2c9-97185ebdcdf0)

If you have no task : 
![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/95619848/f1262537-2741-4829-aab2-24f26c1d66d5)

View of captain : 
![image](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/assets/95619848/fd1bd112-368f-42e5-a88b-eb386f4731a1)

### To test it : 
Create a local captain game event, then use manager to switch team, to see the GUI. 
You can do that to see the captain view of it (just close gui and open it again to have correct view ) : **/c global.special_games_variables["captain_mode"]["captainList"][1]="yourPlayerName"**

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2024-07-12 23:45 UTC, clifffrey reviewed
High level comments:

1) we might want the option of disabling this (for instance, if it causes crashes or something), so you could consider checking `global.captain_group_organization_disabled` or something in a bunch of places. But, meh, not a big deal either way
2) I'd encourage you to at least think of putting this in its own file. captain.lua could then have something like `local CaptainGroupOrganization = require '...'` and then just have a few calls to it.
3) maybe reduce 15 to something like 9?  "main builder, main support, main oil, threatfarming, outpost1-5" is the most I could imagine being useful... but maybe I am just not imaginative enough
4) We could consider always rendering the assigned group name at the top of people's screens... but probably it is a bad idea.  Or at least always doing it during planning or something?  but, shrug, probably not worthwhile to begin with
5) I am generally anxious that this feature might not end up getting much use. But this comment isn't all that directly actionable.  I hope that this feature does get a lot of use, and I am excited for us to try it. Although if we cannot get the feature to be widely used, we should remove it in 4 weeks or something. Does that make sense?

2024-07-12 23:45 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +	if player.gui.screen.group_selection then player.gui.screen.group_selection.destroy() end
perhaps write this as `player.gui.screen["group_selection"]` to be consistent with how it is done throughout the file

2024-07-12 23:45 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +	return player.name == special["captainList"][2] or player.name == special["captainList"][1]
this could just be `isStringInTable(player.name, special["captainList"]), but ok as you have it also

2024-07-12 23:45 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +    for i = 1, 15 do
how about putting 15 into a file-local variable like `local max_num_organization_groups = 15` or something?

2024-07-12 23:45 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +            player_list.caption = "[color=blue]" .. table.concat(group.player_order, ", ") .. "[/color]"
you could use stuff from `pretty_print_player_list` to get player colors here too if you wanted

2024-07-12 23:45 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +	frame.add{type="label", name="list_players_without_task", caption="Players without task : [color=red]".. table.concat(update_list_of_players_without_task(force), ", ") .. "[/color]"}
it might be simpler to make the `create_team_organization_gui` function as simple as you possibly can make it, and just unconditionally call `update_team_organization_gui` at the end of `create_team_organization_gui`, to avoid a bunch of duplicated code.

2024-07-12 23:45 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +		-- For players editing their own group
you might want to verify that the player is allowed to set the name of the group here. Specifically, with the code as you have it, if there is high lag to a player, they could potentially leave a group first, and then rename the group after they left it (but before their UI updated to disable the button). It also might not actually be possible (if you destroy the button rather than just make the button invisible).... so, meh, it is fine if you leave the code as-is. I just have had to make a bunch of changes in the past where I make these `on_gui_click` handlers double-check that people are really allowed to do what they are doing, so I thought that I would mention it.

2024-07-13 05:35 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +	if player.gui.screen.group_selection then player.gui.screen.group_selection.destroy() end
Sure, done

2024-07-13 05:49 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +	return player.name == special["captainList"][2] or player.name == special["captainList"][1]
Agreed, this is better to do that way suggested. Code updated.

2024-07-13 05:59 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +    for i = 1, 15 do
Yes I agree, it will be more flexible that way. Code updated.

 I though of doing something that can adapt, length size, but it was way too much of a headache, maybe could be another improvement in another PR if needed

2024-07-13 06:37 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +		-- For players editing their own group
Oh I see what you mean. I will let as is for now but if there is ever an issue about it, will update code like you explained.

2024-07-13 06:58 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +            player_list.caption = "[color=blue]" .. table.concat(group.player_order, ", ") .. "[/color]"
Good idea, let's do it that way too, to be similar to other code. I updated it, and kept only the red color for player list without tasks. We will see what players think of it.

Code updated

2024-07-13 07:17 UTC, Ragnarok77-factorio commented
For high level comments : 
-I hope it doesn't crash, I tested it, it seemed fine. There will be probably some feedbacks about it so it will probably receive a few updates on it over time.

-For the amount of lines of 9 instead of 15 : threatfarm, main builder, main support, power coal, nuke, oil, outpost 1 to 5 (lasers, rocket, spam, spam2, alone troll outpost..), but that would be for a big game, I reduced it to 11, we'll update the variable if needed (or if it varies a lot, maybe make the table dynamic size instead).

-Yes I don't know too if it's better only in this tab or show next to name or something... We'll see over time I guess.

-I think some captains might use it, some will not care at all. But even if not all captain uses it but some do, I will be very happy, and if it improves teamplay or if it makes more players wanna captain (much each easier to organize with this global view of team organization). We will know over time to be honest, probably test a few weeks, then poll if they like it or not (and if they don't like this task implementation, just remove it), or maybe if they would like some stuffs to be edited for them to use it more..

2024-07-13 07:18 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +	frame.add{type="label", name="list_players_without_task", caption="Players without task : [color=red]".. table.concat(update_list_of_players_without_task(force), ", ") .. "[/color]"}
Agreed, I will update code, will take a bit of time. Hold !

2024-07-13 07:19 UTC, Ragnarok77-factorio commented
Oh and for that comment about another file, sure I can try to do it. Will take a bit of time

2024-07-13 07:20 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +	if update_list_of_players_without_task(force) ~= nil then listPlayersWithoutTask = table.concat(update_list_of_players_without_task(force), ", ") end
FWIW, you can do this whole line as
`listPlayersWithoutTask = table.concat((update_list_of_players_without_task(force) or {}), ", ")`
if you want to, but it is fine either way

2024-07-13 07:30 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +	if update_list_of_players_without_task(force) ~= nil then listPlayersWithoutTask = table.concat(update_list_of_players_without_task(force), ", ") end
Ah I always have trouble to do this kind of stuff, good remark, 2 lines into 1 and less code/line, it's better. Code updated, done.

2024-07-13 08:52 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +	frame.add{type="label", name="list_players_without_task", caption="Players without task : [color=red]".. table.concat(update_list_of_players_without_task(force), ", ") .. "[/color]"}
Done ! Great idea, it's way better that way to code it. No duplicate code and so on.

2024-07-13 11:14 UTC, Ragnarok77-factorio commented
Done, I moved all functions to another lua file to have a lighter captain lua file. Ready for review

2024-07-14 20:50 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +	--Start of all conditions for team organization gui in captain
you could just as easily define your own `on_gui_click` event in the other file, which I think would be better/clearer.  You could consider doing it for the other events as well, but they seem less important either way.

2024-07-14 20:50 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +		-- Remove player from current group
you do this below as well (in `leave_task_group`), so I'd probably make a function for it that you just call in both places

2024-07-14 20:50 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +	elseif element.name:sub(1, 9) == "set_name_" then
I worry that "set_name_" might not be a globally unique name prefix always... might be worth having cpt_task_ be a prefix of all your your elements or something?  I don't feel too strongly though.

2024-07-15 17:47 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +	--Start of all conditions for team organization gui in captain
I would say there is some code in there that should have done the same thing too. But I agree it's cleaner to have his own gui click event for task. Moved all of stuff related to task group (not other things, I don't like doing different things in thesame PR, a PR should be focused to his code only) to the other file, done.

2024-07-15 17:47 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +		-- Remove player from current group
Agreed, no need for duplicate, done.

2024-07-15 17:47 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +	elseif element.name:sub(1, 9) == "set_name_" then
Yes I guess it will be easier to identify, done with cpt_task_

2024-07-17 14:59 UTC, Ragnarok77-factorio commented
Ready for review again

2024-07-17 18:25 UTC, clifffrey requested changes
beautiful!  Just this one last tiny change and I'll submit

2024-07-17 18:25 UTC, clifffrey commented on comfy_panel/special_games/captain_task_group.lua
> +local function cpt_get_player(playerName)
I'd just make the other declaration of this function not-local, rather than duplicating it.

The "more beautiful" fix would be to create cpt_util.lua which contained this function (and any other common dependencies), and have both the existing captain.lua and this new captain_task_group.lua require it. But, shrug.  I find a single global function less scary than a duplicated function.

2024-07-17 19:52 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain_task_group.lua
> +local function cpt_get_player(playerName)
I can't make the function in captain lua file without local, since I would to make a require of captain in captain task lua file, which will do a infinite loop between the 2 lua files. I could have made the function not local in captain task group, but it would be strange to do this way as this is a not really a function made for task group, but more a common function for all captain codes.

So instead I made what you asked, which is a captain_utils file. Code updated

2024-07-17 19:53 UTC, Ragnarok77-factorio commented
Thanks for all the review by the way.
Code updated, ready for review @clifffrey

2024-07-17 22:58 UTC, clifffrey commented on comfy_panel/special_games/captain_task_group.lua
> +local function cpt_get_player(playerName)
You could have just made it a global variable (i.e. removed the word "local", but don't put it as part of `Public`.

But, it is great/better the way that you did it anyways.

2024-07-17 22:59 UTC, clifffrey approved these changes
Thanks for putting up with all of my comments!

2024-07-17 22:59 UTC, merged