Sound enhancement
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #563
Opened 2024-07-12 08:50 UTC by RedRafe

### Brief description of the changes:

Added sound effects as enhanced feedbacks on some player actions:

- on special captain game mode enabled
- during 10s of captain's starting countdown
- on map rerolled
- on poll ended
- on @ and whispers pings
- on commands: /where, /inventory, /load-quickbar

Players can choose to have the additional sound FX disabled by switching ON/OFF their own settings. Default will be **ON** (sounds FX are generally very short and should not overlap with other in-game sounds, faking in-game major events such as biter attacks, game lost/won, research completed etc etc....)

![Uploading Screenshot from 2024-07-12 10-47-31.png…]()

> Note: when rerolling a new map & charting the whole width, the API caps on chunk requested so during the initial forced charting time, sounds are played at the current chart location and are not audible from players unless the charted chunk is same of player's and/or players are in map view at current chunk charted. This is a limitation of the current sound API but could be improved in 2.0 with new system.

### Tested Changes:
- [x] I've tested the changes locally in SP
- [ ] I've not tested the changes in MP

2024-07-12 23:54 UTC, clifffrey requested changes
As a random-thought, if we wanted to fix the charting during map load, instead of unconditionally charting the whole area right at the beginning, we could only chart some of the map (like one column or something), and then schedule more charting to be done inside of either `on_chunk_charted` or `on_chunk_generated` or something. (and we could, in that scheduling, also schedule charting of spectator island again each time)

But, not clear to me that it is actually worth fixing that issue... just wanted to throw out the idea.

I almost always play muted, so I don't personally have much of an opinion about this change, but it seems reasonable to me and the code looks good.

2024-07-12 23:54 UTC, clifffrey commented on comfy_panel/config.lua
> +    if tooltip then
I would just put this in the `t.add({ type = 'label', caption = description, tooltip = tooltip})` line above, no need for the `if` that way

2024-07-13 02:32 UTC, RedRafe commented
@clifffrey IIRC some players reported that charting the full 4k width was quite demanding on their PC during the 30s reroll, so maybe this will be a good follow-up PR on its own.
I personally like having the map fully revealed on both sides at the start, aesthetically and functionally, as it benefits both spectators and players to have the map view of it all.

I did some testing when trying to fix the sound bug thing, and my approach was queuing chunk requests every X time during a longer period (using the Task system) instead of a bulk request as it is now. The issue was that if the map gets voted to reroll again, then the requests from the previous map & current map would overlap & get messy. Maybe I should implement a separate queue that also gets flushed upon map reroll so they wouldn't overlap. But yeah, a lot of changes... I'd like to have some inputs from the community as well, just to understand where we want to go. Then implementing will be straightforward

2024-07-13 05:35 UTC, RedRafe commented on comfy_panel/config.lua
> +    if tooltip then
Good catch, I didnt even notice it was already there. Ty!

2024-07-13 06:16 UTC, clifffrey approved these changes

2024-07-13 06:17 UTC, merged