Synchronize voting time with displayed time in gui.
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #579
Opened 2024-07-26 20:15 UTC by PlayerNoon

### Brief description of the changes:
now voting time will use gui time instead of game.ticks_played
previously voting was closing even if no-one joined team.  
now players have 10 min to vote from the actual match start which is started by multiple actions like crafting mining.

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2024-07-27 03:42 UTC, clifffrey requested changes

2024-07-27 03:42 UTC, clifffrey commented on commands/difficulty_voting_commands.lua
> +    if not global.active_special_games["captain_mode"] then
can you switch this around?  I think that it is easier if the logic is inside of `if global.active_special_games["captain_mode"]` rather than with the `not`

However, even more than that, I think that you can just not have this special case at all?  It used to be the case that captains mode would do difficulty voting after teams were picked, but before the game started, and thus captains mode needed the old logic. However, now that is no longer how captains mode works (since #555).

So, if you keep this logic here, I'd like you to explain why it is necessary.

2024-07-27 06:49 UTC, PlayerNoon commented on commands/difficulty_voting_commands.lua
> +    if not global.active_special_games["captain_mode"] then
1. good idea i will switch it. 
2. at first try i tried to simply change game.ticks_played to Functions.get_ticks_since_game_start()
but i met too complicated problems in captains code which i am not able to understand.

2024-07-31 04:03 UTC, clifffrey approved these changes

2024-08-06 05:27 UTC, merged