Automatic captain system
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #597
Opened 2024-08-16 13:42 UTC by Ragnarok77-factorio

### Brief description of the changes:
After reroll poll ends, captain poll for 45s (same location as reroll poll) if > 26 players online.
If there are more than 14 yes votes and at least 66% or more yes votes than no vote, captain event starts (hard conditions because it's hard getting captains and have enough players, so you better show you really want it).

==
After 5 minutes : 
If < 2 captain, event canceled.
If 2 captains are here, it starts the picking phase (random for the first to pick).
If > 2 captains, the 2 captains chosen will be the 2 with most playtime
If one of the 2 captain leaves before game starts (unfreeze), during picking or prepa phase, event canceled.
Prepa phase auto start after 10 min, if both captains doesnt say yes before.
If captain leaves during the game, the player with most playtime will be the new captain.
Captain can elect a new captain after picking/prepa phase ended (if he needs to leaves, he can just give it instead of using most playtime criteria)

### Tested Changes:
- [ ] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

Vote : https://discord.com/channels/823696400797138974/823771211421974579/1271714940935340063
(still 16h left but with 16 yes 3 no, I doubt it won't pass..)

2024-08-17 05:34 UTC, clifffrey requested changes
are you sure that `tournament_mode` will actually be cleared at the end of the game?  I feel like it is not currently cleared at the end of captains games today, but maybe I am wrong.

2024-08-17 05:34 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +function Public.pick_player_with_most_playtime(player)
it is very surprising that this function takes a `player` as an argument rather than a `force_name`.  I'd suggest changing it and putting the mapping of `captain_player -> force` at the callsite.

2024-08-17 05:34 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +    return playerTimes[1].name
this needs to handle the "there are no players" case (even if it does something drastic, like cancel the captains event)

2024-08-17 05:34 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +    for _, pl in ipairs(game.forces[forceOfCaptain].connected_players) do
rather than constructing the special list and then calling sort, it might be simpler to just loop through the players looking for the maximum value of playtime?

2024-08-17 05:34 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +        if special.initialPickingPhaseStarted and special.prepaPhase then
it might be reasonable to relax this to just `if not special.initialPickingPhaseEnded`?  Like, it is theoretically fine if the captain changes after all picks have done.  Also, I worry about a captain doing something like logging off to look at a map, or accidentally quitting when fiddling with discord or something...  But also fine to leave as-is

2024-08-17 05:34 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +            game.print('Not enough captains to automatically start captain event...', { r = 1, g = 0, b = 0 })
it might be worthwhile to print out a message every 30 seconds or something so that people understand what is happening even if the GUI isn't open (and even the GUI is maybe not as clear as a line or two of text would be)

2024-08-17 05:34 UTC, clifffrey commented on maps/biter_battles_v2/game_over.lua
> +    Event.remove_removable(defines.events.on_player_joined_game, automatic_captain_buttons_token)
rather than adding/removing the event, I'd encourage you to just always have the event, but use an if condition to make the event be a no-op. I think that it is much simpler that way.

2024-08-17 05:34 UTC, clifffrey commented on maps/biter_battles_v2/game_over.lua
> +    if Gui.get_top_element(player, 'automatic_captain_frame') then
I'd probably name this something like `automatic_captain_poll_frame` to avoid ambiguity

2024-08-17 05:34 UTC, clifffrey commented on maps/biter_battles_v2/game_over.lua
> +        Sounds.notify_all('utility/armor_insert')
does this sound conflict with any existing reroll timer sounds?

2024-08-17 05:34 UTC, clifffrey commented on maps/biter_battles_v2/game_over.lua
> +local function draw_automatic_captain_poll_gui(player)
did you consider just extending the existing reroll UI to (optionally) include another question?
I feel like it might be simpler to do that way, as lots of things will break if the two are not in-sync with one another (i.e. we might end up trying to start a captains game after players have already joined otherwise or something)

2024-08-17 05:34 UTC, clifffrey commented on maps/biter_battles_v2/game_over.lua
> +    if global.bb_settings.automatic_captain and #game.connected_players > 25 then
I would suggest putting 25 in `global.bb_settings.automatic_captain_min_connected_players_for_vote` but then don't actually add a config UI for it. It would allow admins to set it using `/c`, and makes it much easier to test

2024-08-17 05:34 UTC, clifffrey commented on maps/biter_battles_v2/init.lua
> +    global.automatic_captain_time_limit = 45 * 60 -- 45 seconds
I never know whether to put things in `bb_settings` or not.  Anyhow, I'm fine with them in either location.  I have a vague gut-feeling that anything that is essentially read-only should probably be in `bb_settings`... but, shrug

2024-08-17 06:53 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/game_over.lua
> +    if Gui.get_top_element(player, 'automatic_captain_frame') then
Yes I like the new name, done.

2024-08-17 07:00 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/game_over.lua
> +        Sounds.notify_all('utility/armor_insert')
Mh, I never paid attention to this kind of son to be honest, and I had this one added from a copy & paste (I didn't plan to add a sound).

From the code I'm seeing in sounds.lua, it's just a player.play_sound function, so I doubt doing it again with same file is an issue..?

If you want I can just remove it instead, to be safer.

2024-08-17 07:05 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/game_over.lua
> +    if global.bb_settings.automatic_captain and #game.connected_players > 25 then
Okay sure, why not, done ! Added a variable for it, it will give more flexibility to admins for very unique case.

2024-08-17 07:07 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/init.lua
> +    global.automatic_captain_time_limit = 45 * 60 -- 45 seconds
Yeah I never know which one to use. I let the code as is since you are fine with it.

I'm fine with either location too, don't really care which one..

2024-08-17 07:28 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +            game.print('Not enough captains to automatically start captain event...', { r = 1, g = 0, b = 0 })
Understood ! Done every 30s as requested.

I like this idea too, also added a message if it's missing captains too, so they are not surprised at the end.

2024-08-17 08:21 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +local decrement_timer_captain_prepa_token = Token.get_counter() + 1 -- predict what the token will look like
I don't understand it either to be honest, for me token system is a black box, and I never digged for hours on trying to understand how token works, I've just copied the existing reroll code and adapted it to this new code, there is the same code for reroll poll, this "get_counter".

Maybe another dev could explain it to us, because someone developed it initially..

2024-08-17 11:00 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/game_over.lua
> +    Event.remove_removable(defines.events.on_player_joined_game, automatic_captain_buttons_token)
Sure, why not, easier code to understand, done and pushed.

 I also added a print on why the vote failed, so everyone understand why the captain vote failed, as the algorithm is not just reaching x% but also having enough yes.

2024-08-17 11:12 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +        if special.initialPickingPhaseStarted and special.prepaPhase then
The captain is kinda needed to prepare the initial strategy so it's not a big mess.

But I agree the algorithm is very harsh, the captain is required to stay at least until the event starts. If he has an internet issue, or anything else, it will be canceled. But that was the algorithm in the poll so..

Anyways I think all these conditions, variable to start the captain game, the time, and so on, will be probably edited over time and players will request changes on it to improve it, just a first version. Even the conditions of the poll just to start a captain event automatically, is very very hard.

2024-08-17 11:21 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +    global.automatic_captain_prepa_time_remaining_for_start = global.automatic_captain_prepa_time_remaining_for_start
Oh, I never noticed yet this bug of time for reroll sometimes not being updated.

Maybe it would be better to do a task that is run once , and that this task start another task in 1s, again and again, until the end is over...?

But if I did it that way, I would also need to edit reroll code as it doesn't make sense to have the same need (poll), having 2 very different code, and really don't want to edit reroll code in this PR as it's working well. If I wanted to do that, I would probably do another PR that is editing that for both of them (and maybe it would also fix the bug you talked about on reroll), but already quite busy with this PR and other stuff, and not goal of this PR, I leave the code as is.

For now I let the code as is.

2024-08-17 11:28 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/game_over.lua
> +local function draw_automatic_captain_poll_gui(player)
The algorithm of the poll was to only show captain poll after the reroll has ended, or maybe misunderstood this remark..?

For the conflict of reroll and captain poll, it's 2 different codes and the captain poll is called to be starting only after the reroll poll ended with no, so I have a hard time seeing how it could have issue.

I also tested it with 4 players total, I didn't have any issue with the 2 polls, so the code seems fine.

For sure it's different from having 30 players at same time, so my test is not perfect, maybe I forgot something but it seemed fine (I also tried to disconnect/reconnect too). And then it also rejoins my comment about token too

2024-08-17 11:55 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +function Public.pick_player_with_most_playtime(player)
Ah, yes true in the end we just want the force, not the player, so sure, why not ! 
I edited the function, it takes a force now, done.

2024-08-17 12:29 UTC, Ragnarok77-factorio commented
> are you sure that `tournament_mode` will actually be cleared at the end of the game? I feel like it is not currently cleared at the end of captains games today, but maybe I am wrong.

I tested it, after automatic event ended by natural cause, once a new map was generated, I couldnt join until the polls were over , tournament mode was kept on but it's on purpose, there was a poll recently that doesn't allow players to join before reroll is over and it was implemented..?
Or am I wrong..?

I also tried to do "/c global.tournament_mode = false" and it removed the tournament mode too.

2024-08-17 12:38 UTC, Ragnarok77-factorio commented
Okay, the issue is in classic captain mode with referee, the tournament mode is not removed at the end, I added it even if it's outside the scope of this PR (and would only happen in this pr if the automatic captain option is disabled and there was a captain game just before, which is a lot of if 🤣 ) , as it was just a one liner, in the commit  : "@Ragnarok77-factorio
[Bugfix for classic referee captain : disable tournament mode once it](https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/pull/597/commits/f6ca95f9e0cb957a75a2e9d4d7d07fcf7b4b7b07)"

2024-08-17 12:59 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +    return playerTimes[1].name
I added a condition to check not nil before doing the rest of the code to handle it, so it won't crash an error if there is only 1 captain playing and no player and the last player, the captain, left too.

I think this case will happen in a server crash, quite rare then. So once the server is back, they should all rejoin.
I don't think I ever saw a 0 player in a captain game, and if that's the case, probably game over/game crash.. Are you fine with that idea ..?

2024-08-19 02:07 UTC, clifffrey commented on comfy_panel/special_games/captain.lua
> +local decrement_timer_captain_prepa_token = Token.get_counter() + 1 -- predict what the token will look like
ok, just delete these lines that I believe do nothing, and move the `local` word to the next line.

2024-08-19 05:19 UTC, clifffrey commented on maps/biter_battles_v2/game_over.lua
> +local function draw_automatic_captain_poll_gui(player)
I guess regardless of whether the polls run at the same time or back-to-back, it still might make sense to reuse all of the code as the reroll poll?

I just worry about copying/pasting so much code (that neither one of us really understands all that well), compared to making a smaller change that just makes the existing UI stick around longer or show 2 questions or whatever...

Anyhow, I guess I don't know the right answer either, just trying to explain my hesitation.

2024-08-19 05:23 UTC, clifffrey commented on maps/biter_battles_v2/game_over.lua
> +            global.tournament_mode = false
maybe add a print here, or else just be sure to warn all admins about this behavior change, as it'll matter if we try and do back-to-back captains games

2024-08-19 05:24 UTC, clifffrey commented
I'm sorry for creating merge conflicts for you. If you have trouble with them, I can resolve the conflicts for you, just let me know.

I'm also not sure if you want to wait and see if it makes more sense to do the "community picks" mode captain event for this case rather than forcing people to volunteer to captain. I'm fine either way on that though (perhaps community picks won't work well, I dunno).

2024-08-19 14:43 UTC, Ragnarok77-factorio commented
> I'm sorry for creating merge conflicts for you. If you have trouble with them, I can resolve the conflicts for you, just let me know.
> 
> I'm also not sure if you want to wait and see if it makes more sense to do the "community picks" mode captain event for this case rather than forcing people to volunteer to captain. I'm fine either way on that though (perhaps community picks won't work well, I dunno).

No worry, I will try to solve it, and if I can't find any good solution, I will ask you.

For the community picks, for me it's 2 different things, one is another kind of captain (captainless with a referee and admin that manually start), and this one is making captain automatic with 2 captains without referee and without admin (but you can still do a manual captain with referee or manual captain with community picks).

Even before community picks, there was also another mode, bucket one with random too. When I did the poll about this implementation poll got approved with massive yes for this automatic captain with 2 captains elected too, so no need to wait (once the conflicts and so on are resolved, and will be interesting to test it live, best way to know how good/bad it is really).

But I'm sure after a few weeks of testing, it will be edited I think, people will either say it was finally a bad idea, maybe they will say criteria are too harsh (never start) or too easy (start too much).

Or maybe it will work fine because people really wanting to have captain game will see the countdown 10/9/8s and the print and become a captain to get it running (one time I was referee and had not enough captains despite x minutes of waiting. I said I cancel in 2 minutes, I did the countdown before closing it : 10s, 9s...and at 1s before cancel, I got the 2 captains 😆.

It's just the implementation of the poll, I doubt the algorithm/criteria of the poll is perfect, will be improved over time if it's really used (or maybe even deleted, who knows what community will think over time of it).

2024-08-19 15:11 UTC, Ragnarok77-factorio commented
Conflicts resolved but I need to verify it's still working now.

2024-08-19 15:28 UTC, Ragnarok77-factorio commented on maps/biter_battles_v2/game_over.lua
> +            global.tournament_mode = false
Agreed, it is better. I added the print, done.

The captain mode enable tournament mode and send the players back to island but still, between the time the map is chosen, and the time an admin goes to start captain game, there is still a delay, so it is still a bit required to make admins aware it was disabled.

2024-08-19 16:33 UTC, Ragnarok77-factorio commented on comfy_panel/special_games/captain.lua
> +local decrement_timer_captain_prepa_token = Token.get_counter() + 1 -- predict what the token will look like
I did this change like you suggested : 
local decrement_timer_automatic_captain_token = Token.register(function()

I removed the get_counter+1, and got an error . I think I understand a bit more, it probably identify the token by a a unique id (counter+1), and every time it's called, it increases 1 and do the function, since the function calls itself, it needs this weird system.

And I'm not surprised it broke the code, because the dev who made it wouldn't have bothered to add this line if it was useless in the first place. At least now we know, wasn't a mistake

2024-08-20 17:34 UTC, clifffrey approved these changes
Thanks! I'm excited about this direction.

2024-08-20 17:35 UTC, merged