reveals silos, if multi silo special is active
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #613
Opened 2024-09-07 00:49 UTC by Arktischer

to let people know how many silos are still alive, they are revealed (with fish)
### Tested Changes:
- [ x] I've tested the changes locally or with people.
- [ ] I've not tested the changes.

2024-09-07 02:22 UTC, clifffrey requested changes
I'm excited about this change! It will make the special better

2024-09-07 02:22 UTC, clifffrey commented on maps/biter_battles_v2/gui.lua
>                  game.forces[f[1]].chart(surface, {
I'd be a bit more comfortable if this had something like `if entity.valid` - specifically the silos in multi-silo can die at almost any point, and I don't know whether this code will run before or after the `on_entity_died` event or whatever.

2024-09-07 02:22 UTC, clifffrey commented on maps/biter_battles_v2/gui.lua
> +                table.add_all(entities, global.multi_silo[f[2]])
maybe add both forces silos?  I could imagine wanting to know where the silos are on my own team as well...

2024-09-07 02:22 UTC, clifffrey commented on maps/biter_battles_v2/gui.lua
> +                table.add_all(entities, global.multi_silo[f[2]])
Relatedly (and less important), we could theoretically always reveal their locations to spectators in this function as well (i.e. unconditionally doing it for `game.forces.spectator.chart` during the special)

2024-09-07 04:31 UTC, Arktischer commented on maps/biter_battles_v2/gui.lua
> +                table.add_all(entities, global.multi_silo[f[2]])
if you add both forces silos you have somewhat unexpected behavior in that you have to send fish to reveal your own silo.. better i do that before the fish check

2024-09-07 05:35 UTC, Arktischer commented
its getting late for me.. i think this should work, but it shows enemy silos without fish. Dont know why, probably just tired and its obvious. Will fix it tomorrow

2024-09-07 09:53 UTC, Arktischer commented
game.forces.spectator.chart() reveals map, even if im in a team and
game.forces.spectator.connected_players is empty.
in spectator mode game.forces.north.chart() also reveals map, if i joined north before.
Do you know anything about that ?

2024-09-07 10:10 UTC, Arktischer commented
.chart() for north or south always gets revealed for spectator.. i guess it makes sense this way. That means its not necessary to chart explicitly for spectators

2024-09-07 10:19 UTC, Arktischer commented
should work now

2024-09-08 00:01 UTC, developer-8 commented
These changes should be made to the special game code and not to the scenario code.

2024-09-08 01:51 UTC, clifffrey commented
We should actually add the multi-silo special to the scenario, it is run often enough that I don't want to break it when we next refactor something.

2024-09-08 16:48 UTC, Arktischer commented
> These changes should be made to the special game code and not to the scenario code.

I do agree, but is that something i can help with? Where would i find the up to date multi-silo code ?

2024-09-08 17:20 UTC, developer-8 commented
> > These changes should be made to the special game code and not to the scenario code.
> 
> I do agree, but is that something i can help with? Where would i find the up to date multi-silo code ?

Idk if it up to date but here https://discord.com/channels/823696400797138974/1264598829559189565

2024-09-08 20:58 UTC, Arktischer commented
I moved it to the multi-silo code, i will post the proposed changes in the mentioned dc channel.

2024-09-08 20:58 UTC, closed without merging