Update readme.md
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #618
Opened 2024-09-14 15:11 UTC by outstanding-factorio

Enhanced README with comprehensive project details and community resources

This pull request significantly improves the README.md file to provide a more detailed and accurate description of the Biter Battles project. Key changes include:

1. Added links to official community resources:
   - Discord server: https://discord.gg/ZsNNTcPfXm
   - BiterBattles.org website: https://www.biterbattles.org/

2. Expanded the overview section with more detailed game mechanics

3. Included information about special game modes and features

4. Added a new section on Competitions and Events, highlighting:
   - Captain Games
   - Biter Battles Championship (BBC)
   - Various ranking systems (science scores, ELO)

5. Provided links to additional resources such as leaderboards and ranking pages

6. Improved the structure with a more comprehensive table of contents

7. Updated the Contributing and Bug Reporting sections with in-game commands

8. Maintained existing information about installation, gameplay, and contributing

These changes aim to give new players and contributors a better understanding of the Biter Battles project, its community, and available resources. The enhanced README should help attract more players and potential contributors by showcasing the depth and active community of the project.

2024-09-14 15:24 UTC, clifffrey commented on readme.md
> +### Strategies
I feel like it might make more sense to leave much of this to the wiki?  https://freebb.miraheze.org/wiki/Main_Page

In any case, I see a huge amount of overlap between this page and the wiki.  I feel like it is unlikely that potential players are going to start with the github page... this page is more about developers I think?  So really having this page primarily have links to the other pages and only a very short description of the scenario makes the most sense to me.

2024-09-15 09:45 UTC, outstanding-factorio commented on readme.md
> +### Strategies
I am fine with removing some descriptions, but I think there should be some links and especially to install guide, testguide and discord. Maybe a link to the wiki could also be added.

2024-09-15 19:24 UTC, clifffrey commented on readme.md
> +### Strategies
Yep, agreed

2024-10-13 17:49 UTC, clifffrey requested changes
Let me know once you have removed a bunch of the descriptions and you think it is ready for another round of review.

2024-10-14 20:13 UTC, majrie commented
> Let me know once you have removed a bunch of the descriptions and you think it is ready for another round of review.

Sure. Just a bit time constrained at the moment.

2025-01-20 02:09 UTC, clifffrey commented
Closing as no progress has been made in a long time. Feel free to reopen if it is ready for more review

2025-01-20 02:09 UTC, closed without merging