Biter AI refactor
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #631
Opened 2024-11-03 09:08 UTC by RedRafe

- AI fixes for biter controls
- UI, teleport, restart smaller fixes

2024-11-03 10:24 UTC, cogito123 commented
Bosses don't work

Error while running event level::on_entity_damaged (ID 111)
LuaRendering doesn't contain key get_y_scale.
stack traceback:
        [C]: in function '__index'
        __level__/functions/boss_unit.lua:57: in function 'set_healthbar'
        __level__/functions/boss_unit.lua:97: in function <__level__/functions/boss_unit.lua:82>

2024-11-03 10:50 UTC, RedRafe commented
@cogito123 did renders got ported to 2.0?

2024-11-03 12:37 UTC, cogito123 commented
I ported what was failing. If I didn't trigger the issue, I didn't fix it.
Did you test boss code?

```
Error while running event level::on_entity_damaged (ID 111)
__level__/functions/boss_unit.lua:99: attempt to index global 'healthbar' (a nil value)
stack traceback:
        __level__/functions/boss_unit.lua:99: in function <__level__/functions/boss_unit.lua:83>
```

2024-11-03 12:46 UTC, RedRafe commented
no, how are you getting bosses? Also, were waves this big even in 1.1?

![Screenshot from 2024-11-03 13-42-40](https://github.com/user-attachments/assets/2354e2af-a229-4d57-836c-73b4427f7bca)

2024-11-03 12:51 UTC, cogito123 commented
I manually throw few K of utility science.
I don't think waves were this big in 1.1

2024-11-03 15:30 UTC, cogito123 commented
I patched remaining thing I found during biter testing

2024-11-03 15:30 UTC, clifffrey requested changes
Overall looks great. Just a few comments.

2024-11-03 15:30 UTC, clifffrey commented on maps/biter_battles_v2/ai_strikes.lua
> +local function print_admins(message, color)
how about changing this to be `debug_print` and remove the admin-only logic in it?

2024-11-03 15:30 UTC, clifffrey commented on maps/biter_battles_v2/ai_targets.lua
> +                { unit_number = entity.unit_number, position = entity.position, entity = entity }
Just to mention it... because you changed it from working with positions to working with entities, it means that the case where the entity is deleted when the biters are on the way will behave differently.  Probably no big deal, just hopefully it doesn't crash or strand the biters or anything.

2024-11-03 15:30 UTC, clifffrey commented on maps/biter_battles_v2/main.lua
> +        for _, biter_force_name in pairs({ 'north_biters', 'south_biters' }) do
I don't understand what this block of code is for.  Why would `force.get_evolution_factor` change/be higher?

If we want to keep the block of code, please add a comment explaining why we want it.

2024-11-03 16:51 UTC, RedRafe commented on maps/biter_battles_v2/ai_strikes.lua
> +local function print_admins(message, color)
done

2024-11-03 16:53 UTC, RedRafe commented on maps/biter_battles_v2/ai_targets.lua
> +                { unit_number = entity.unit_number, position = entity.position, entity = entity }
Yes, I checked that no other part of the code used this function. I kept position and unit number in case this interface is used by special code that arent kept in repo.
AI module always checks for `(entity and entity.valid)` before using it so it should be accounted for that the entity may become invalid between when it's saved and when it's later used.

2024-11-03 16:57 UTC, RedRafe commented on maps/biter_battles_v2/main.lua
> +        for _, biter_force_name in pairs({ 'north_biters', 'south_biters' }) do
This piece of code I added to keep `force::evolution_factor` and `storage.bb_evolution` in synch between the two. Because it was not consistent which to use, so this solves any ambiguity and once a second they are sync'd together so it is reasonably safe in code to change one or the other

2024-11-03 17:03 UTC, RedRafe commented on maps/biter_battles_v2/main.lua
> +        for _, biter_force_name in pairs({ 'north_biters', 'south_biters' }) do
I can remove this

2024-11-04 02:37 UTC, clifffrey approved these changes

2024-11-04 02:38 UTC, merged