Adjust nests value by evolution
Factorio-Biter-Battles/Factorio-Biter-Battles pull request #633
Opened 2024-11-03 11:55 UTC by RedRafe

Biter nests health increases with evo (see [FFF-427](https://factorio.com/blog/post/fff-427)]. This adjusts the score obtained by killing spawners according to the new approximated function of:

`y = 350 + 3150 * (x^2.25)`

rerulting in

`factor = 1 + 9 * (evolution^2.25)`

which describes the factor of `nest_health / base_prototype_health` in function of evo(x)

2024-11-03 15:42 UTC, clifffrey requested changes
It would be good to update the summary to be explicit that this only increases the threat-benefit of killing nests up to 100% evolution.  Specifically that the health/threat increases do not continue to scale after that.

I feel like this will be a net-buff to threatfarming, but I could be wrong.  So many things about the balance might need tweaking post 2.0, and this change seems like a good start/approximation of what might be good, so I like it.

2024-11-03 15:42 UTC, clifffrey commented on maps/biter_battles_v2/ai.lua
> +    if entity.type == 'unit-spawner' then
I would use `elseif` or I would change it to be `factor = factor * ...`

2024-11-03 15:42 UTC, clifffrey commented on maps/biter_battles_v2/functions.lua
> +---@param params table
you can make the type checker happier (or at least pickier) if you do this as
```
---@param params {surface: string|integer|LuaSurface}
```

2024-11-03 17:13 UTC, RedRafe commented on maps/biter_battles_v2/ai.lua
> +    if entity.type == 'unit-spawner' then
done

2024-11-03 17:13 UTC, RedRafe commented on maps/biter_battles_v2/functions.lua
> +---@param params table
ah, thanks!

2024-11-03 17:17 UTC, RedRafe commented
@clifffrey sorry, which summary?

2024-11-04 02:39 UTC, clifffrey commented
> @clifffrey sorry, which summary?

I just meant the PR description, which will turn in to the commit description.
I edited it, adding "Note that this only applies up to 100% evo, after that, the threat reduction for killing (and health value of) the biter nests does not change."

2024-11-04 02:40 UTC, clifffrey approved these changes

2024-11-04 02:41 UTC, merged